/**
 * Extra Lenten recipes inspired by Mia Kouppa’s nistisima list.
 * Food photos bundled from Mia Kouppa; kitchen notes are original OrthoDaily text
 * (not scraped recipe copy). Adjust to taste and your parish’s fasting practice.
 */
import type {
  FastingRecipe,
  LocalizedLines,
  LocalizedText,
  RecipeCategory,
  RecipeDifficulty,
  RecipeFastLevel,
} from '../../src/lib/recipes/fastingRecipes';

function L(en: string, ru: string, el: string): LocalizedText {
  return { en, ru, el };
}

function lines(en: string[], ru: string[], el: string[]): LocalizedLines {
  return { en, ru, el };
}

function R(input: {
  id: string;
  level: RecipeFastLevel;
  category: RecipeCategory;
  difficulty: RecipeDifficulty;
  prepMinutes: number;
  cookMinutes: number;
  servings: number;
  servingSize: LocalizedText;
  title: LocalizedText;
  summary: LocalizedText;
  ingredients: LocalizedLines;
  steps: LocalizedLines;
  tips: LocalizedLines;
  notes?: LocalizedText;
}): FastingRecipe {
  return input;
}

export const MIA_KOUPPA_EXTRA_RECIPES: readonly FastingRecipe[] = [
  R({
    id: 'brownie-baked-oatmeal',
    level: 'wine_oil',
    category: 'breakfast',
    difficulty: 'easy',
    prepMinutes: 10,
    cookMinutes: 35,
    servings: 6,
    servingSize: L('1 square (~120 g)', '1 кусок (~120 г)', '1 κομμάτι (~120 γρ.)'),
    title: L('Brownie baked oatmeal', 'Овсянка-брауни', 'Ψητή βρώμη τύπου brownie'),
    summary: L('Cocoa baked oats with banana — a Lenten breakfast that tastes like dessert.', 'Овсянка с какао и бананом в духовке — постный завтрак как десерт.', 'Ψητή βρώμη με κακάο και μπανάνα — νηστίσιμο πρωινό σαν επιδόρπιο.'),
    ingredients: lines(
      [
        '2 ripe bananas, mashed',
        '2 cups (180 g) rolled oats',
        '3 tbsp cocoa powder',
        '2 tbsp olive oil or tahini',
        '2 tbsp maple or date syrup',
        '1½ cups (360 ml) water or plant milk',
        '1 tsp baking powder',
        'Pinch of salt',
        'Optional: 2 tbsp chopped walnuts',
      ],
      [
        '2 спелых банана',
        '2 стакана (180 г) овсянки',
        '3 ст.л. какао',
        '2 ст.л. масла или тахини',
        '2 ст.л. сиропа',
        '1½ стакана (360 мл) воды или растительного молока',
        '1 ч.л. разрыхлителя',
        'Щепотка соли',
        'По желанию: 2 ст.л. орехов',
      ],
      [
        '2 ώριμες μπανάνες',
        '2 φλ. (180 γρ.) βρώμη',
        '3 κ.σ. κακάο',
        '2 κ.σ. ελαιόλαδο ή ταχίνι',
        '2 κ.σ. σιρόπι',
        '1½ φλ. (360 ml) νερό ή φυτικό γάλα',
        '1 κ.γ. baking powder',
        'Πιτσίλισμα αλάτι',
        'Προαιρετικά: 2 κ.σ. καρύδια',
      ],
    ),
    steps: lines(
      [
        'Heat oven to 180°C / 350°F. Oil a small baking dish.',
        'Mix bananas, oil/tahini, syrup, and liquid. Stir in oats, cocoa, baking powder, salt, and nuts.',
        'Spread in the dish. Bake 30–35 minutes until set.',
        'Cool 10 minutes; cut into 6. Serve warm.',
      ],
      [
        'Духовка 180°C. Смажьте форму.',
        'Смешайте банан, масло/тахини, сироп, жидкость. Добавьте овсянку, какао, разрыхлитель, соль, орехи.',
        'Выложите. Пеките 30–35 мин.',
        'Остудите 10 мин; разрежьте на 6.',
      ],
      [
        'Φούρνος 180°C. Λαδώστε ταψί.',
        'Ανακατέψτε μπανάνα, λάδι/ταχίνι, σιρόπι, υγρό. Βρώμη, κακάο, baking powder, αλάτι, ξηρούς καρπούς.',
        'Απλώστε. Ψήστε 30–35 λεπτά.',
        'Κρυώστε 10 λεπτά· κόψτε σε 6.',
      ],
    ),
    tips: lines(
      [
        'Leftovers reheat well with a splash of plant milk.',
        'On strict days, skip oil and use mashed banana only for richness.',
      ],
      [
        'Остатки разогревайте с растительным молоком.',
        'В строгий пост — без масла, только банан.',
      ],
      [
        'Τα περισσεύματα ζεσταίνονται με φυτικό γάλα.',
        'Σε αυστηρή νηστεία, χωρίς λάδι.',
      ],
    ),
  }),
  R({
    id: 'berry-orange-smoothie',
    level: 'strict',
    category: 'drink',
    difficulty: 'easy',
    prepMinutes: 5,
    cookMinutes: 0,
    servings: 2,
    servingSize: L('1 glass (~300 ml)', '1 стакан (~300 мл)', '1 ποτήρι (~300 ml)'),
    title: L('Berry orange smoothie', 'Смузи ягоды и апельсин', 'Smoothie μούρα και πορτοκάλι'),
    summary: L('Cold orange juice blended with berries and banana — quick strict-fast drink.', 'Апельсиновый сок с ягодами и бананом — быстрый строгий напиток.', 'Χυμός πορτοκαλιού με μούρα και μπανάνα — γρήγορο αυστηρό ρόφημα.'),
    ingredients: lines(
      [
        '1 cup (240 ml) fresh orange juice',
        '1 cup (140 g) frozen mixed berries',
        '1 ripe banana',
        '½ cup (120 ml) cold water',
        'Optional: ice cubes',
      ],
      [
        '1 стакан (240 мл) апельсинового сока',
        '1 стакан (140 г) замороженных ягод',
        '1 банан',
        '½ стакана (120 мл) воды',
        'По желанию: лёд',
      ],
      [
        '1 φλ. (240 ml) χυμό πορτοκαλιού',
        '1 φλ. (140 γρ.) κατεψυγμένα μούρα',
        '1 μπανάνα',
        '½ φλ. (120 ml) νερό',
        'Προαιρετικά: πάγος',
      ],
    ),
    steps: lines(
      [
        'Add everything to a blender.',
        'Blend until smooth, 30–45 seconds.',
        'Pour into 2 glasses. Serve immediately.',
      ],
      [
        'Всё в блендер.',
        'Взбейте 30–45 сек.',
        'Налейте в 2 стакана.',
      ],
      [
        'Όλα στο μπλέντερ.',
        'Χτυπήστε 30–45 δεύτερα.',
        'Σε 2 ποτήρια.',
      ],
    ),
    tips: lines(
      [
        'Frozen berries chill the drink without watering it down.',
        'Add a spoon of soaked oats for more substance.',
      ],
      [
        'Замороженные ягоды охлаждают без лишней воды.',
        'Ложка замоченной овсянки — сытнее.',
      ],
      [
        'Τα κατεψυγμένα μούρα δροσίζουν χωρίς πολύ νερό.',
        'Λίγη βρώμη για πιο χορταστικό.',
      ],
    ),
  }),
  R({
    id: 'apple-oatmeal-muffins',
    level: 'wine_oil',
    category: 'breakfast',
    difficulty: 'easy',
    prepMinutes: 15,
    cookMinutes: 25,
    servings: 12,
    servingSize: L('1 muffin (~70 g)', '1 маффин (~70 г)', '1 muffin (~70 γρ.)'),
    title: L('Apple oatmeal muffins', 'Яблочные овсяные маффины', 'Muffins μήλου με βρώμη'),
    summary: L('Soft Lenten muffins with grated apple, oats, and a little oil.', 'Мягкие постные маффины с яблоком, овсянкой и маслом.', 'Απαλά νηστίσιμα muffins με μήλο, βρώμη και λίγο λάδι.'),
    ingredients: lines(
      [
        '1½ cups (135 g) rolled oats',
        '1 cup (120 g) flour',
        '2 tsp baking powder',
        '1 tsp cinnamon',
        '⅓ cup (80 ml) olive oil',
        '⅓ cup (70 g) sugar or maple syrup',
        '1 cup (240 ml) water or plant milk',
        '1 large apple, grated',
        'Pinch of salt',
      ],
      [
        '1½ стакана (135 г) овсянки',
        '1 стакан (120 г) муки',
        '2 ч.л. разрыхлителя',
        '1 ч.л. корицы',
        '⅓ стакана (80 мл) масла',
        '⅓ стакана (70 г) сахара или сиропа',
        '1 стакан (240 мл) воды/молока',
        '1 яблоко, тёртое',
        'Щепотка соли',
      ],
      [
        '1½ φλ. (135 γρ.) βρώμη',
        '1 φλ. (120 γρ.) αλεύρι',
        '2 κ.γ. baking powder',
        '1 κ.γ. κανέλα',
        '⅓ φλ. (80 ml) ελαιόλαδο',
        '⅓ φλ. (70 γρ.) ζάχαρη ή σιρόπι',
        '1 φλ. (240 ml) νερό/γάλα',
        '1 μήλο τριμμένο',
        'Πιτσίλισμα αλάτι',
      ],
    ),
    steps: lines(
      [
        'Heat oven to 180°C. Line a 12-cup muffin tin.',
        'Mix dry ingredients. Whisk oil, sweetener, and liquid; fold into dry with apple.',
        'Fill cups ¾ full. Bake 22–25 minutes until a toothpick is clean.',
        'Cool 10 minutes in the tin, then on a rack.',
      ],
      [
        'Духовка 180°C. Форма на 12.',
        'Смешайте сухое. Жидкое + яблоко вмешите.',
        '¾ формы. 22–25 мин.',
        'Остудите.',
      ],
      [
        'Φούρνος 180°C. Φόρμα 12.',
        'Ανακατέψτε στερεά. Υγρά + μήλο.',
        'Γεμίστε στα ¾. 22–25 λεπτά.',
        'Κρυώστε.',
      ],
    ),
    tips: lines(
      [
        'Use a tart apple for better flavour.',
        'Freeze extras up to a month.',
      ],
      [
        'Кисловатое яблоко вкуснее.',
        'Заморозьте лишние до месяца.',
      ],
      [
        'Ξινό μήλο = καλύτερη γεύση.',
        'Κατάψυξη έως ένα μήνα.',
      ],
    ),
  }),
  R({
    id: 'greek-potato-salad',
    level: 'wine_oil',
    category: 'salad',
    difficulty: 'easy',
    prepMinutes: 15,
    cookMinutes: 25,
    servings: 4,
    servingSize: L('1 bowl (~220 g)', '1 миска (~220 г)', '1 μπολ (~220 γρ.)'),
    title: L('Greek potato salad', 'Греческий картофельный салат', 'Πατατοσαλάτα με μυρωδικά'),
    summary: L('Warm boiled potatoes with herbs, onion, lemon, and olive oil — no mayo.', 'Тёплый картофель с зеленью, луком, лимоном и маслом — без майонеза.', 'Ζεστές πατάτες με μυρωδικά, κρεμμύδι, λεμόνι και λάδι — χωρίς μαγιονέζα.'),
    ingredients: lines(
      [
        '800 g potatoes, boiled and cubed',
        '½ red onion, thinly sliced',
        '⅓ cup chopped parsley',
        '2 tbsp chopped dill',
        '⅓ cup (80 ml) olive oil',
        'Juice of 1 lemon',
        '1 tsp dried oregano',
        'Salt and pepper',
      ],
      [
        '800 г картофеля кубиками',
        '½ красного лука',
        '⅓ стакана петрушки',
        '2 ст.л. укропа',
        '⅓ стакана (80 мл) масла',
        'Сок 1 лимона',
        '1 ч.л. орегано',
        'Соль и перец',
      ],
      [
        '800 γρ. πατάτες σε κύβους',
        '½ κόκκινο κρεμμύδι',
        '⅓ φλ. μαϊντανό',
        '2 κ.σ. άνηθο',
        '⅓ φλ. (80 ml) ελαιόλαδο',
        'Χυμός 1 λεμονιού',
        '1 κ.γ. ρίγανη',
        'Αλάτι και πιπέρι',
      ],
    ),
    steps: lines(
      [
        'Boil potatoes in salted water until just tender; drain.',
        'While warm, toss with onion, herbs, oil, lemon, oregano, salt, and pepper.',
        'Taste and add more lemon if needed. Serve warm or room temperature.',
      ],
      [
        'Варите картофель до мягкости; откиньте.',
        'Тёплым смешайте с луком, зеленью, маслом, лимоном, орегано, солью.',
        'Попробуйте; подавайте тёплым или комнатной температуры.',
      ],
      [
        'Βράστε πατάτες· στραγγίξτε.',
        'Χλιαρές ανακατέψτε με κρεμμύδι, μυρωδικά, λάδι, λεμόνι, ρίγανη, αλάτι.',
        'Δοκιμάστε· σερβίρετε χλιαρό ή σε θερμοκρασία δωματίου.',
      ],
    ),
    tips: lines(
      [
        'Waxy potatoes hold their shape better.',
        'Add chopped olives on oil days if you like.',
      ],
      [
        'Восковой картофель лучше держит форму.',
        'Можно добавить оливки.',
      ],
      [
        'Οι κηρώδεις πατάτες κρατούν καλύτερα.',
        'Προαιρετικά ελιές.',
      ],
    ),
  }),
  R({
    id: 'red-cabbage-apple',
    level: 'strict',
    category: 'salad',
    difficulty: 'easy',
    prepMinutes: 15,
    cookMinutes: 0,
    servings: 4,
    servingSize: L('1 bowl (~180 g)', '1 миска (~180 г)', '1 μπολ (~180 γρ.)'),
    title: L('Red cabbage & apple salad', 'Салат из красной капусты с яблоком', 'Κόκκινο λάχανο με μήλο'),
    summary: L('Crunchy red cabbage with apple and vinegar — bright strict-fast salad.', 'Хрустящая красная капуста с яблоком и уксусом — яркий строгий салат.', 'Τραγανό κόκκινο λάχανο με μήλο και ξίδι — δροσερή αυστηρή σαλάτα.'),
    ingredients: lines(
      [
        '½ small red cabbage, shredded',
        '1 crisp apple, julienned',
        '2 tbsp red wine vinegar or lemon juice',
        '1 tsp maple syrup (optional)',
        'Salt and pepper',
        'Optional: 2 tbsp raisins',
      ],
      [
        '½ небольшого кочана красной капусты',
        '1 яблоко соломкой',
        '2 ст.л. уксуса или лимона',
        '1 ч.л. сиропа (по желанию)',
        'Соль и перец',
        'По желанию: 2 ст.л. изюма',
      ],
      [
        '½ μικρό κόκκινο λάχανο',
        '1 μήλο σε λεπτοκομμένα',
        '2 κ.σ. ξίδι ή λεμόνι',
        '1 κ.γ. σιρόπι (προαιρετικά)',
        'Αλάτι και πιπέρι',
        'Προαιρετικά: 2 κ.σ. σταφίδες',
      ],
    ),
    steps: lines(
      [
        'Toss cabbage and apple with vinegar, syrup if using, salt, and pepper.',
        'Massage lightly 1 minute so cabbage softens.',
        'Rest 10 minutes. Fold in raisins if using. Serve.',
      ],
      [
        'Смешайте капусту и яблоко с уксусом, сиропом, солью.',
        'Помните 1 мин.',
        '10 мин отдохнуть. Добавьте изюм.',
      ],
      [
        'Ανακατέψτε λάχανο και μήλο με ξίδι, σιρόπι, αλάτι.',
        'Μαλάξτε 1 λεπτό.',
        'Ξεκούραση 10 λεπτά. Σταφίδες αν θέλετε.',
      ],
    ),
    tips: lines(
      [
        'On oil days, finish with 1–2 tbsp olive oil.',
        'Keeps 2 days in the fridge.',
      ],
      [
        'В дни с маслом — 1–2 ст.л. оливкового.',
        'Хранится 2 дня.',
      ],
      [
        'Σε μέρες με λάδι, 1–2 κ.σ. ελαιόλαδο.',
        'Κρατάει 2 μέρες.',
      ],
    ),
  }),
  R({
    id: 'spinach-strawberry-salad',
    level: 'wine_oil',
    category: 'salad',
    difficulty: 'easy',
    prepMinutes: 12,
    cookMinutes: 0,
    servings: 3,
    servingSize: L('1 bowl (~200 g)', '1 миска (~200 г)', '1 μπολ (~200 γρ.)'),
    title: L('Spinach & strawberry salad', 'Салат шпинат с клубникой', 'Σπανάκι με φράουλες'),
    summary: L('Baby greens with strawberries, balsamic, and olive oil — light oil-day salad.', 'Зелень с клубникой, бальзамиком и маслом — лёгкий салат с маслом.', 'Χόρτα με φράουλες, βαλσάμικο και λάδι — ελαφριά σαλάτα.'),
    ingredients: lines(
      [
        '150 g baby spinach or arugula mix',
        '200 g strawberries, sliced',
        '2 tbsp olive oil',
        '1 tbsp balsamic vinegar',
        'Pinch of salt and pepper',
        'Optional: 2 tbsp toasted seeds',
      ],
      [
        '150 г шпината или рукколы',
        '200 г клубники',
        '2 ст.л. масла',
        '1 ст.л. бальзамика',
        'Соль и перец',
        'По желанию: 2 ст.л. семян',
      ],
      [
        '150 γρ. σπανάκι ή ρόκα',
        '200 γρ. φράουλες',
        '2 κ.σ. ελαιόλαδο',
        '1 κ.σ. βαλσάμικο',
        'Αλάτι και πιπέρι',
        'Προαιρετικά: 2 κ.σ. σπόρους',
      ],
    ),
    steps: lines(
      [
        'Whisk oil, balsamic, salt, and pepper.',
        'Toss greens and strawberries with dressing just before serving.',
        'Scatter seeds if using.',
      ],
      [
        'Взбейте масло, бальзамик, соль.',
        'Смешайте зелень и клубнику перед подачей.',
        'Посыпьте семенами.',
      ],
      [
        'Χτυπήστε λάδι, βαλσάμικο, αλάτι.',
        'Ανακατέψτε χόρτα και φράουλες πριν σερβίρετε.',
        'Σπόροι από πάνω.',
      ],
    ),
    tips: lines(
      [
        'Dress at the last minute so leaves stay crisp.',
        'Swap balsamic for lemon if preferred.',
      ],
      [
        'Заправляйте в последний момент.',
        'Вместо бальзамика — лимон.',
      ],
      [
        'Ντύστε την τελευταία στιγμή.',
        'Λεμόνι αντί βαλσάμικο αν θέλετε.',
      ],
    ),
  }),
  R({
    id: 'maroulosalata',
    level: 'wine_oil',
    category: 'salad',
    difficulty: 'easy',
    prepMinutes: 15,
    cookMinutes: 0,
    servings: 4,
    servingSize: L('1 bowl (~160 g)', '1 миска (~160 г)', '1 μπολ (~160 γρ.)'),
    title: L('Maroulosalata', 'Марулосалата', 'Μαρουλοσαλάτα'),
    summary: L('Finely shredded Greek lettuce salad with dill, spring onion, lemon, and oil.', 'Тонко нарезанный греческий салат с укропом, зелёным луком, лимоном и маслом.', 'Λεπτοκομμένο μαρούλι με άνηθο, φρέσκο κρεμμύδι, λεμόνι και λάδι.'),
    ingredients: lines(
      [
        '1 large romaine or soft lettuce, finely shredded',
        '4 spring onions, sliced',
        '⅓ cup chopped dill',
        '⅓ cup (80 ml) olive oil',
        'Juice of 1–1½ lemons',
        'Salt',
      ],
      [
        '1 кочан салата, тонко',
        '4 зелёных лука',
        '⅓ стакана укропа',
        '⅓ стакана (80 мл) масла',
        'Сок 1–1½ лимонов',
        'Соль',
      ],
      [
        '1 μεγάλο μαρούλι, ψιλοκομμένο',
        '4 φρέσκα κρεμμύδια',
        '⅓ φλ. άνηθο',
        '⅓ φλ. (80 ml) ελαιόλαδο',
        'Χυμός 1–1½ λεμονιών',
        'Αλάτι',
      ],
    ),
    steps: lines(
      [
        'Combine lettuce, spring onion, and dill in a bowl.',
        'Dress with oil, lemon, and salt. Toss well.',
        'Serve immediately while crisp.',
      ],
      [
        'Смешайте салат, лук, укроп.',
        'Заправьте маслом, лимоном, солью.',
        'Сразу к столу.',
      ],
      [
        'Ανακατέψτε μαρούλι, κρεμμύδι, άνηθο.',
        'Λάδι, λεμόνι, αλάτι.',
        'Αμέσως στο τραπέζι.',
      ],
    ),
    tips: lines(
      [
        'The finer the shred, the more classic the texture.',
        'Add thin cucumber slices in summer.',
      ],
      [
        'Чем тоньше нарезка — тем традиционнее.',
        'Летом — огурец.',
      ],
      [
        'Όσο πιο ψιλό, τόσο πιο κλασικό.',
        'Το καλοκαίρι λίγο αγγούρι.',
      ],
    ),
  }),
  R({
    id: 'quinoa-chickpea-salad',
    level: 'wine_oil',
    category: 'salad',
    difficulty: 'easy',
    prepMinutes: 15,
    cookMinutes: 20,
    servings: 4,
    servingSize: L('1 bowl (~250 g)', '1 миска (~250 г)', '1 μπολ (~250 γρ.)'),
    title: L('Quinoa chickpea salad', 'Салат киноа с нутом', 'Σαλάτα κινόα με ρεβίθια'),
    summary: L('Protein-rich jar-style salad with quinoa, chickpeas, veg, and lemon oil.', 'Сытный салат с киноа, нутом, овощами и лимонной заправкой.', 'Χορταστική σαλάτα με κινόα, ρεβίθια, λαχανικά και λεμονάτη σάλτσα.'),
    ingredients: lines(
      [
        '1 cup (170 g) quinoa, cooked and cooled',
        '1 can (400 g) chickpeas, rinsed',
        '1 cucumber, diced',
        '1 cup cherry tomatoes, halved',
        '½ red onion, minced',
        '¼ cup parsley',
        '3 tbsp olive oil',
        'Juice of 1 lemon',
        'Salt and pepper',
      ],
      [
        '1 стакан (170 г) киноа, варёной',
        '1 банка (400 г) нута',
        '1 огурец',
        '1 стакан черри',
        '½ красного лука',
        '¼ стакана петрушки',
        '3 ст.л. масла',
        'Сок 1 лимона',
        'Соль и перец',
      ],
      [
        '1 φλ. (170 γρ.) κινόα βρασμένη',
        '1 κονσέρβα (400 γρ.) ρεβίθια',
        '1 αγγούρι',
        '1 φλ. ντοματίνια',
        '½ κόκκινο κρεμμύδι',
        '¼ φλ. μαϊντανό',
        '3 κ.σ. ελαιόλαδο',
        'Χυμός 1 λεμονιού',
        'Αλάτι και πιπέρι',
      ],
    ),
    steps: lines(
      [
        'Combine quinoa, chickpeas, cucumber, tomatoes, onion, and parsley.',
        'Dress with oil, lemon, salt, and pepper. Toss.',
        'Chill 15 minutes or serve at once.',
      ],
      [
        'Смешайте киноа, нут, овощи, зелень.',
        'Заправьте маслом и лимоном.',
        '15 мин в холоде или сразу.',
      ],
      [
        'Ανακατέψτε κινόα, ρεβίθια, λαχανικά, μαϊντανό.',
        'Λάδι και λεμόνι.',
        '15 λεπτά στο ψυγείο ή αμέσως.',
      ],
    ),
    tips: lines(
      [
        'Layer in jars for lunch: dressing first, then grains, then greens.',
        'Works with leftover rice instead of quinoa.',
      ],
      [
        'В банку: сначала заправка, потом крупа.',
        'Вместо киноа — рис.',
      ],
      [
        'Σε βαζάκι: πρώτα σάλτσα, μετά κινόα.',
        'Ρύζι αντί κινόα.',
      ],
    ),
  }),
  R({
    id: 'squash-couscous-salad',
    level: 'wine_oil',
    category: 'salad',
    difficulty: 'easy',
    prepMinutes: 15,
    cookMinutes: 30,
    servings: 4,
    servingSize: L('1 bowl (~240 g)', '1 миска (~240 г)', '1 μπολ (~240 γρ.)'),
    title: L('Squash couscous salad', 'Салат с тыквой и кускусом', 'Σαλάτα κολοκύθας με κουσκούς'),
    summary: L('Roasted squash with pearl couscous, herbs, and a lemon-oil dressing.', 'Запечённая тыква с кускусом, зеленью и лимонной заправкой.', 'Ψητή κολοκύθα με κουσκούς, μυρωδικά και λεμονάτη σάλτσα.'),
    ingredients: lines(
      [
        '500 g butternut or kabocha, cubed',
        '1 cup (160 g) pearl couscous, cooked',
        '3 tbsp olive oil, divided',
        'Juice of 1 lemon',
        '¼ cup parsley or mint',
        'Salt and pepper',
        'Optional: 2 tbsp pomegranate seeds',
      ],
      [
        '500 г тыквы кубиками',
        '1 стакан (160 г) перлового кускуса',
        '3 ст.л. масла',
        'Сок 1 лимона',
        '¼ стакана петрушки или мяты',
        'Соль и перец',
        'По желанию: зёрна граната',
      ],
      [
        '500 γρ. κολοκύθα σε κύβους',
        '1 φλ. (160 γρ.) πέρλες κουσκούς',
        '3 κ.σ. ελαιόλαδο',
        'Χυμός 1 λεμονιού',
        '¼ φλ. μαϊντανό ή δυόσμο',
        'Αλάτι και πιπέρι',
        'Προαιρετικά: ρόδι',
      ],
    ),
    steps: lines(
      [
        'Toss squash with 1 tbsp oil, salt, and pepper. Roast at 200°C for 25–30 minutes.',
        'Combine warm squash with couscous, remaining oil, lemon, and herbs.',
        'Adjust seasoning. Top with pomegranate if using.',
      ],
      [
        'Тыкву с 1 ст.л. масла запеките при 200°C 25–30 мин.',
        'Смешайте с кускусом, маслом, лимоном, зеленью.',
        'По желанию гранат.',
      ],
      [
        'Κολοκύθα με 1 κ.σ. λάδι στους 200°C 25–30 λεπτά.',
        'Με κουσκούς, λάδι, λεμόνι, μυρωδικά.',
        'Ρόδι αν θέλετε.',
      ],
    ),
    tips: lines(
      [
        'Pearl barley works if you cannot find pearl couscous.',
        'Serve warm as a side or cold as lunch.',
      ],
      [
        'Подойдёт перловка вместо кускуса.',
        'Тёплым гарниром или холодным обедом.',
      ],
      [
        'Κριθάρι αντί κουσκούς.',
        'Ζεστό συνοδευτικό ή κρύο μεσημεριανό.',
      ],
    ),
  }),
  R({
    id: 'mung-bean-soup',
    level: 'wine_oil',
    category: 'soup',
    difficulty: 'easy',
    prepMinutes: 10,
    cookMinutes: 45,
    servings: 5,
    servingSize: L('1 bowl (~350 ml)', '1 миска (~350 мл)', '1 μπολ (~350 ml)'),
    title: L('Mung bean soup', 'Суп из маша', 'Σούπα μουνγκ (ψιλοφάσουλα)'),
    summary: L('Greek-style psilofasola — small mung beans simmered with veg and olive oil.', 'Греческий псилофасола — маш с овощами и оливковым маслом.', 'Ψιλοφάσουλα — μουνγκ με λαχανικά και ελαιόλαδο.'),
    ingredients: lines(
      [
        '1½ cups (300 g) dried mung beans, rinsed',
        '1 onion, chopped',
        '2 carrots, chopped',
        '2 celery stalks, chopped',
        '⅓ cup (80 ml) olive oil',
        '8 cups (1.9 L) water',
        'Juice of 1 lemon',
        'Salt and pepper',
        'Optional: dill to finish',
      ],
      [
        '1½ стакана (300 г) маша',
        '1 луковица',
        '2 моркови',
        '2 стебля сельдерея',
        '⅓ стакана (80 мл) масла',
        '8 стаканов (1,9 л) воды',
        'Сок 1 лимона',
        'Соль и перец',
        'По желанию: укроп',
      ],
      [
        '1½ φλ. (300 γρ.) μουνγκ',
        '1 κρεμμύδι',
        '2 καρότα',
        '2 σέλινα',
        '⅓ φλ. (80 ml) ελαιόλαδο',
        '8 φλ. (1,9 L) νερό',
        'Χυμός 1 λεμονιού',
        'Αλάτι και πιπέρι',
        'Προαιρετικά: άνηθος',
      ],
    ),
    steps: lines(
      [
        'Warm half the oil; soften onion, carrot, and celery 8 minutes.',
        'Add mung beans and water. Boil, then simmer 35–40 minutes until soft.',
        'Season; stir in lemon and remaining oil. Dill if using. Serve.',
      ],
      [
        'В половине масла обжарьте овощи 8 мин.',
        'Маш и вода; варите 35–40 мин.',
        'Соль, лимон, оставшееся масло, укроп.',
      ],
      [
        'Με το μισό λάδι μαλακώστε λαχανικά 8 λεπτά.',
        'Μουνγκ και νερό· 35–40 λεπτά.',
        'Αλάτι, λεμόνι, υπόλοιπο λάδι, άνηθος.',
      ],
    ),
    tips: lines(
      [
        'Mung beans need no overnight soak.',
        'Mash a ladle of beans against the pot for a creamier broth.',
      ],
      [
        'Маш не нужно замачивать.',
        'Разомните часть для густоты.',
      ],
      [
        'Δεν χρειάζεται μούλιασμα.',
        'Λιώστε λίγα για πιο πηχτό ζουμί.',
      ],
    ),
  }),
  R({
    id: 'black-eyed-kale-soup',
    level: 'wine_oil',
    category: 'soup',
    difficulty: 'easy',
    prepMinutes: 15,
    cookMinutes: 50,
    servings: 5,
    servingSize: L('1 bowl (~350 ml)', '1 миска (~350 мл)', '1 μπολ (~350 ml)'),
    title: L('Black-eyed pea & kale soup', 'Суп чёрный глаз с кале', 'Σούπα μαυρομάτικα με kale'),
    summary: L('Hearty bean soup with kale (or greens) and olive oil — winter Lenten bowl.', 'Сытный суп из фасоли с кале и маслом — зимняя постная миска.', 'Χορταστική σούπα οσπρίων με χόρτα και λάδι.'),
    ingredients: lines(
      [
        '1½ cups (300 g) dried black-eyed peas, soaked',
        '1 onion, chopped',
        '2 garlic cloves',
        '1 bunch kale, chopped',
        '⅓ cup (80 ml) olive oil',
        '8 cups water',
        '1 tsp oregano',
        'Salt and pepper',
        'Lemon wedges to serve',
      ],
      [
        '1½ стакана (300 г) фасоли чёрный глаз',
        '1 луковица',
        '2 зубчика чеснока',
        '1 пучок кале',
        '⅓ стакана (80 мл) масла',
        '8 стаканов воды',
        '1 ч.л. орегано',
        'Соль и перец',
        'Лимон к столу',
      ],
      [
        '1½ φλ. (300 γρ.) μαυρομάτικα',
        '1 κρεμμύδι',
        '2 σκελίδες σκόρδο',
        '1 ματσάκι kale',
        '⅓ φλ. (80 ml) ελαιόλαδο',
        '8 φλ. νερό',
        '1 κ.γ. ρίγανη',
        'Αλάτι και πιπέρι',
        'Λεμόνι',
      ],
    ),
    steps: lines(
      [
        'Boil soaked peas until tender, 30–40 minutes; drain, keep 1 cup liquid.',
        'In a pot, warm oil; cook onion and garlic 5 minutes. Add kale until wilted.',
        'Add peas, water or cooking liquid, oregano, salt, and pepper. Simmer 15 minutes.',
        'Serve with lemon.',
      ],
      [
        'Варите фасоль 30–40 мин.',
        'В масле лук и чеснок 5 мин; кале до увядания.',
        'Фасоль, вода, орегано, соль; 15 мин.',
        'С лимоном.',
      ],
      [
        'Βράστε τα φασόλια 30–40 λεπτά.',
        'Στο λάδι κρεμμύδι και σκόρδο 5 λεπτά· kale μέχρι να μαραθεί.',
        'Φασόλια, νερό, ρίγανη· 15 λεπτά.',
        'Με λεμόνι.',
      ],
    ),
    tips: lines(
      [
        'Swiss chard or spinach stand in for kale.',
        'Canned peas: simmer 20 minutes total.',
      ],
      [
        'Вместо кале — мангольд или шпинат.',
        'Консервы: всего ~20 мин.',
      ],
      [
        'Σέσκουλο ή σπανάκι αντί kale.',
        'Κονσέρβα: ~20 λεπτά συνολικά.',
      ],
    ),
  }),
  R({
    id: 'green-beans-potatoes',
    level: 'wine_oil',
    category: 'main',
    difficulty: 'easy',
    prepMinutes: 15,
    cookMinutes: 45,
    servings: 5,
    servingSize: L('1 portion (~280 g)', '1 порция (~280 г)', '1 μερίδα (~280 γρ.)'),
    title: L('Green beans with potatoes', 'Стручковая фасоль с картофелем', 'Φασολάκια λαδερά με πατάτες'),
    summary: L('Classic Greek fasolakia — green beans and potatoes in tomato and olive oil.', 'Классические фасолакия — стручки и картофель в томате с маслом.', 'Κλασικά φασολάκια — φασολάκια και πατάτες σε ντομάτα με λάδι.'),
    ingredients: lines(
      [
        '700 g green beans, trimmed',
        '3 potatoes, wedges',
        '1 onion, sliced',
        '2 garlic cloves',
        '½ cup (120 ml) olive oil',
        '1 cup tomato passata',
        '1 cup water',
        '½ cup dill or parsley',
        'Salt and pepper',
      ],
      [
        '700 г стручковой фасоли',
        '3 картофелины',
        '1 луковица',
        '2 зубчика чеснока',
        '½ стакана (120 мл) масла',
        '1 стакан томатной пассы',
        '1 стакан воды',
        '½ стакана укропа',
        'Соль и перец',
      ],
      [
        '700 γρ. φασολάκια',
        '3 πατάτες',
        '1 κρεμμύδι',
        '2 σκελίδες σκόρδο',
        '½ φλ. (120 ml) ελαιόλαδο',
        '1 φλ. passata',
        '1 φλ. νερό',
        '½ φλ. άνηθο',
        'Αλάτι και πιπέρι',
      ],
    ),
    steps: lines(
      [
        'Warm oil; soften onion and garlic 5 minutes.',
        'Add beans, potatoes, passata, water, salt, and pepper. Cover and simmer 35–40 minutes until tender.',
        'Stir in herbs. Rest 5 minutes. Serve with bread.',
      ],
      [
        'В масле лук и чеснок 5 мин.',
        'Фасоль, картофель, пасса, вода; 35–40 мин.',
        'Зелень; 5 мин отдых. С хлебом.',
      ],
      [
        'Στο λάδι κρεμμύδι και σκόρδο 5 λεπτά.',
        'Φασολάκια, πατάτες, passata, νερό· 35–40 λεπτά.',
        'Μυρωδικά· ξεκούραση 5 λεπτά.',
      ],
    ),
    tips: lines(
      [
        'Frozen green beans work — no need to thaw fully.',
        'Sauce should be juicy, not dry.',
      ],
      [
        'Подойдёт замороженная фасоль.',
        'Соуса должно быть вдоволь.',
      ],
      [
        'Κατεψυγμένα φασολάκια εντάξει.',
        'Ζουμί αρκετό, όχι στεγνό.',
      ],
    ),
  }),
  R({
    id: 'herbed-orzo-chickpeas',
    level: 'wine_oil',
    category: 'main',
    difficulty: 'easy',
    prepMinutes: 10,
    cookMinutes: 25,
    servings: 4,
    servingSize: L('1 bowl (~300 g)', '1 миска (~300 г)', '1 μπολ (~300 γρ.)'),
    title: L('Herbed orzo with chickpeas', 'Орзо с нутом и зеленью', 'Κριθαράκι με ρεβίθια και μυρωδικά'),
    summary: L('One-pan orzo with chickpeas, lemon, and plenty of herbs — oil-day comfort.', 'Орзо с нутом, лимоном и зеленью — уютное блюдо с маслом.', 'Κριθαράκι με ρεβίθια, λεμόνι και μυρωδικά — άνετο πιάτο με λάδι.'),
    ingredients: lines(
      [
        '1½ cups (300 g) orzo',
        '1 can (400 g) chickpeas, rinsed',
        '1 onion, chopped',
        '⅓ cup (80 ml) olive oil',
        '4 cups vegetable broth or water',
        'Zest and juice of 1 lemon',
        '½ cup mixed herbs (parsley, dill, mint)',
        'Salt and pepper',
      ],
      [
        '1½ стакана (300 г) орзо',
        '1 банка нута',
        '1 луковица',
        '⅓ стакана (80 мл) масла',
        '4 стакана бульона или воды',
        'Цедра и сок 1 лимона',
        '½ стакана зелени',
        'Соль и перец',
      ],
      [
        '1½ φλ. (300 γρ.) κριθαράκι',
        '1 κονσέρβα ρεβίθια',
        '1 κρεμμύδι',
        '⅓ φλ. (80 ml) ελαιόλαδο',
        '4 φλ. ζωμό ή νερό',
        'Ξύσμα και χυμός 1 λεμονιού',
        '½ φλ. μυρωδικά',
        'Αλάτι και πιπέρι',
      ],
    ),
    steps: lines(
      [
        'Warm oil; soften onion 4 minutes. Toast orzo 1 minute.',
        'Add broth, chickpeas, salt, and pepper. Simmer, stirring, 12–15 minutes until tender.',
        'Off heat, fold in lemon zest, juice, and herbs. Rest 2 minutes.',
      ],
      [
        'В масле лук 4 мин; орзо 1 мин.',
        'Бульон, нут, соль; 12–15 мин.',
        'Лимон и зелень; 2 мин.',
      ],
      [
        'Στο λάδι κρεμμύδι 4 λεπτά· κριθαράκι 1 λεπτό.',
        'Ζωμός, ρεβίθια· 12–15 λεπτά.',
        'Λεμόνι και μυρωδικά· 2 λεπτά.',
      ],
    ),
    tips: lines(
      [
        'Add a splash of water if it thickens before the orzo is done.',
        'Leftovers make a good cold salad next day.',
      ],
      [
        'Долейте воды, если густеет рано.',
        'Назавтра — холодный салат.',
      ],
      [
        'Λίγο νερό αν δέσει νωρίς.',
        'Την άλλη μέρα κρύα σαλάτα.',
      ],
    ),
  }),
  R({
    id: 'roasted-cauliflower',
    level: 'wine_oil',
    category: 'main',
    difficulty: 'easy',
    prepMinutes: 15,
    cookMinutes: 40,
    servings: 4,
    servingSize: L('1 portion (~280 g)', '1 порция (~280 г)', '1 μερίδα (~280 γρ.)'),
    title: L('Roasted cauliflower & potatoes', 'Цветная капуста с картофелем', 'Κουνουπίδι φούρνου με πατάτες'),
    summary: L('Tray-roasted cauliflower and potatoes with oregano and olive oil.', 'Запечённые цветная капуста и картофель с орегано и маслом.', 'Κουνουπίδι και πατάτες στο φούρνο με ρίγανη και λάδι.'),
    ingredients: lines(
      [
        '1 large cauliflower, florets',
        '4 potatoes, wedges',
        '⅓ cup (80 ml) olive oil',
        '1 tsp dried oregano',
        '2 garlic cloves, minced',
        'Juice of ½ lemon',
        'Salt and pepper',
        'Optional: paprika',
      ],
      [
        '1 цветная капуста',
        '4 картофелины',
        '⅓ стакана (80 мл) масла',
        '1 ч.л. орегано',
        '2 зубчика чеснока',
        'Сок ½ лимона',
        'Соль и перец',
        'По желанию: паприка',
      ],
      [
        '1 κουνουπίδι',
        '4 πατάτες',
        '⅓ φλ. (80 ml) ελαιόλαδο',
        '1 κ.γ. ρίγανη',
        '2 σκελίδες σκόρδο',
        'Χυμός ½ λεμονιού',
        'Αλάτι και πιπέρι',
        'Προαιρετικά: πάπρικα',
      ],
    ),
    steps: lines(
      [
        'Heat oven to 200°C. Toss everything on a sheet pan.',
        'Roast 35–40 minutes, turning once, until edges brown.',
        'Finish with extra lemon. Serve hot.',
      ],
      [
        'Духовка 200°C. Всё на противень.',
        '35–40 мин, один раз переверните.',
        'Ещё лимон; горячим.',
      ],
      [
        'Φούρνος 200°C. Όλα στο ταψί.',
        '35–40 λεπτά, γυρίστε μία φορά.',
        'Λίγο λεμόνι· ζεστό.',
      ],
    ),
    tips: lines(
      [
        'Crowding the pan steams — use two pans if needed.',
        'Add chickpeas for the last 15 minutes for protein.',
      ],
      [
        'Не перегружайте противень.',
        'Нут в последние 15 мин.',
      ],
      [
        'Μην γεμίζετε υπερβολικά το ταψί.',
        'Ρεβίθια τα τελευταία 15 λεπτά.',
      ],
    ),
  }),
  R({
    id: 'beans-and-rice',
    level: 'wine_oil',
    category: 'main',
    difficulty: 'easy',
    prepMinutes: 10,
    cookMinutes: 40,
    servings: 4,
    servingSize: L('1 bowl (~320 g)', '1 миска (~320 г)', '1 μπολ (~320 γρ.)'),
    title: L('Red beans and rice', 'Красная фасоль с рисом', 'Κόκκινα φασόλια με ρύζι'),
    summary: L('Tomato-simmered beans over rice — simple Lenten plate for oil days.', 'Фасоль в томате с рисом — простое постное блюдо с маслом.', 'Φασόλια σε ντομάτα με ρύζι — απλό νηστίσιμο με λάδι.'),
    ingredients: lines(
      [
        '2 cups cooked red or kidney beans (or 1 large can)',
        '1 cup rice, cooked separately',
        '1 onion, chopped',
        '2 garlic cloves',
        '⅓ cup (80 ml) olive oil',
        '1 cup passata',
        '1 tsp cumin or oregano',
        'Salt and pepper',
        'Parsley to finish',
      ],
      [
        '2 стакана варёной красной фасоли',
        '1 стакан риса',
        '1 луковица',
        '2 зубчика чеснока',
        '⅓ стакана (80 мл) масла',
        '1 стакан пассы',
        '1 ч.л. тмина или орегано',
        'Соль и перец',
        'Петрушка',
      ],
      [
        '2 φλ. βραστά κόκκινα φασόλια',
        '1 φλ. ρύζι',
        '1 κρεμμύδι',
        '2 σκελίδες σκόρδο',
        '⅓ φλ. (80 ml) ελαιόλαδο',
        '1 φλ. passata',
        '1 κ.γ. κύμινο ή ρίγανη',
        'Αλάτι και πιπέρι',
        'Μαϊντανός',
      ],
    ),
    steps: lines(
      [
        'Warm oil; cook onion and garlic 6 minutes.',
        'Add passata, spices, beans, and a splash of water. Simmer 15–20 minutes.',
        'Serve over rice with parsley.',
      ],
      [
        'В масле лук и чеснок 6 мин.',
        'Пасса, специи, фасоль; 15–20 мин.',
        'На рис с петрушкой.',
      ],
      [
        'Στο λάδι κρεμμύδι και σκόρδο 6 λεπτά.',
        'Passata, μπαχαρικά, φασόλια· 15–20 λεπτά.',
        'Πάνω σε ρύζι με μαϊντανό.',
      ],
    ),
    tips: lines(
      [
        'Brown rice needs longer — start it first.',
        'A pinch of smoked paprika deepens the flavour.',
      ],
      [
        'Коричневый рис варите заранее.',
        'Щепотка копчёной паприки.',
      ],
      [
        'Καστανό ρύζι πρώτα.',
        'Λίγη καπνιστή πάπρικα.',
      ],
    ),
  }),
  R({
    id: 'eggplant-potato-bake',
    level: 'wine_oil',
    category: 'main',
    difficulty: 'medium',
    prepMinutes: 25,
    cookMinutes: 50,
    servings: 5,
    servingSize: L('1 portion (~300 g)', '1 порция (~300 г)', '1 μερίδα (~300 γρ.)'),
    title: L('Eggplant, zucchini & potato bake', 'Запеканка баклажан–кабачок–картофель', 'Μελιτζάνα, κολοκυθάκι και πατάτα στο φούρνο'),
    summary: L('Layered summer vegetables baked in tomato and olive oil.', 'Слои летних овощей в томате и масле.', 'Στρώσεις καλοκαιρινών λαχανικών σε ντομάτα και λάδι.'),
    ingredients: lines(
      [
        '2 eggplants, sliced',
        '2 zucchini, sliced',
        '3 potatoes, sliced',
        '1 onion, sliced',
        '½ cup (120 ml) olive oil',
        '1½ cups passata',
        '2 garlic cloves',
        '1 tsp oregano',
        'Salt and pepper',
        'Basil or parsley',
      ],
      [
        '2 баклажана',
        '2 кабачка',
        '3 картофелины',
        '1 луковица',
        '½ стакана (120 мл) масла',
        '1½ стакана пассы',
        '2 зубчика чеснока',
        '1 ч.л. орегано',
        'Соль и перец',
        'Базилик',
      ],
      [
        '2 μελιτζάνες',
        '2 κολοκυθάκια',
        '3 πατάτες',
        '1 κρεμμύδι',
        '½ φλ. (120 ml) ελαιόλαδο',
        '1½ φλ. passata',
        '2 σκελίδες σκόρδο',
        '1 κ.γ. ρίγανη',
        'Αλάτι και πιπέρι',
        'Βασιλικός',
      ],
    ),
    steps: lines(
      [
        'Heat oven to 190°C. Salt eggplant 15 minutes; pat dry.',
        'Layer vegetables in a baking dish with garlic, oregano, salt, and pepper. Pour passata and oil over.',
        'Cover and bake 35 minutes; uncover 15 minutes more until tender and browned.',
        'Rest 10 minutes. Scatter herbs.',
      ],
      [
        'Духовка 190°C. Баклажаны посолите 15 мин.',
        'Слоями овощи; пасса и масло.',
        'Под крышкой 35 мин; без 15 мин.',
        '10 мин отдых; зелень.',
      ],
      [
        'Φούρνος 190°C. Αλάτι στις μελιτζάνες 15 λεπτά.',
        'Στρώσεις· passata και λάδι.',
        'Σκεπαστά 35 λεπτά· ακάλυπτα 15.',
        'Ξεκούραση 10 λεπτά· μυρωδικά.',
      ],
    ),
    tips: lines(
      [
        'Similar-thickness slices cook evenly.',
        'Great next day, reheated.',
      ],
      [
        'Одинаковая толщина — равномернее.',
        'Назавтра ещё лучше.',
      ],
      [
        'Ίδιο πάχος φέτες.',
        'Καλύτερο την επόμενη μέρα.',
      ],
    ),
  }),
  R({
    id: 'stuffed-eggplant',
    level: 'wine_oil',
    category: 'main',
    difficulty: 'medium',
    prepMinutes: 25,
    cookMinutes: 55,
    servings: 4,
    servingSize: L('1 half (~280 g)', '1 половинка (~280 г)', '1 μισό (~280 γρ.)'),
    title: L('Stuffed eggplant', 'Фаршированные баклажаны', 'Μελιτζάνες γεμιστές (παπουτσάκια)'),
    summary: L('Roasted eggplant boats filled with tomato-herb rice — Lenten papoutsakia.', 'Лодочки из баклажана с рисом в томате — постные папуцакия.', 'Βαρκούλες μελιτζάνας με ρύζι ντομάτας — νηστίσιμα παπουτσάκια.'),
    ingredients: lines(
      [
        '2 large eggplants, halved lengthwise',
        '1 cup rice',
        '1 onion, chopped',
        '2 garlic cloves',
        '⅓ cup (80 ml) olive oil',
        '1 cup passata',
        '1½ cups water',
        '½ cup parsley',
        'Salt and pepper',
      ],
      [
        '2 крупных баклажана половинками',
        '1 стакан риса',
        '1 луковица',
        '2 зубчика чеснока',
        '⅓ стакана (80 мл) масла',
        '1 стакан пассы',
        '1½ стакана воды',
        '½ стакана петрушки',
        'Соль и перец',
      ],
      [
        '2 μεγάλες μελιτζάνες στη μέση',
        '1 φλ. ρύζι',
        '1 κρεμμύδι',
        '2 σκελίδες σκόρδο',
        '⅓ φλ. (80 ml) ελαιόλαδο',
        '1 φλ. passata',
        '1½ φλ. νερό',
        '½ φλ. μαϊντανό',
        'Αλάτι και πιπέρι',
      ],
    ),
    steps: lines(
      [
        'Score eggplant flesh, brush with oil, roast at 200°C for 25 minutes until soft. Scoop a little flesh.',
        'Cook onion and garlic in oil; add rice, passata, water, scooped flesh, herbs, salt. Simmer 10 minutes (rice half-done).',
        'Fill boats; add a splash of water to the pan. Cover and bake 25–30 minutes.',
        'Rest 5 minutes before serving.',
      ],
      [
        'Надрежьте, смажьте, запеките 25 мин при 200°C. Выньте немного мякоти.',
        'Лук, чеснок; рис, пасса, вода, мякоть; 10 мин.',
        'Начините; под крышкой 25–30 мин.',
        '5 мин отдых.',
      ],
      [
        'Χαράξτε, λαδώστε, ψήστε 25 λεπτά στους 200°C. Βγάλτε λίγη σάρκα.',
        'Κρεμμύδι, σκόρδο· ρύζι, passata, νερό· 10 λεπτά.',
        'Γεμίστε· σκεπαστά 25–30 λεπτά.',
        'Ξεκούραση 5 λεπτά.',
      ],
    ),
    tips: lines(
      [
        'Choose firm, glossy eggplants.',
        'Serve with a lemon wedge.',
      ],
      [
        'Берите упругие блестящие баклажаны.',
        'С лимоном.',
      ],
      [
        'Σφιχτές γυαλιστερές μελιτζάνες.',
        'Με λεμόνι.',
      ],
    ),
  }),
  R({
    id: 'youvetsi-chickpeas',
    level: 'wine_oil',
    category: 'main',
    difficulty: 'easy',
    prepMinutes: 10,
    cookMinutes: 40,
    servings: 5,
    servingSize: L('1 bowl (~320 g)', '1 миска (~320 г)', '1 μπολ (~320 γρ.)'),
    title: L('Youvetsi with chickpeas', 'Гиувеци с нутом', 'Γιουβέτσι με ρεβίθια'),
    summary: L('Baked orzo (kritharaki) in tomato with chickpeas — Sunday Lenten youvetsi.', 'Запечённое орзо в томате с нутом — воскресное постное гиувеци.', 'Κριθαράκι στο φούρνο με ντομάτα και ρεβίθια — κυριακάτικο γιουβέτσι.'),
    ingredients: lines(
      [
        '2 cups (400 g) orzo / kritharaki',
        '2 cups cooked chickpeas',
        '1 onion, chopped',
        '⅓ cup (80 ml) olive oil',
        '2 cups passata',
        '4 cups hot water or broth',
        '1 cinnamon stick (optional)',
        'Salt and pepper',
        'Parsley',
      ],
      [
        '2 стакана (400 г) орзо',
        '2 стакана нута',
        '1 луковица',
        '⅓ стакана (80 мл) масла',
        '2 стакана пассы',
        '4 стакана горячей воды',
        '1 палочка корицы (по желанию)',
        'Соль и перец',
        'Петрушка',
      ],
      [
        '2 φλ. (400 γρ.) κριθαράκι',
        '2 φλ. ρεβίθια',
        '1 κρεμμύδι',
        '⅓ φλ. (80 ml) ελαιόλαδο',
        '2 φλ. passata',
        '4 φλ. καυτό νερό',
        '1 ξύλο κανέλας (προαιρετικά)',
        'Αλάτι και πιπέρι',
        'Μαϊντανός',
      ],
    ),
    steps: lines(
      [
        'Heat oven to 190°C. Soften onion in oil on the stove; add passata, water, chickpeas, cinnamon, salt, pepper. Bring to a simmer.',
        'Stir in orzo. Transfer to a baking dish.',
        'Bake 25–30 minutes until pasta is tender and liquid absorbed, stirring once.',
        'Rest 5 minutes; parsley on top.',
      ],
      [
        'Духовка 190°C. Лук в масле; пасса, вода, нут, корица.',
        'Вмешайте орзо; в форму.',
        '25–30 мин, один раз перемешайте.',
        '5 мин; петрушка.',
      ],
      [
        'Φούρνος 190°C. Κρεμμύδι στο λάδι· passata, νερό, ρεβίθια, κανέλα.',
        'Κριθαράκι· στο ταψί.',
        '25–30 λεπτά, ανακατέψτε μία φορά.',
        '5 λεπτά· μαϊντανός.',
      ],
    ),
    tips: lines(
      [
        'Add hot water if the pan looks dry before the orzo is done.',
        'Traditional with a cinnamon stick — optional but lovely.',
      ],
      [
        'Долейте горячей воды, если сухо.',
        'Корица — по желанию, но уместна.',
      ],
      [
        'Προσθέστε καυτό νερό αν στεγνώσει.',
        'Η κανέλα είναι προαιρετική αλλά ωραία.',
      ],
    ),
  }),
  R({
    id: 'sweet-potato-quesadilla',
    level: 'wine_oil',
    category: 'main',
    difficulty: 'easy',
    prepMinutes: 20,
    cookMinutes: 25,
    servings: 4,
    servingSize: L('1 quesadilla half', '½ кесадильи', '½ quesadilla'),
    title: L('Sweet potato black bean quesadillas', 'Кесадилья батат и фасоль', 'Quesadilla γλυκοπατάτας'),
    summary: L('Sheet-pan tortillas filled with mashed sweet potato and black beans.', 'Тортильи с пюре батата и чёрной фасолью на противне.', 'Πίτες με πουρέ γλυκοπατάτας και μαύρα φασόλια στο ταψί.'),
    ingredients: lines(
      [
        '2 medium sweet potatoes, roasted and mashed',
        '1 can black beans, rinsed',
        '1 tsp cumin',
        '½ tsp smoked paprika',
        '4 large tortillas',
        '2 tbsp olive oil',
        'Salt',
        'Salsa or lemon to serve',
      ],
      [
        '2 батата, запечённых в пюре',
        '1 банка чёрной фасоли',
        '1 ч.л. тмина',
        '½ ч.л. паприки',
        '4 большие тортильи',
        '2 ст.л. масла',
        'Соль',
        'Сальса или лимон',
      ],
      [
        '2 γλυκοπατάτες πουρέ',
        '1 κονσέρβα μαύρα φασόλια',
        '1 κ.γ. κύμινο',
        '½ κ.γ. πάπρικα',
        '4 μεγάλες πίτες',
        '2 κ.σ. ελαιόλαδο',
        'Αλάτι',
        'Σάλτσα ή λεμόνι',
      ],
    ),
    steps: lines(
      [
        'Mix sweet potato, beans, spices, and salt.',
        'Spread on half of each tortilla; fold. Brush lightly with oil.',
        'Bake at 200°C for 12–15 minutes, flipping once, until crisp.',
        'Cut and serve with salsa or lemon.',
      ],
      [
        'Смешайте пюре, фасоль, специи.',
        'На половину тортильи; сложите; смажьте.',
        '200°C 12–15 мин, переверните.',
        'Нарежьте; с сальсой.',
      ],
      [
        'Ανακατέψτε πουρέ, φασόλια, μπαχαρικά.',
        'Γεμίστε· διπλώστε· λαδώστε.',
        '200°C 12–15 λεπτά, γυρίστε.',
        'Κόψτε· με σάλτσα.',
      ],
    ),
    tips: lines(
      [
        'Roast sweet potatoes ahead to save time.',
        'Corn tortillas work if warmed first.',
      ],
      [
        'Запеките батат заранее.',
        'Кукурузные тортильи — сначала прогрейте.',
      ],
      [
        'Ψήστε τις γλυκοπατάτες από πριν.',
        'Καλαμποκίσια πίτα — ζεστάνετε πρώτα.',
      ],
    ),
  }),
  R({
    id: 'vegan-chili',
    level: 'wine_oil',
    category: 'main',
    difficulty: 'easy',
    prepMinutes: 15,
    cookMinutes: 35,
    servings: 6,
    servingSize: L('1 bowl (~350 g)', '1 миска (~350 г)', '1 μπολ (~350 γρ.)'),
    title: L('Vegan chili', 'Постный чили', 'Vegan chili'),
    summary: L('Tomato chili with beans and spices — hearty Lenten pot, oil optional but lovely.', 'Томатный чили с фасолью и специями — сытная постная кастрюля.', 'Chili ντομάτας με φασόλια — χορταστική νηστίσιμη κατσαρόλα.'),
    ingredients: lines(
      [
        '2 tbsp olive oil',
        '1 onion, chopped',
        '1 bell pepper, diced',
        '3 garlic cloves',
        '2 tbsp chili powder or paprika mix',
        '1 tsp cumin',
        '2 cans beans (kidney/black), rinsed',
        '1 can crushed tomatoes',
        '1 cup water',
        'Salt',
      ],
      [
        '2 ст.л. масла',
        '1 луковица',
        '1 перец',
        '3 зубчика чеснока',
        '2 ст.л. смеси чили/паприки',
        '1 ч.л. тмина',
        '2 банки фасоли',
        '1 банка томатов',
        '1 стакан воды',
        'Соль',
      ],
      [
        '2 κ.σ. ελαιόλαδο',
        '1 κρεμμύδι',
        '1 πιπεριά',
        '3 σκελίδες σκόρδο',
        '2 κ.σ. chili/πάπρικα',
        '1 κ.γ. κύμινο',
        '2 κονσέρβες φασόλια',
        '1 κονσέρβα ντομάτα',
        '1 φλ. νερό',
        'Αλάτι',
      ],
    ),
    steps: lines(
      [
        'Warm oil; cook onion and pepper 8 minutes; garlic 1 minute.',
        'Stir in spices 30 seconds. Add beans, tomatoes, water, and salt.',
        'Simmer 25 minutes, stirring. Adjust spices. Serve.',
      ],
      [
        'В масле лук и перец 8 мин; чеснок.',
        'Специи 30 сек; фасоль, томаты, вода.',
        '25 мин. Попробуйте.',
      ],
      [
        'Στο λάδι κρεμμύδι και πιπεριά 8 λεπτά· σκόρδο.',
        'Μπαχαρικά 30 δεύτερα· φασόλια, ντομάτα, νερό.',
        '25 λεπτά. Δοκιμάστε.',
      ],
    ),
    tips: lines(
      [
        'Serve over rice or with tortillas.',
        'On strict days, water-sauté the onion instead of oil.',
      ],
      [
        'С рисом или тортильями.',
        'В строгий пост — лук на воде.',
      ],
      [
        'Με ρύζι ή πίτες.',
        'Σε αυστηρή νηστεία, κρεμμύδι με νερό.',
      ],
    ),
  }),
  R({
    id: 'stuffed-calamari',
    level: 'fish',
    category: 'main',
    difficulty: 'medium',
    prepMinutes: 30,
    cookMinutes: 40,
    servings: 4,
    servingSize: L('2–3 pieces', '2–3 штуки', '2–3 κομμάτια'),
    title: L('Stuffed calamari', 'Фаршированные кальмары', 'Καλαμάρια γεμιστά'),
    summary: L('Calamari tubes filled with rice and herbs in tomato — for fish-allowed fasting days.', 'Кальмары с рисом и зеленью в томате — в дни, когда разрешена рыба.', 'Καλαμάρια με ρύζι και μυρωδικά σε ντομάτα — τις μέρες με ψάρι/θαλασσινά.'),
    ingredients: lines(
      [
        '800 g cleaned calamari tubes',
        '¾ cup rice',
        '1 onion, chopped',
        '⅓ cup olive oil',
        '1 cup passata',
        '½ cup parsley',
        'Juice of ½ lemon',
        'Salt and pepper',
        'Water as needed',
      ],
      [
        '800 г очищенных кальмаров',
        '¾ стакана риса',
        '1 луковица',
        '⅓ стакана масла',
        '1 стакан пассы',
        '½ стакана петрушки',
        'Сок ½ лимона',
        'Соль и перец',
        'Вода',
      ],
      [
        '800 γρ. καθαρισμένα καλαμάρια',
        '¾ φλ. ρύζι',
        '1 κρεμμύδι',
        '⅓ φλ. ελαιόλαδο',
        '1 φλ. passata',
        '½ φλ. μαϊντανό',
        'Χυμός ½ λεμονιού',
        'Αλάτι και πιπέρι',
        'Νερό',
      ],
    ),
    steps: lines(
      [
        'Chop tentacles if included. Soften onion in oil; add rice, half the passata, parsley, salt; cook 5 minutes.',
        'Stuff tubes loosely (rice expands); seal with toothpicks.',
        'Arrange in a pan with remaining passata, lemon, and a little water. Cover and simmer or bake at 180°C for 30–35 minutes.',
        'Rest 5 minutes; remove picks.',
      ],
      [
        'Щупальца нарежьте. Лук в масле; рис, половина пассы, зелень; 5 мин.',
        'Начините неплотно; закрепите.',
        'В соусе 30–35 мин.',
        '5 мин отдых.',
      ],
      [
        'Ψιλοκόψτε τα πλοκάμια. Κρεμμύδι στο λάδι· ρύζι, μισή passata· 5 λεπτά.',
        'Γεμίστε χαλαρά.',
        'Στη σάλτσα 30–35 λεπτά.',
        'Ξεκούραση 5 λεπτά.',
      ],
    ),
    tips: lines(
      [
        'Do not overstuff — rice swells.',
        'Only on days your parish allows shellfish/fish.',
      ],
      [
        'Не набивайте плотно.',
        'Только когда разрешены морепродукты.',
      ],
      [
        'Μην παραγεμίζετε.',
        'Μόνο τις μέρες που επιτρέπονται θαλασσινά.',
      ],
    ),
  }),
  R({
    id: 'octopus-pasta',
    level: 'fish',
    category: 'main',
    difficulty: 'medium',
    prepMinutes: 20,
    cookMinutes: 60,
    servings: 4,
    servingSize: L('1 plate (~320 g)', '1 тарелка (~320 г)', '1 πιάτο (~320 γρ.)'),
    title: L('Octopus and pasta', 'Осьминог с пастой', 'Χταπόδι με ζυμαρικά'),
    summary: L('Slow-simmered octopus in tomato tossed with pasta — fish-day main.', 'Осьминог в томате с пастой — основное блюдо в рыбный день.', 'Χταπόδι σε ντομάτα με ζυμαρικά — κυρίως πιάτο σε μέρα με ψάρι.'),
    ingredients: lines(
      [
        '1 kg octopus, cleaned',
        '400 g short pasta',
        '1 onion, chopped',
        '⅓ cup olive oil',
        '1 cup passata',
        '½ cup red wine (optional, if used in your practice)',
        'Bay leaf',
        'Salt and pepper',
        'Parsley',
      ],
      [
        '1 кг осьминога',
        '400 г короткой пасты',
        '1 луковица',
        '⅓ стакана масла',
        '1 стакан пассы',
        '½ стакана вина (по желанию)',
        'Лавровый лист',
        'Соль и перец',
        'Петрушка',
      ],
      [
        '1 κιλό χταπόδι',
        '400 γρ. κοντά ζυμαρικά',
        '1 κρεμμύδι',
        '⅓ φλ. ελαιόλαδο',
        '1 φλ. passata',
        '½ φλ. κρασί (προαιρετικά)',
        'Δάφνη',
        'Αλάτι και πιπέρι',
        'Μαϊντανός',
      ],
    ),
    steps: lines(
      [
        'Simmer octopus in a covered pot with a splash of water/wine until tender, 40–50 minutes; cut into pieces.',
        'In oil, cook onion; add passata, bay, octopus, and a little cooking liquid. Simmer 10 minutes.',
        'Boil pasta; toss with sauce. Parsley on top.',
      ],
      [
        'Тушите осьминога 40–50 мин; нарежьте.',
        'Лук, пасса, осьминог; 10 мин.',
        'Паста; смешайте; петрушка.',
      ],
      [
        'Σιγοβράστε χταπόδι 40–50 λεπτά· κόψτε.',
        'Κρεμμύδι, passata, χταπόδι· 10 λεπτά.',
        'Ζυμαρικά· ανακατέψτε· μαϊντανός.',
      ],
    ),
    tips: lines(
      [
        'Frozen octopus is fine and often already cleaned.',
        'Skip wine on stricter fish days if needed.',
      ],
      [
        'Замороженный осьминог удобен.',
        'Без вина — при более строгой практике.',
      ],
      [
        'Κατεψυγμένο χταπόδι είναι εντάξει.',
        'Χωρίς κρασί αν χρειάζεται.',
      ],
    ),
  }),
  R({
    id: 'shrimp-rice',
    level: 'fish',
    category: 'main',
    difficulty: 'easy',
    prepMinutes: 15,
    cookMinutes: 30,
    servings: 4,
    servingSize: L('1 bowl (~300 g)', '1 миска (~300 г)', '1 μπολ (~300 γρ.)'),
    title: L('Shrimp and rice', 'Креветки с рисом', 'Γαρίδες με ρύζι'),
    summary: L('One-pan tomato rice finished with shrimp — for fish-allowed days.', 'Рис в томате с креветками — когда разрешена рыба/морепродукты.', 'Ρύζι ντομάτας με γαρίδες — τις μέρες με θαλασσινά.'),
    ingredients: lines(
      [
        '400 g shrimp, peeled',
        '1½ cups rice',
        '1 onion, chopped',
        '⅓ cup olive oil',
        '1 cup passata',
        '3 cups water',
        '1 tsp oregano',
        'Salt and pepper',
        'Lemon wedges',
      ],
      [
        '400 г креветок',
        '1½ стакана риса',
        '1 луковица',
        '⅓ стакана масла',
        '1 стакан пассы',
        '3 стакана воды',
        '1 ч.л. орегано',
        'Соль и перец',
        'Лимон',
      ],
      [
        '400 γρ. γαρίδες',
        '1½ φλ. ρύζι',
        '1 κρεμμύδι',
        '⅓ φλ. ελαιόλαδο',
        '1 φλ. passata',
        '3 φλ. νερό',
        '1 κ.γ. ρίγανη',
        'Αλάτι και πιπέρι',
        'Λεμόνι',
      ],
    ),
    steps: lines(
      [
        'Warm oil; soften onion. Toast rice 1 minute.',
        'Add passata, water, oregano, salt, and pepper. Simmer covered 15 minutes.',
        'Nestle shrimp on top; cover 5–7 minutes until pink. Rest 5 minutes. Lemon at the table.',
      ],
      [
        'Лук в масле; рис 1 мин.',
        'Пасса, вода, орегано; 15 мин.',
        'Креветки сверху 5–7 мин. Лимон.',
      ],
      [
        'Κρεμμύδι στο λάδι· ρύζι 1 λεπτό.',
        'Passata, νερό, ρίγανη· 15 λεπτά.',
        'Γαρίδες από πάνω 5–7 λεπτά. Λεμόνι.',
      ],
    ),
    tips: lines(
      [
        'Do not overcook shrimp — they toughen quickly.',
        'Use vegetable broth instead of water if you have it.',
      ],
      [
        'Не передержите креветки.',
        'Бульон вместо воды — ещё лучше.',
      ],
      [
        'Μην παραψήσετε τις γαρίδες.',
        'Ζωμός αντί νερό αν έχετε.',
      ],
    ),
  }),
  R({
    id: 'calamari-rice',
    level: 'fish',
    category: 'main',
    difficulty: 'easy',
    prepMinutes: 15,
    cookMinutes: 45,
    servings: 4,
    servingSize: L('1 bowl (~300 g)', '1 миска (~300 г)', '1 μπολ (~300 γρ.)'),
    title: L('Calamari and rice', 'Кальмары с рисом', 'Καλαμάρι με ρύζι'),
    summary: L('Tomato rice simmered with calamari rings — simple fish-day pot.', 'Томатный рис с кольцами кальмара — простая рыбная кастрюля.', 'Ρύζι ντομάτας με καλαμάρι — απλή κατσαρόλα θαλασσινών.'),
    ingredients: lines(
      [
        '600 g calamari, sliced into rings',
        '1½ cups rice',
        '1 onion, chopped',
        '⅓ cup olive oil',
        '1 cup passata',
        '3½ cups water',
        'Bay leaf',
        'Salt and pepper',
        'Parsley and lemon',
      ],
      [
        '600 г кальмара кольцами',
        '1½ стакана риса',
        '1 луковица',
        '⅓ стакана масла',
        '1 стакан пассы',
        '3½ стакана воды',
        'Лавровый лист',
        'Соль и перец',
        'Петрушка и лимон',
      ],
      [
        '600 γρ. καλαμάρι σε ροδέλες',
        '1½ φλ. ρύζι',
        '1 κρεμμύδι',
        '⅓ φλ. ελαιόλαδο',
        '1 φλ. passata',
        '3½ φλ. νερό',
        'Δάφνη',
        'Αλάτι και πιπέρι',
        'Μαϊντανός και λεμόνι',
      ],
    ),
    steps: lines(
      [
        'Warm oil; cook onion and calamari 8–10 minutes.',
        'Add rice, passata, water, bay, salt, and pepper. Cover and simmer 20–25 minutes until rice is tender.',
        'Rest 5 minutes. Finish with parsley and lemon.',
      ],
      [
        'Лук и кальмар в масле 8–10 мин.',
        'Рис, пасса, вода; 20–25 мин.',
        '5 мин; петрушка и лимон.',
      ],
      [
        'Κρεμμύδι και καλαμάρι 8–10 λεπτά.',
        'Ρύζι, passata, νερό· 20–25 λεπτά.',
        '5 λεπτά· μαϊντανός και λεμόνι.',
      ],
    ),
    tips: lines(
      [
        'If calamari is thick, simmer it longer before adding rice.',
        'Frozen calamari is convenient and works well.',
      ],
      [
        'Толстые куски — дольше до риса.',
        'Замороженный кальмар удобен.',
      ],
      [
        'Αν είναι χοντρό, παραπάνω χρόνο πριν το ρύζι.',
        'Κατεψυγμένο καλαμάρι είναι πρακτικό.',
      ],
    ),
  }),
  R({
    id: 'eggplant-blt',
    level: 'wine_oil',
    category: 'main',
    difficulty: 'easy',
    prepMinutes: 15,
    cookMinutes: 20,
    servings: 2,
    servingSize: L('1 sandwich', '1 сэндвич', '1 σάντουιτς'),
    title: L('Eggplant BLT', 'Сэндвич с баклажаном', 'Σάντουιτς μελιτζάνας'),
    summary: L('Roasted eggplant strips with tomato and greens in toasted bread — oil-day lunch.', 'Запечённый баклажан с томатом и зеленью в хлебе — обед с маслом.', 'Ψητή μελιτζάνα με ντομάτα και χόρτα σε ψωμί — μεσημεριανό με λάδι.'),
    ingredients: lines(
      [
        '1 medium eggplant, sliced',
        '2 tbsp olive oil',
        '4 slices good bread',
        '1 tomato, sliced',
        'Handful lettuce or arugula',
        'Salt, pepper, oregano',
        'Optional: olive tapenade',
      ],
      [
        '1 баклажан ломтиками',
        '2 ст.л. масла',
        '4 ломтика хлеба',
        '1 помидор',
        'Горсть зелени',
        'Соль, перец, орегано',
        'По желанию: тапенад',
      ],
      [
        '1 μελιτζάνα σε φέτες',
        '2 κ.σ. ελαιόλαδο',
        '4 φέτες ψωμί',
        '1 ντομάτα',
        'Χούφτα χόρτα',
        'Αλάτι, πιπέρι, ρίγανη',
        'Προαιρετικά: ταπενάντ',
      ],
    ),
    steps: lines(
      [
        'Brush eggplant with oil, salt, pepper, oregano. Roast or pan-sear until soft and browned.',
        'Toast bread. Layer eggplant, tomato, and greens (tapenade if using).',
        'Press lightly and serve warm.',
      ],
      [
        'Смажьте баклажан; запеките или обжарьте.',
        'Поджарьте хлеб; соберите слои.',
        'Слегка прижмите; тёплым.',
      ],
      [
        'Λαδώστε τη μελιτζάνα· ψήστε.',
        'Φρυγανίστε το ψωμί· στρώστε.',
        'Πιέστε ελαφρά· ζεστό.',
      ],
    ),
    tips: lines(
      [
        'Salt eggplant first if it tends to be bitter.',
        'Whole-grain bread holds up better to the juices.',
      ],
      [
        'Посолите баклажан заранее, если горчит.',
        'Цельнозерновой хлеб лучше держит сок.',
      ],
      [
        'Αλάτι στη μελιτζάνα αν πικρίζει.',
        'Ολικής αλέσεως ψωμί κρατάει καλύτερα.',
      ],
    ),
  }),
  R({
    id: 'chickpea-wraps',
    level: 'wine_oil',
    category: 'main',
    difficulty: 'easy',
    prepMinutes: 15,
    cookMinutes: 10,
    servings: 4,
    servingSize: L('1 wrap', '1 ролл', '1 wrap'),
    title: L('Chickpea wraps', 'Роллы с нутом', 'Wrap με ρεβίθια'),
    summary: L('Mashed spiced chickpeas in flatbreads with crunchy veg — quick oil-day wrap.', 'Размятый нут со специями в лепёшке с овощами — быстрый ролл.', 'Λιωμένα ρεβίθια με μπαχαρικά σε πίτα με λαχανικά.'),
    ingredients: lines(
      [
        '2 cans chickpeas, rinsed',
        '2 tbsp olive oil',
        '1 tsp cumin',
        '1 tsp paprika',
        'Juice of ½ lemon',
        '4 tortillas or pita',
        'Shredded lettuce, cucumber, tomato',
        'Salt',
      ],
      [
        '2 банки нута',
        '2 ст.л. масла',
        '1 ч.л. тмина',
        '1 ч.л. паприки',
        'Сок ½ лимона',
        '4 тортильи или питы',
        'Салат, огурец, томат',
        'Соль',
      ],
      [
        '2 κονσέρβες ρεβίθια',
        '2 κ.σ. ελαιόλαδο',
        '1 κ.γ. κύμινο',
        '1 κ.γ. πάπρικα',
        'Χυμός ½ λεμονιού',
        '4 πίτες',
        'Μαρούλι, αγγούρι, ντομάτα',
        'Αλάτι',
      ],
    ),
    steps: lines(
      [
        'Mash chickpeas with oil, spices, lemon, and salt — leave some texture.',
        'Warm wraps. Spread filling; add raw veg.',
        'Roll tightly and slice if desired.',
      ],
      [
        'Размять нут с маслом, специями, лимоном.',
        'Начинку на тёплую лепёшку с овощами.',
        'Сверните.',
      ],
      [
        'Λιώστε ρεβίθια με λάδι, μπαχαρικά, λεμόνι.',
        'Άλειμμα σε ζεστή πίτα με λαχανικά.',
        'Τυλίξτε.',
      ],
    ),
    tips: lines(
      [
        'Add pickled onions for brightness.',
        'Leftover filling keeps 3 days.',
      ],
      [
        'Маринованный лук освежает.',
        'Начинка хранится 3 дня.',
      ],
      [
        'Τουρσί κρεμμύδι δίνει φρεσκάδα.',
        'Το γέμισμα κρατάει 3 μέρες.',
      ],
    ),
  }),
  R({
    id: 'lentil-bulgur-wraps',
    level: 'wine_oil',
    category: 'main',
    difficulty: 'medium',
    prepMinutes: 20,
    cookMinutes: 30,
    servings: 4,
    servingSize: L('1 wrap', '1 ролл', '1 wrap'),
    title: L('Lentil bulgur wraps', 'Роллы чечевица и булгур', 'Wrap φακής και πλιγουριού'),
    summary: L('Red lentils and bulgur in wraps with a tahini cabbage slaw.', 'Красная чечевица и булгур в ролле с капустой и тахини.', 'Κόκκινη φακή και πλιγούρι με λάχανο και ταχίνι.'),
    ingredients: lines(
      [
        '1 cup red lentils',
        '½ cup bulgur',
        '2 tbsp olive oil',
        '2 tbsp tahini',
        '2 cups shredded cabbage',
        'Juice of 1 lemon',
        '4 large wraps',
        'Salt, cumin, garlic',
        'Water as needed',
      ],
      [
        '1 стакан красной чечевицы',
        '½ стакана булгура',
        '2 ст.л. масла',
        '2 ст.л. тахини',
        '2 стакана капусты',
        'Сок 1 лимона',
        '4 больших ролла',
        'Соль, тмин, чеснок',
        'Вода',
      ],
      [
        '1 φλ. κόκκινη φακή',
        '½ φλ. πλιγούρι',
        '2 κ.σ. ελαιόλαδο',
        '2 κ.σ. ταχίνι',
        '2 φλ. λάχανο',
        'Χυμός 1 λεμονιού',
        '4 μεγάλα wrap',
        'Αλάτι, κύμινο, σκόρδο',
        'Νερό',
      ],
    ),
    steps: lines(
      [
        'Cook lentils and bulgur in salted water until soft; drain and season with oil, cumin, garlic, salt.',
        'Mix cabbage with tahini, lemon, and a splash of water into a slaw.',
        'Fill wraps with lentil mix and slaw; roll.',
      ],
      [
        'Сварите чечевицу и булгур; заправьте.',
        'Капуста с тахини и лимоном.',
        'Сверните роллы.',
      ],
      [
        'Βράστε φακή και πλιγούρι· καρυκεύστε.',
        'Λάχανο με ταχίνι και λεμόνι.',
        'Τυλίξτε.',
      ],
    ),
    tips: lines(
      [
        'Tahini thickens — loosen with lemon water.',
        'Make the filling ahead for easy lunches.',
      ],
      [
        'Тахини густеет — разбавьте лимонной водой.',
        'Начинку можно заранее.',
      ],
      [
        'Το ταχίνι πήζει — αραιώστε με λεμονόνερο.',
        'Το γέμισμα γίνεται από πριν.',
      ],
    ),
  }),
  R({
    id: 'dandelion-toast',
    level: 'wine_oil',
    category: 'side',
    difficulty: 'easy',
    prepMinutes: 10,
    cookMinutes: 15,
    servings: 2,
    servingSize: L('2 toasts', '2 тоста', '2 φέτες'),
    title: L('Dandelion greens on toast', 'Одуванчик на тосте', 'Ραδίκια σε ψωμί'),
    summary: L('Wilted bitter greens with lemon and oil on grilled bread — classic meze.', 'Припущенная горькая зелень с лимоном и маслом на хлебе.', 'Μαραμένα πικρά χόρτα με λεμόνι και λάδι σε ψωμί.'),
    ingredients: lines(
      [
        '300 g dandelion greens or chicory, washed',
        '3 tbsp olive oil',
        '2 garlic cloves',
        'Juice of ½ lemon',
        '4 slices sturdy bread',
        'Salt and pepper',
      ],
      [
        '300 г одуванчика или цикория',
        '3 ст.л. масла',
        '2 зубчика чеснока',
        'Сок ½ лимона',
        '4 ломтика хлеба',
        'Соль и перец',
      ],
      [
        '300 γρ. ραδίκια ή πικραλίδα',
        '3 κ.σ. ελαιόλαδο',
        '2 σκελίδες σκόρδο',
        'Χυμός ½ λεμονιού',
        '4 φέτες ψωμί',
        'Αλάτι και πιπέρι',
      ],
    ),
    steps: lines(
      [
        'Blanch greens 2–3 minutes in salted water; drain and chop.',
        'Warm oil; garlic 30 seconds; toss greens, lemon, salt, pepper.',
        'Grill or toast bread; pile greens on top.',
      ],
      [
        'Бланшируйте зелень 2–3 мин; откиньте.',
        'Масло, чеснок; зелень с лимоном.',
        'На тост.',
      ],
      [
        'Ζεματίστε χόρτα 2–3 λεπτά· στραγγίξτε.',
        'Λάδι, σκόρδο· χόρτα με λεμόνι.',
        'Πάνω στη φρυγανιά.',
      ],
    ),
    tips: lines(
      [
        'Any bitter green works — endive, escarole, wild greens.',
        'A pinch of chili flakes wakes it up.',
      ],
      [
        'Подойдёт любая горькая зелень.',
        'Щепотка чили.',
      ],
      [
        'Οποιαδήποτε πικρά χόρτα.',
        'Λίγη καυτερή πιπεριά.',
      ],
    ),
  }),
  R({
    id: 'horta',
    level: 'wine_oil',
    category: 'side',
    difficulty: 'easy',
    prepMinutes: 10,
    cookMinutes: 20,
    servings: 4,
    servingSize: L('1 plate (~200 g)', '1 тарелка (~200 г)', '1 πιάτο (~200 γρ.)'),
    title: L('Horta', 'Хорта (варёная зелень)', 'Χόρτα βραστά'),
    summary: L('Boiled wild greens dressed with olive oil and lemon — essential Greek Lenten side.', 'Варёная зелень с маслом и лимоном — обязательный греческий гарнир поста.', 'Βραστά χόρτα με λάδι και λεμόνι — βασικό νηστίσιμο συνοδευτικό.'),
    ingredients: lines(
      [
        '1 kg mixed greens (amaranth, chicory, spinach, beet greens)',
        '⅓ cup (80 ml) olive oil',
        'Juice of 1–2 lemons',
        'Salt',
      ],
      [
        '1 кг смеси зелени',
        '⅓ стакана (80 мл) масла',
        'Сок 1–2 лимонов',
        'Соль',
      ],
      [
        '1 κιλό χόρτα ανάμεικτα',
        '⅓ φλ. (80 ml) ελαιόλαδο',
        'Χυμός 1–2 λεμονιών',
        'Αλάτι',
      ],
    ),
    steps: lines(
      [
        'Wash greens thoroughly. Boil in salted water until tender, 10–20 minutes depending on type.',
        'Drain well. Dress with oil and lemon while warm.',
        'Serve warm or room temperature.',
      ],
      [
        'Промойте. Варите в солёной воде 10–20 мин.',
        'Откиньте; заправьте маслом и лимоном.',
        'Тёплым или комнатной температуры.',
      ],
      [
        'Πλύνετε καλά. Βράστε 10–20 λεπτά.',
        'Στραγγίξτε· λάδι και λεμόνι.',
        'Χλιαρό ή σε θερμοκρασία δωματίου.',
      ],
    ),
    tips: lines(
      [
        'Dress while warm so the oil soaks in.',
        'Save a little cooking water to loosen if they seem dry.',
      ],
      [
        'Заправляйте тёплыми.',
        'Чуть отвара, если сухо.',
      ],
      [
        'Ντύστε χλιαρά.',
        'Λίγο ζουμί αν στεγνώσουν.',
      ],
    ),
  }),
  R({
    id: 'oatmeal-cups',
    level: 'wine_oil',
    category: 'sweet',
    difficulty: 'easy',
    prepMinutes: 15,
    cookMinutes: 0,
    servings: 10,
    servingSize: L('1 cup (~40 g)', '1 шт. (~40 г)', '1 τεμ. (~40 γρ.)'),
    title: L('Oatmeal cups', 'Овсяные чашечки', 'Βρώμη σε φορμάκια'),
    summary: L('No-bake oat cups with nut butter and dried fruit — Lenten snack bites.', 'Овсяные чашечки без выпечки с пастой из орехов и сухофруктами.', 'Φορμάκια βρώμης χωρίς φούρνο με ταχίνι/φυστικοβούτυρο και ξερά φρούτα.'),
    ingredients: lines(
      [
        '2 cups (180 g) rolled oats',
        '½ cup tahini or almond butter',
        '⅓ cup maple syrup or honey if used',
        '⅓ cup chopped dried fruit',
        'Pinch of salt',
        'Optional: cocoa or cinnamon',
      ],
      [
        '2 стакана (180 г) овсянки',
        '½ стакана тахини или миндальной пасты',
        '⅓ стакана сиропа',
        '⅓ стакана сухофруктов',
        'Щепотка соли',
        'По желанию: какао или корица',
      ],
      [
        '2 φλ. (180 γρ.) βρώμη',
        '½ φλ. ταχίνι ή αμυγδαλοβούτυρο',
        '⅓ φλ. σιρόπι',
        '⅓ φλ. ξερά φρούτα',
        'Πιτσίλισμα αλάτι',
        'Προαιρετικά: κακάο ή κανέλα',
      ],
    ),
    steps: lines(
      [
        'Mix everything until sticky.',
        'Press into mini muffin cups or form balls.',
        'Chill 1 hour until firm. Store cold.',
      ],
      [
        'Смешайте до липкости.',
        'Утрамбуйте в формочки или шарики.',
        '1 час в холоде.',
      ],
      [
        'Ανακατέψτε μέχρι να κολλάνε.',
        'Σε φορμάκια ή μπάλες.',
        '1 ώρα στο ψυγείο.',
      ],
    ),
    tips: lines(
      [
        'If dry, add a spoon of warm water or more syrup.',
        'Keep refrigerated up to a week.',
      ],
      [
        'Если сухо — ложка воды или сиропа.',
        'В холодильнике до недели.',
      ],
      [
        'Αν στεγνό, λίγο νερό ή σιρόπι.',
        'Στο ψυγείο έως μία εβδομάδα.',
      ],
    ),
  }),
  R({
    id: 'stuffed-dates',
    level: 'strict',
    category: 'sweet',
    difficulty: 'easy',
    prepMinutes: 15,
    cookMinutes: 0,
    servings: 12,
    servingSize: L('2 dates', '2 финика', '2 χουρμάδες'),
    title: L('Stuffed dates', 'Фаршированные финики', 'Χουρμάδες γεμιστοί'),
    summary: L('Dates filled with almond butter and coconut — no-cook Lenten sweet.', 'Финики с миндальной пастой и кокосом — сладкое без готовки.', 'Χουρμάδες με αμυγδαλοβούτυρο και καρύδα — γλυκό χωρίς ψήσιμο.'),
    ingredients: lines(
      [
        '12 soft Medjool dates, pitted',
        '3 tbsp almond or peanut butter',
        '2 tbsp shredded coconut',
        'Optional: pinch of cinnamon',
      ],
      [
        '12 мягких фиников без косточек',
        '3 ст.л. миндальной/арахисовой пасты',
        '2 ст.л. кокосовой стружки',
        'По желанию: корица',
      ],
      [
        '12 μαλακοί χουρμάδες χωρίς κουκούτσι',
        '3 κ.σ. αμυγδαλοβούτυρο',
        '2 κ.σ. καρύδα',
        'Προαιρετικά: κανέλα',
      ],
    ),
    steps: lines(
      [
        'Open each date.',
        'Fill with nut butter; press coconut on top.',
        'Arrange on a plate; chill briefly if soft.',
      ],
      [
        'Раскройте финики.',
        'Начините пастой; кокос сверху.',
        'Слегка охладите.',
      ],
      [
        'Ανοίξτε τους χουρμάδες.',
        'Γεμίστε· καρύδα από πάνω.',
        'Λίγο ψυγείο αν χρειάζεται.',
      ],
    ),
    tips: lines(
      [
        'If dates are dry, soak 10 minutes in warm water.',
        'Tahini works instead of almond butter on oil days.',
      ],
      [
        'Сухие финики замочите 10 мин.',
        'Тахини вместо миндальной пасты в дни с маслом.',
      ],
      [
        'Αν είναι στεγνοί, μουλιάστε 10 λεπτά.',
        'Ταχίνι αντί αμυγδαλοβούτυρο σε μέρες με λάδι.',
      ],
    ),
  }),
  R({
    id: 'vegan-rizogalo',
    level: 'strict',
    category: 'sweet',
    difficulty: 'easy',
    prepMinutes: 5,
    cookMinutes: 35,
    servings: 4,
    servingSize: L('1 bowl (~200 g)', '1 миска (~200 г)', '1 μπολ (~200 γρ.)'),
    title: L('Vegan rizogalo', 'Постный рисовый пудинг', 'Νηστίσιμο ρυζόγαλο'),
    summary: L('Creamy rice pudding with plant milk and cinnamon — dairy-free Greek classic.', 'Нежный рисовый пудинг на растительном молоке с корицей.', 'Κρεμώδες ρυζόγαλο με φυτικό γάλα και κανέλα.'),
    ingredients: lines(
      [
        '½ cup short-grain rice',
        '4 cups (960 ml) plant milk (oat or almond)',
        '⅓ cup sugar',
        '1 strip lemon peel',
        'Cinnamon to serve',
        'Pinch of salt',
      ],
      [
        '½ стакана круглозёрного риса',
        '4 стакана (960 мл) растительного молока',
        '⅓ стакана сахара',
        'Полоска цедры лимона',
        'Корица',
        'Щепотка соли',
      ],
      [
        '½ φλ. ρύζι γλασέ',
        '4 φλ. (960 ml) φυτικό γάλα',
        '⅓ φλ. ζάχαρη',
        'Φλούδα λεμονιού',
        'Κανέλα',
        'Πιτσίλισμα αλάτι',
      ],
    ),
    steps: lines(
      [
        'Simmer rice with plant milk, sugar, lemon peel, and salt, stirring often, 30–35 minutes until creamy.',
        'Remove peel. Pour into bowls.',
        'Cool slightly; dust with cinnamon.',
      ],
      [
        'Варите рис с молоком, сахаром, цедрой 30–35 мин, часто мешая.',
        'Уберите цедру; в миски.',
        'Корица сверху.',
      ],
      [
        'Σιγοβράστε ρύζι με γάλα, ζάχαρη, φλούδα 30–35 λεπτά.',
        'Βγάλτε τη φλούδα· σε μπολ.',
        'Κανέλα από πάνω.',
      ],
    ),
    tips: lines(
      [
        'Stir often so it does not catch on the bottom.',
        'Thicker as it cools — loosen with a splash of plant milk.',
      ],
      [
        'Часто мешайте.',
        'При остывании густеет — добавьте молоко.',
      ],
      [
        'Ανακατεύετε συχνά.',
        'Όσο κρυώνει πήζει — λίγο γάλα.',
      ],
    ),
  }),
  R({
    id: 'date-cake',
    level: 'wine_oil',
    category: 'sweet',
    difficulty: 'easy',
    prepMinutes: 15,
    cookMinutes: 40,
    servings: 10,
    servingSize: L('1 slice (~80 g)', '1 кусок (~80 г)', '1 φέτα (~80 γρ.)'),
    title: L('Vegan date cake', 'Постный финиковый кекс', 'Κέικ χουρμά νηστίσιμο'),
    summary: L('Moist Lenten cake sweetened with dates and a little oil.', 'Влажный постный кекс на финиках с небольшим количеством масла.', 'Ζουμερό νηστίσιμο κέικ με χουρμάδες και λίγο λάδι.'),
    ingredients: lines(
      [
        '1½ cups (220 g) chopped dates',
        '1 cup hot water',
        '⅓ cup (80 ml) olive oil',
        '1½ cups (180 g) flour',
        '1 tsp baking soda',
        '1 tsp cinnamon',
        'Pinch of salt',
      ],
      [
        '1½ стакана (220 г) фиников',
        '1 стакан кипятка',
        '⅓ стакана (80 мл) масла',
        '1½ стакана (180 г) муки',
        '1 ч.л. соды',
        '1 ч.л. корицы',
        'Щепотка соли',
      ],
      [
        '1½ φλ. (220 γρ.) χουρμάδες',
        '1 φλ. καυτό νερό',
        '⅓ φλ. (80 ml) ελαιόλαδο',
        '1½ φλ. (180 γρ.) αλεύρι',
        '1 κ.γ. σόδα',
        '1 κ.γ. κανέλα',
        'Πιτσίλισμα αλάτι',
      ],
    ),
    steps: lines(
      [
        'Soak dates in hot water 10 minutes; mash. Stir in oil.',
        'Mix flour, soda, cinnamon, salt; fold into date mixture.',
        'Bake in a lined tin at 180°C for 35–40 minutes. Cool before slicing.',
      ],
      [
        'Замочите финики 10 мин; разомните с маслом.',
        'Мука, сода, корица; вмешайте.',
        '180°C 35–40 мин. Остудите.',
      ],
      [
        'Μουλιάστε χουρμάδες 10 λεπτά· λιώστε με λάδι.',
        'Αλεύρι, σόδα, κανέλα.',
        '180°C 35–40 λεπτά. Κρυώστε.',
      ],
    ),
    tips: lines(
      [
        'Medjool dates give the best texture.',
        'A handful of walnuts is welcome on oil days.',
      ],
      [
        'Мягкие финики — лучшая текстура.',
        'Горсть орехов уместна.',
      ],
      [
        'Οι μαλακοί χουρμάδες δίνουν καλύτερη υφή.',
        'Μια χούφτα καρύδια είναι ωραία.',
      ],
    ),
  }),
  R({
    id: 'chocolate-blueberry-cake',
    level: 'wine_oil',
    category: 'sweet',
    difficulty: 'easy',
    prepMinutes: 15,
    cookMinutes: 40,
    servings: 10,
    servingSize: L('1 slice (~90 g)', '1 кусок (~90 г)', '1 φέτα (~90 γρ.)'),
    title: L('Chocolate blueberry cake', 'Шоколадный кекс с черникой', 'Κέικ σοκολάτας με μύρτιλα'),
    summary: L('Cocoa Lenten cake folded with blueberries — oil-based, no eggs.', 'Какао-кекс с черникой — на масле, без яиц.', 'Κέικ κακάο με μύρτιλα — με λάδι, χωρίς αυγά.'),
    ingredients: lines(
      [
        '1½ cups (180 g) flour',
        '⅓ cup cocoa',
        '1 tsp baking soda',
        '¾ cup sugar',
        '⅓ cup (80 ml) oil',
        '1 cup water',
        '1 tsp vinegar',
        '1 cup blueberries',
        'Pinch of salt',
      ],
      [
        '1½ стакана (180 г) муки',
        '⅓ стакана какао',
        '1 ч.л. соды',
        '¾ стакана сахара',
        '⅓ стакана (80 мл) масла',
        '1 стакан воды',
        '1 ч.л. уксуса',
        '1 стакан черники',
        'Щепотка соли',
      ],
      [
        '1½ φλ. (180 γρ.) αλεύρι',
        '⅓ φλ. κακάο',
        '1 κ.γ. σόδα',
        '¾ φλ. ζάχαρη',
        '⅓ φλ. (80 ml) λάδι',
        '1 φλ. νερό',
        '1 κ.γ. ξίδι',
        '1 φλ. μύρτιλα',
        'Πιτσίλισμα αλάτι',
      ],
    ),
    steps: lines(
      [
        'Heat oven to 180°C. Mix dry ingredients.',
        'Whisk oil, water, vinegar; combine. Fold in berries.',
        'Bake 35–40 minutes until a toothpick is mostly clean. Cool.',
      ],
      [
        'Духовка 180°C. Смешайте сухое.',
        'Масло, вода, уксус; ягоды.',
        '35–40 мин. Остудите.',
      ],
      [
        'Φούρνος 180°C. Στερεά μαζί.',
        'Λάδι, νερό, ξίδι· μούρα.',
        '35–40 λεπτά. Κρυώστε.',
      ],
    ),
    tips: lines(
      [
        'Frozen berries work — do not thaw.',
        'Dust with cocoa instead of icing sugar.',
      ],
      [
        'Замороженные ягоды — не размораживайте.',
        'Какао вместо сахарной пудры.',
      ],
      [
        'Κατεψυγμένα μούρα — χωρίς απόψυξη.',
        'Κακάο αντί άχνη.',
      ],
    ),
  }),
  R({
    id: 'chocolate-strawberry-cookies',
    level: 'wine_oil',
    category: 'sweet',
    difficulty: 'easy',
    prepMinutes: 15,
    cookMinutes: 15,
    servings: 16,
    servingSize: L('1 cookie (~35 g)', '1 печенье (~35 г)', '1 μπισκότο (~35 γρ.)'),
    title: L('Chocolate strawberry cookies', 'Шоколадное печенье с клубникой', 'Μπισκότα σοκολάτας με φράουλα'),
    summary: L('Soft cocoa cookies with dried strawberry pieces — Lenten tray bake.', 'Мягкое какао-печенье с кусочками клубники.', 'Απαλά μπισκότα κακάο με κομμάτια φράουλας.'),
    ingredients: lines(
      [
        '1½ cups flour',
        '⅓ cup cocoa',
        '½ tsp baking soda',
        '½ cup sugar',
        '⅓ cup oil',
        '⅓ cup water',
        '½ cup chopped dried strawberries or freeze-dried',
        'Pinch of salt',
      ],
      [
        '1½ стакана муки',
        '⅓ стакана какао',
        '½ ч.л. соды',
        '½ стакана сахара',
        '⅓ стакана масла',
        '⅓ стакана воды',
        '½ стакана сушёной клубники',
        'Щепотка соли',
      ],
      [
        '1½ φλ. αλεύρι',
        '⅓ φλ. κακάο',
        '½ κ.γ. σόδα',
        '½ φλ. ζάχαρη',
        '⅓ φλ. λάδι',
        '⅓ φλ. νερό',
        '½ φλ. ξερή φράουλα',
        'Πιτσίλισμα αλάτι',
      ],
    ),
    steps: lines(
      [
        'Mix dry; stir in oil and water to a soft dough. Fold in strawberry.',
        'Scoop onto a lined sheet; flatten slightly.',
        'Bake at 180°C for 12–14 minutes. Cool on the sheet.',
      ],
      [
        'Смешайте тесто; добавьте клубнику.',
        'Выложите; слегка приплющите.',
        '180°C 12–14 мин.',
      ],
      [
        'Ζυμώστε· φράουλα.',
        'Μπάλες στο ταψί· πιέστε.',
        '180°C 12–14 λεπτά.',
      ],
    ),
    tips: lines(
      [
        'They firm up as they cool — do not overbake.',
        'Swap strawberries for raisins if needed.',
      ],
      [
        'Застывают при остывании.',
        'Вместо клубники — изюм.',
      ],
      [
        'Σφίγγουν καθώς κρυώνουν.',
        'Σταφίδες αντί φράουλα.',
      ],
    ),
  }),
  R({
    id: 'chocolate-orange-cake',
    level: 'wine_oil',
    category: 'sweet',
    difficulty: 'easy',
    prepMinutes: 15,
    cookMinutes: 40,
    servings: 10,
    servingSize: L('1 slice (~90 g)', '1 кусок (~90 г)', '1 φέτα (~90 γρ.)'),
    title: L('Chocolate orange cake', 'Шоколадный кекс с апельсином', 'Κέικ σοκολάτας με πορτοκάλι'),
    summary: L('Cocoa cake scented with orange zest and juice — Lenten favourite.', 'Какао-кекс с цедрой и соком апельсина.', 'Κέικ κακάο με ξύσμα και χυμό πορτοκαλιού.'),
    ingredients: lines(
      [
        '1½ cups flour',
        '⅓ cup cocoa',
        '1 tsp baking soda',
        '¾ cup sugar',
        '⅓ cup oil',
        '¾ cup orange juice',
        'Zest of 1 orange',
        '1 tsp vinegar',
        'Pinch of salt',
      ],
      [
        '1½ стакана муки',
        '⅓ стакана какао',
        '1 ч.л. соды',
        '¾ стакана сахара',
        '⅓ стакана масла',
        '¾ стакана апельсинового сока',
        'Цедра 1 апельсина',
        '1 ч.л. уксуса',
        'Щепотка соли',
      ],
      [
        '1½ φλ. αλεύρι',
        '⅓ φλ. κακάο',
        '1 κ.γ. σόδα',
        '¾ φλ. ζάχαρη',
        '⅓ φλ. λάδι',
        '¾ φλ. χυμό πορτοκαλιού',
        'Ξύσμα 1 πορτοκαλιού',
        '1 κ.γ. ξίδι',
        'Πιτσίλισμα αλάτι',
      ],
    ),
    steps: lines(
      [
        'Mix dry with zest. Whisk oil, juice, vinegar; combine.',
        'Bake in a lined tin at 180°C for 35–40 minutes.',
        'Cool completely before slicing.',
      ],
      [
        'Сухое с цедрой; жидкое вмешайте.',
        '180°C 35–40 мин.',
        'Полностью остудите.',
      ],
      [
        'Στερεά με ξύσμα· υγρά.',
        '180°C 35–40 λεπτά.',
        'Κρυώστε τελείως.',
      ],
    ),
    tips: lines(
      [
        'Fresh juice tastes brighter than carton.',
        'A thin orange-juice glaze is optional on oil days.',
      ],
      [
        'Свежий сок ярче.',
        'Тонкая глазурь из сока — по желанию.',
      ],
      [
        'Φρέσκος χυμός είναι καλύτερος.',
        'Λεπτό γλάσο χυμού προαιρετικά.',
      ],
    ),
  }),
  R({
    id: 'vegan-apple-cake',
    level: 'wine_oil',
    category: 'sweet',
    difficulty: 'easy',
    prepMinutes: 20,
    cookMinutes: 45,
    servings: 10,
    servingSize: L('1 slice (~90 g)', '1 кусок (~90 г)', '1 φέτα (~90 γρ.)'),
    title: L('Vegan apple cake', 'Постный яблочный пирог', 'Νηστίσιμο μηλόπιτα-κέικ'),
    summary: L('Oil-based apple cake with cinnamon — simple Lenten tray dessert.', 'Яблочный кекс на масле с корицей — простой постный десерт.', 'Κέικ μήλου με λάδι και κανέλα — απλό νηστίσιμο γλυκό.'),
    ingredients: lines(
      [
        '2 cups flour',
        '¾ cup sugar',
        '2 tsp baking powder',
        '2 tsp cinnamon',
        '⅓ cup oil',
        '1 cup water',
        '2 apples, diced',
        'Pinch of salt',
      ],
      [
        '2 стакана муки',
        '¾ стакана сахара',
        '2 ч.л. разрыхлителя',
        '2 ч.л. корицы',
        '⅓ стакана масла',
        '1 стакан воды',
        '2 яблока кубиками',
        'Щепотка соли',
      ],
      [
        '2 φλ. αλεύρι',
        '¾ φλ. ζάχαρη',
        '2 κ.γ. baking powder',
        '2 κ.γ. κανέλα',
        '⅓ φλ. λάδι',
        '1 φλ. νερό',
        '2 μήλα σε κύβους',
        'Πιτσίλισμα αλάτι',
      ],
    ),
    steps: lines(
      [
        'Heat oven to 180°C. Mix dry; stir in oil and water. Fold in apples.',
        'Spread in a lined pan. Bake 40–45 minutes.',
        'Cool before cutting.',
      ],
      [
        'Духовка 180°C. Тесто + яблоки.',
        '40–45 мин.',
        'Остудите.',
      ],
      [
        'Φούρνος 180°C. Ζύμη + μήλα.',
        '40–45 λεπτά.',
        'Κρυώστε.',
      ],
    ),
    tips: lines(
      [
        'Toss apple pieces in a little cinnamon sugar before folding in.',
        'Serve with a spoon of fruit compote.',
      ],
      [
        'Яблоки можно обвалять в корице с сахаром.',
        'С компотом.',
      ],
      [
        'Τα μήλα με λίγη κανέλα-ζάχαρη.',
        'Με κομπόστα.',
      ],
    ),
  }),
  R({
    id: 'vegan-banana-bread',
    level: 'wine_oil',
    category: 'sweet',
    difficulty: 'easy',
    prepMinutes: 15,
    cookMinutes: 50,
    servings: 10,
    servingSize: L('1 slice (~80 g)', '1 кусок (~80 г)', '1 φέτα (~80 γρ.)'),
    title: L('Vegan banana bread', 'Постный банановый хлеб', 'Νηστίσιμο κέικ μπανάνας'),
    summary: L('Classic banana loaf with oil — no eggs or dairy.', 'Классический банановый кекс на масле — без яиц и молока.', 'Κλασικό κέικ μπανάνας με λάδι — χωρίς αυγά και γάλα.'),
    ingredients: lines(
      [
        '3 ripe bananas, mashed',
        '⅓ cup (80 ml) oil',
        '½ cup sugar',
        '1½ cups flour',
        '1 tsp baking soda',
        '1 tsp cinnamon',
        'Pinch of salt',
        'Optional: ½ cup walnuts',
      ],
      [
        '3 спелых банана',
        '⅓ стакана (80 мл) масла',
        '½ стакана сахара',
        '1½ стакана муки',
        '1 ч.л. соды',
        '1 ч.л. корицы',
        'Щепотка соли',
        'По желанию: ½ стакана орехов',
      ],
      [
        '3 ώριμες μπανάνες',
        '⅓ φλ. (80 ml) λάδι',
        '½ φλ. ζάχαρη',
        '1½ φλ. αλεύρι',
        '1 κ.γ. σόδα',
        '1 κ.γ. κανέλα',
        'Πιτσίλισμα αλάτι',
        'Προαιρετικά: ½ φλ. καρύδια',
      ],
    ),
    steps: lines(
      [
        'Heat oven to 175°C. Mix bananas, oil, and sugar.',
        'Fold in dry ingredients and nuts.',
        'Bake in a loaf tin 45–55 minutes until a skewer comes out clean. Cool in the tin 10 minutes.',
      ],
      [
        'Духовка 175°C. Банан, масло, сахар.',
        'Сухое и орехи.',
        '45–55 мин. 10 мин в форме.',
      ],
      [
        'Φούρνος 175°C. Μπανάνα, λάδι, ζάχαρη.',
        'Στερεά και καρύδια.',
        '45–55 λεπτά. 10 λεπτά στη φόρμα.',
      ],
    ),
    tips: lines(
      [
        'The spottier the bananas, the sweeter the loaf.',
        'Wrap and freeze slices for quick snacks.',
      ],
      [
        'Чем спелее банан — тем слаще.',
        'Ломтики можно заморозить.',
      ],
      [
        'Όσο πιο ώριμη η μπανάνα, τόσο πιο γλυκό.',
        'Φέτες στην κατάψυξη.',
      ],
    ),
  }),
  R({
    id: 'tahini-cookies',
    level: 'wine_oil',
    category: 'sweet',
    difficulty: 'easy',
    prepMinutes: 15,
    cookMinutes: 15,
    servings: 20,
    servingSize: L('1 cookie (~30 g)', '1 печенье (~30 г)', '1 μπισκότο (~30 γρ.)'),
    title: L('Tahini cookies', 'Печенье с тахини', 'Μπισκότα ταχινιού'),
    summary: L('Crisp-edged tahini cookies — classic Greek Lenten sweet for oil days.', 'Печенье с тахини — классическое греческое постное сладкое.', 'Μπισκότα ταχινιού — κλασικό νηστίσιμο γλυκό.'),
    ingredients: lines(
      [
        '1 cup (250 g) tahini',
        '¾ cup sugar',
        '1 cup flour',
        '1 tsp baking powder',
        'Optional: sesame seeds to roll',
        'Pinch of salt',
      ],
      [
        '1 стакан (250 г) тахини',
        '¾ стакана сахара',
        '1 стакан муки',
        '1 ч.л. разрыхлителя',
        'По желанию: кунжут',
        'Щепотка соли',
      ],
      [
        '1 φλ. (250 γρ.) ταχίνι',
        '¾ φλ. ζάχαρη',
        '1 φλ. αλεύρι',
        '1 κ.γ. baking powder',
        'Προαιρετικά: σουσάμι',
        'Πιτσίλισμα αλάτι',
      ],
    ),
    steps: lines(
      [
        'Mix tahini and sugar; fold in flour, baking powder, and salt to a soft dough.',
        'Roll balls; coat in sesame if using; flatten on a sheet.',
        'Bake at 170°C for 12–15 minutes until lightly golden. Cool on the sheet.',
      ],
      [
        'Тахини с сахаром; мука и разрыхлитель.',
        'Шарики; кунжут; приплюснуть.',
        '170°C 12–15 мин.',
      ],
      [
        'Ταχίνι με ζάχαρη· αλεύρι.',
        'Μπάλες· σουσάμι· πιέστε.',
        '170°C 12–15 λεπτά.',
      ],
    ),
    tips: lines(
      [
        'Stir tahini well before measuring — oil separates.',
        'They crisp as they cool.',
      ],
      [
        'Перемешайте тахини перед отмером.',
        'Хрустят после остывания.',
      ],
      [
        'Ανακατέψτε το ταχίνι πριν μετρήσετε.',
        'Γίνονται τραγανά όταν κρυώσουν.',
      ],
    ),
  }),
];
