/**
 * OrthoDaily fasting recipe library.
 *
 * These are original, hand-curated kitchen notes for Orthodox fasting days —
 * not scraped from a commercial recipe API. Quantities are home-kitchen
 * estimates; adjust to taste and your parish’s fasting practice.
 */
import type {
  FastingRecipe,
  LocalizedLines,
  LocalizedText,
  RecipeCategory,
  RecipeDifficulty,
  RecipeFastLevel,
} from '../../src/lib/recipes/fastingRecipes';
import { MARILENA_EXTRA_RECIPES } from './marilenaExtra';
import { MIA_KOUPPA_EXTRA_RECIPES } from './miaKouppaExtra';

function L(en: string, ru: string, el: string): LocalizedText {
  return { en, ru, el };
}

function lines(en: string[], ru: string[], el: string[]): LocalizedLines {
  return { en, ru, el };
}

function R(input: {
  id: string;
  level: RecipeFastLevel;
  category: RecipeCategory;
  difficulty: RecipeDifficulty;
  prepMinutes: number;
  cookMinutes: number;
  servings: number;
  servingSize: LocalizedText;
  title: LocalizedText;
  summary: LocalizedText;
  ingredients: LocalizedLines;
  steps: LocalizedLines;
  tips: LocalizedLines;
  notes?: LocalizedText;
}): FastingRecipe {
  return input;
}

const CORE_FASTING_RECIPES: FastingRecipe[] = [
R({
    id: 'oat-porridge',
    level: 'strict',
    category: 'breakfast',
    difficulty: 'easy',
    prepMinutes: 5,
    cookMinutes: 12,
    servings: 2,
    servingSize: L('1 bowl (~300 g)', '1 миска (~300 г)', '1 μπολ (~300 γρ.)'),
    title: L('Oat porridge with fruit', 'Овсянка с фруктами', 'Νιφάδες βρώμης με φρούτα'),
    summary: L(
      'Warm rolled oats simmered in water, finished with banana or dried fruit — a classic strict-fast breakfast.',
      'Тёплая овсянка на воде с бананом или сухофруктами — простое строгое блюдо.',
      'Ζεστή βρώμη σε νερό με μπανάνα ή ξερά φρούτα — απλό αυστηρό πρωινό.',
    ),
    ingredients: lines(
      [
        '1 cup (90 g) rolled oats',
        '2 cups (480 ml) water',
        'Pinch of fine salt',
        '1 ripe banana, sliced — or 3 tbsp raisins',
        '½ tsp ground cinnamon (optional)',
        '1 tsp maple syrup or date syrup (optional, if used in your practice)',
      ],
      [
        '1 стакан (90 г) овсяных хлопьев',
        '2 стакана (480 мл) воды',
        'Щепотка соли',
        '1 спелый банан ломтиками — или 3 ст.л. изюма',
        '½ ч.л. корицы (по желанию)',
        '1 ч.л. кленового/финиковго сиропа (по желанию)',
      ],
      [
        '1 φλ. (90 γρ.) νιφάδες βρώμης',
        '2 φλ. (480 ml) νερό',
        'Πιτσίλισμα αλάτι',
        '1 ώριμη μπανάνα σε φέτες — ή 3 κ.σ. σταφίδες',
        '½ κ.γ. κανέλα (προαιρετικά)',
        '1 κ.γ. σιρόπι σφενδάμου ή χουρμά (προαιρετικά)',
      ],
    ),
    steps: lines(
      [
        'Bring the water and salt to a gentle boil in a small saucepan.',
        'Stir in the oats. Lower heat and simmer 8–10 minutes, stirring often, until creamy.',
        'Remove from heat. Fold in half the fruit and cinnamon.',
        'Divide into 2 bowls (~300 g each). Top with remaining fruit and optional syrup. Serve hot.',
      ],
      [
        'Доведите воду с солью до слабого кипения.',
        'Всыпьте овсянку. Убавьте огонь и варите 8–10 мин, помешивая, до кремовости.',
        'Снимите с огня. Добавьте половину фруктов и корицу.',
        'Разложите в 2 миски (~300 г). Сверху оставшиеся фрукты и сироп. Подавайте горячим.',
      ],
      [
        'Βράστε απαλά το νερό με αλάτι.',
        'Προσθέστε τη βρώμη. Χαμηλώστε και σιγοβράστε 8–10 λεπτά, ανακατεύοντας, μέχρι κρεμώδες.',
        'Κατεβάστε από τη φωτιά. Ανακατέψτε τα μισά φρούτα και την κανέλα.',
        'Μοιράστε σε 2 μπολ (~300 γρ.). Από πάνω τα υπόλοιπα φρούτα και προαιρετικά σιρόπι. Ζεστό.',
      ],
    ),
    tips: lines(
      [
        'Steel-cut oats need ~20–25 minutes and more water.',
        'For thicker porridge, use 1¾ cups water; for looser, add a splash at the end.',
      ],
      [
        'Цельнозерновой овёс варится 20–25 мин и требует больше воды.',
        'Для густой каши — 1¾ стакана воды; для жидкой — долейте в конце.',
      ],
      [
        'Η χοντρή βρώμη θέλει ~20–25 λεπτά και περισσότερο νερό.',
        'Για πιο πηχτό: 1¾ φλ. νερό· για πιο αραιό, λίγο νερό στο τέλος.',
      ],
    ),
  }),
R({
    id: 'hummus',
    level: 'strict',
    category: 'side',
    difficulty: 'easy',
    prepMinutes: 10,
    cookMinutes: 0,
    servings: 6,
    servingSize: L('~⅓ cup (80 g)', '~⅓ стакана (80 г)', '~⅓ φλ. (80 γρ.)'),
    title: L('Oil-free chickpea hummus', 'Хумус без масла', 'Χούμους χωρίς λάδι'),
    summary: L(
      'Smooth chickpea dip with lemon and garlic — thinned with aquafaba so it stays strict-fast friendly.',
      'Нежный хумус с лимоном и чесноком — разбавлен жидкостью от нута, без масла.',
      'Απαλό χούμους με λεμόνι και σκόρδο — αραιωμένο με νερό ρεβιθιών, χωρίς λάδι.',
    ),
    ingredients: lines(
      [
        '1 can (400 g) chickpeas, drained — reserve 6 tbsp aquafaba',
        'Juice of 1 large lemon (~3 tbsp)',
        '2 garlic cloves, minced',
        '½ tsp fine salt, plus more to taste',
        '½ tsp ground cumin',
        'Paprika and raw vegetable sticks, to serve',
      ],
      [
        '1 банка (400 г) нута, откинуть — оставить 6 ст.л. жидкости',
        'Сок 1 крупного лимона (~3 ст.л.)',
        '2 зубчика чеснока',
        '½ ч.л. соли, ещё по вкусу',
        '½ ч.л. молотого тмина',
        'Паприка и сырые овощи для подачи',
      ],
      [
        '1 κονσέρβα (400 γρ.) ρεβίθια — κρατήστε 6 κ.σ. νερό ρεβιθιών',
        'Χυμός 1 μεγάλου λεμονιού (~3 κ.σ.)',
        '2 σκελίδες σκόρδο',
        '½ κ.γ. αλάτι, κι άλλο στη γεύση',
        '½ κ.γ. κύμινο',
        'Πάπρικα και ωμά λαχανικά για σερβίρισμα',
      ],
    ),
    steps: lines(
      [
        'Add chickpeas, lemon juice, garlic, salt, and cumin to a blender or food processor.',
        'Blend, adding aquafaba 1 tbsp at a time, until smooth and scoopable (about 4–6 tbsp).',
        'Taste and adjust salt and lemon. Chill 15 minutes if you can.',
        'Serve ~80 g portions with paprika on top and cut vegetables.',
      ],
      [
        'Сложите нут, лимон, чеснок, соль и тмин в блендер.',
        'Измельчайте, добавляя по 1 ст.л. жидкости, до гладкости (4–6 ст.л.).',
        'Попробуйте; досолите и добавьте лимон. По возможности охладите 15 мин.',
        'Подавайте порциями ~80 г с паприкой и овощами.',
      ],
      [
        'Βάλτε ρεβίθια, λεμόνι, σκόρδο, αλάτι και κύμινο στο μπλέντερ.',
        'Χτυπήστε, προσθέτοντας 1 κ.σ. νερό κάθε φορά, μέχρι κρεμώδες (4–6 κ.σ.).',
        'Δοκιμάστε αλάτι και λεμόνι. Αν μπορείτε, κρυώστε 15 λεπτά.',
        'Σερβίρετε ~80 γρ. με πάπρικα και λαχανικά.',
      ],
    ),
    tips: lines(
      [
        'Peeling chickpeas makes a silkier dip, but is optional.',
        'On wine-and-oil days, finish with 1–2 tbsp tahini or olive oil.',
      ],
      [
        'Очищенный нут даёт более нежную текстуру.',
        'В дни с маслом добавьте 1–2 ст.л. тахини или оливкового масла.',
      ],
      [
        'Αν ξεφλουδίσετε τα ρεβίθια, γίνεται πιο βελούδινο.',
        'Σε ημέρες λαδιού προσθέστε 1–2 κ.σ. ταχίνι ή ελαιόλαδο.',
      ],
    ),
  }),
R({
    id: 'lentil-soup',
    level: 'strict',
    category: 'soup',
    difficulty: 'easy',
    prepMinutes: 15,
    cookMinutes: 30,
    servings: 4,
    servingSize: L('1½ cups (~360 ml)', '1½ стакана (~360 мл)', '1½ φλ. (~360 ml)'),
    title: L('Red lentil soup', 'Суп из красной чечевицы', 'Σούπα κόκκινης φακής'),
    summary: L(
      'Hearty Lenten soup with onion, carrot, and cumin — no oil, finished with lemon.',
      'Сытный постный суп с луком, морковью и тмином — без масла, с лимоном.',
      'Χορταστική νηστίσιμη σούπα με κρεμμύδι, καρότο και κύμινο — χωρίς λάδι, με λεμόνι.',
    ),
    ingredients: lines(
      [
        '1½ cups (300 g) red lentils, rinsed',
        '1 medium onion, finely chopped',
        '2 medium carrots, diced',
        '1 tsp ground cumin',
        '6 cups (1.4 L) water or vegetable broth (check label)',
        '1¼ tsp fine salt, black pepper',
        'Lemon wedges, to serve',
        'Fresh parsley or cilantro (optional)',
      ],
      [
        '1½ стакана (300 г) красной чечевицы, промыть',
        '1 средняя луковица, мелко',
        '2 средние моркови кубиками',
        '1 ч.л. молотого тмина',
        '6 стаканов (1,4 л) воды или овощного бульона',
        '1¼ ч.л. соли, чёрный перец',
        'Дольки лимона',
        'Петрушка или кинза (по желанию)',
      ],
      [
        '1½ φλ. (300 γρ.) κόκκινη φακή, πλυμένη',
        '1 κρεμμύδι ψιλοκομμένο',
        '2 καρότα σε κύβους',
        '1 κ.γ. κύμινο',
        '6 φλ. (1,4 L) νερό ή ζωμό λαχανικών',
        '1¼ κ.γ. αλάτι, πιπέρι',
        'Λεμόνι σε φέτες',
        'Μαϊντανός ή κόλιανδρος (προαιρετικά)',
      ],
    ),
    steps: lines(
      [
        'In a heavy pot, add onion, carrot, and 3 tbsp water. Cover and steam-sauté 5–6 minutes until soft, adding splashes of water so nothing sticks.',
        'Stir in cumin for 30 seconds. Add lentils and remaining water. Bring to a boil.',
        'Skim foam. Simmer uncovered 22–25 minutes until lentils collapse and soup thickens.',
        'Season with salt and pepper. Mash lightly with a spoon for a creamier texture if you like.',
        'Ladle ~360 ml per bowl. Finish with lemon juice and herbs.',
      ],
      [
        'В кастрюле припустите лук и морковь с 3 ст.л. воды под крышкой 5–6 мин, добавляя воду, чтобы не пригорало.',
        'Всыпьте тмин на 30 сек. Добавьте чечевицу и остальную воду. Доведите до кипения.',
        'Снимите пену. Варите без крышки 22–25 мин, пока чечевица разварится.',
        'Посолите и поперчите. При желании слегка разомните ложкой.',
        'Налейте ~360 мл в тарелку. Добавьте лимон и зелень.',
      ],
      [
        'Σε κατσαρόλα μαλακώστε κρεμμύδι και καρότο με 3 κ.σ. νερό σκεπαστά 5–6 λεπτά.',
        'Προσθέστε κύμινο 30 δεύτερα. Φακή και υπόλοιπο νερό· βράστε.',
        'Αφαιρέστε αφρό. Σιγοβράστε χωρίς καπάκι 22–25 λεπτά μέχρι να λιώσει η φακή.',
        'Αλατοπιπερώστε. Αν θέλετε, λιώστε λίγο με κουτάλι.',
        'Σερβίρετε ~360 ml με λεμόνι και βότανα.',
      ],
    ),
    tips: lines(
      [
        'Soup thickens as it cools — thin with hot water when reheating.',
        'On oil days, start the vegetables in 2 tbsp olive oil instead of water.',
      ],
      [
        'Суп густеет при остывании — разбавьте горячей водой при разогреве.',
        'В дни с маслом обжарьте овощи на 2 ст.л. оливкового масла.',
      ],
      [
        'Πήζει καθώς κρυώνει — αραιώστε με ζεστό νερό στο ζέσταμα.',
        'Σε ημέρες λαδιού σοτάρετε τα λαχανικά σε 2 κ.σ. ελαιόλαδο.',
      ],
    ),
  }),
R({
    id: 'bean-stew',
    level: 'strict',
    category: 'main',
    difficulty: 'medium',
    prepMinutes: 15,
    cookMinutes: 35,
    servings: 4,
    servingSize: L('1¼ cups (~280 g)', '1¼ стакана (~280 г)', '1¼ φλ. (~280 γρ.)'),
    title: L('Tomato bean stew', 'Фасоль в томате', 'Φασόλια κοκκινιστά'),
    summary: L(
      'White beans simmered with onion, tomato, and bay — a monastery-style main for strict days.',
      'Белая фасоль с луком, томатом и лавром — монастырское основное блюдо для строгого поста.',
      'Άσπρα φασόλια με κρεμμύδι, ντομάτα και δαφνή — μοναστηριακό κυρίως πιάτο.',
    ),
    ingredients: lines(
      [
        '3 cups (450 g) cooked white beans — or 2 cans, rinsed',
        '1 large onion, sliced',
        '2 cups (480 ml) tomato passata or crushed tomatoes',
        '2 bay leaves',
        '1 tsp sweet paprika',
        '1 tsp salt, black pepper',
        '½ cup (120 ml) water, as needed',
        'Handful of parsley, chopped',
      ],
      [
        '3 стакана (450 г) варёной белой фасоли — или 2 банки, промыть',
        '1 крупная луковица полукольцами',
        '2 стакана (480 мл) томатной пассы или измельчённых томатов',
        '2 лавровых листа',
        '1 ч.л. сладкой паприки',
        '1 ч.л. соли, чёрный перец',
        '½ стакана (120 мл) воды по необходимости',
        'Горсть петрушки',
      ],
      [
        '3 φλ. (450 γρ.) βρασμένα άσπρα φασόλια — ή 2 κονσέρβες',
        '1 μεγάλο κρεμμύδι σε φέτες',
        '2 φλ. (480 ml) ντομάτα passata ή λιωμένη',
        '2 δαφνόφυλλα',
        '1 κ.γ. γλυκιά πάπρικα',
        '1 κ.γ. αλάτι, πιπέρι',
        '½ φλ. (120 ml) νερό αν χρειαστεί',
        'Μαϊντανός ψιλοκομμένος',
      ],
    ),
    steps: lines(
      [
        'Steam-sauté onion with 3–4 tbsp water in a wide pan until translucent, 7–8 minutes.',
        'Add paprika, tomato, bay, salt, and pepper. Simmer 8 minutes to thicken slightly.',
        'Fold in beans and a splash of water. Cover and simmer gently 20 minutes so flavours marry.',
        'Discard bay leaves. Adjust seasoning. Stir in parsley off heat.',
        'Serve ~280 g per person with bread or rice (strict rice if needed).',
      ],
      [
        'Припустите лук с 3–4 ст.л. воды 7–8 мин до мягкости.',
        'Добавьте паприку, томат, лавр, соль и перец. Тушите 8 мин.',
        'Добавьте фасоль и немного воды. Под крышкой тушите 20 мин.',
        'Уберите лавр. По вкусу досолите. Вмешайте петрушку.',
        'Порция ~280 г с хлебом или рисом.',
      ],
      [
        'Μαλακώστε το κρεμμύδι με 3–4 κ.σ. νερό 7–8 λεπτά.',
        'Προσθέστε πάπρικα, ντομάτα, δαφνή, αλάτι, πιπέρι. 8 λεπτά.',
        'Φασόλια και λίγο νερό· σκεπάστε 20 λεπτά σε χαμηλή φωτιά.',
        'Βγάλτε τη δαφνή. Δοκιμάστε. Μαϊντανός εκτός φωτιάς.',
        'Σερβίρετε ~280 γρ. με ψωμί ή ρύζι.',
      ],
    ),
    tips: lines(
      [
        'Dried beans: soak overnight, then boil until tender before starting the stew.',
        'A pinch of sugar balances acidic tomatoes.',
      ],
      [
        'Сухую фасоль замочите на ночь и отварите до мягкости.',
        'Щепотка сахара смягчает кислоту томатов.',
      ],
      [
        'Ξερά φασόλια: μουλιάστε overnight και βράστε πριν τη σάλτσα.',
        'Πιτσίλισμα ζάχαρη ισορροπεί την οξύτητα της ντομάτας.',
      ],
    ),
  }),
R({
    id: 'cabbage-salad',
    level: 'strict',
    category: 'salad',
    difficulty: 'easy',
    prepMinutes: 15,
    cookMinutes: 0,
    servings: 4,
    servingSize: L('1 cup (~120 g)', '1 стакан (~120 г)', '1 φλ. (~120 γρ.)'),
    title: L('Cabbage and carrot salad', 'Салат из капусты и моркови', 'Σαλάτα λάχανο-καρότο'),
    summary: L(
      'Crunchy shredded cabbage with carrot, vinegar, and dill — no oil needed.',
      'Хрустящая капуста с морковью, уксусом и укропом — без масла.',
      'Τραγανό λάχανο με καρότο, ξίδι και άνηθο — χωρίς λάδι.',
    ),
    ingredients: lines(
      [
        '½ medium white cabbage (~500 g), finely shredded',
        '2 medium carrots, grated',
        '2 tbsp apple cider vinegar or lemon juice',
        '¾ tsp fine salt',
        '1 tsp sugar or maple syrup (optional)',
        '3 tbsp chopped fresh dill',
        'Freshly ground black pepper',
      ],
      [
        '½ среднего кочана капусты (~500 г), тонко нашинковать',
        '2 средние моркови, натереть',
        '2 ст.л. яблочного уксуса или лимонного сока',
        '¾ ч.л. соли',
        '1 ч.л. сахара или сиропа (по желанию)',
        '3 ст.л. свежего укропа',
        'Свежемолотый чёрный перец',
      ],
      [
        '½ μέτριο λάχανο (~500 γρ.), ψιλοκομμένο',
        '2 καρότα τριμμένα',
        '2 κ.σ. μηλόξιδο ή χυμό λεμονιού',
        '¾ κ.γ. αλάτι',
        '1 κ.γ. ζάχαρη ή σιρόπι (προαιρετικά)',
        '3 κ.σ. φρέσκο άνηθο',
        'Φρεσκοτριμμένο πιπέρι',
      ],
    ),
    steps: lines(
      [
        'Toss cabbage and carrot with salt in a large bowl. Massage 1–2 minutes until slightly wilted.',
        'Add vinegar (and sugar if using). Toss well and rest 10 minutes.',
        'Fold in dill and pepper. Taste — add more acid or salt if needed.',
        'Serve ~120 g per person cold or room temperature.',
      ],
      [
        'Смешайте капусту и морковь с солью; помните 1–2 мин.',
        'Добавьте уксус (и сахар). Перемешайте; подержите 10 мин.',
        'Добавьте укроп и перец. Попробуйте.',
        'Порция ~120 г, охлаждённым или комнатной температуры.',
      ],
      [
        'Ανακατέψτε λάχανο και καρότο με αλάτι· μαλάξτε 1–2 λεπτά.',
        'Προσθέστε ξίδι (και ζάχαρη). 10 λεπτά ξεκούραση.',
        'Άνηθος και πιπέρι. Δοκιμάστε.',
        'Σερβίρετε ~120 γρ. κρύο ή σε θερμοκρασία δωματίου.',
      ],
    ),
    tips: lines(
      [
        'Make up to a day ahead — it softens and sweetens in the fridge.',
        'On oil days, dress with 2 tbsp olive oil just before serving.',
      ],
      [
        'Можно за день — в холодильнике становится мягче и слаще.',
        'В дни с маслом заправьте 2 ст.л. оливкового масла перед подачей.',
      ],
      [
        'Κρατάει έως μία ημέρα στο ψυγείο.',
        'Σε ημέρες λαδιού προσθέστε 2 κ.σ. ελαιόλαδο πριν σερβίρετε.',
      ],
    ),
  }),
R({
    id: 'potato-hash',
    level: 'strict',
    category: 'main',
    difficulty: 'easy',
    prepMinutes: 10,
    cookMinutes: 25,
    servings: 3,
    servingSize: L('1½ cups (~250 g)', '1½ стакана (~250 г)', '1½ φλ. (~250 γρ.)'),
    title: L('Water-sautéed potatoes', 'Картофель на воде', 'Πατάτες σοτέ σε νερό'),
    summary: L(
      'Crisp-edged potatoes and onion cooked with steam and little water — no oil for strict fast.',
      'Картофель с луком «на воде» с корочкой — без масла для строгого поста.',
      'Πατάτες με κρεμμύδι σε ατμό/νερό — χωρίς λάδι για αυστηρή νηστεία.',
    ),
    ingredients: lines(
      [
        '4 medium potatoes (~800 g), scrubbed, 2 cm cubes',
        '1 large onion, sliced',
        '¾ tsp salt, black pepper',
        '1 tsp sweet paprika',
        '½ cup (120 ml) water, plus more as needed',
        'Fresh dill or green onion, to finish',
      ],
      [
        '4 средние картофелины (~800 г), кубики 2 см',
        '1 крупная луковица полукольцами',
        '¾ ч.л. соли, чёрный перец',
        '1 ч.л. сладкой паприки',
        '½ стакана (120 мл) воды, ещё по необходимости',
        'Укроп или зелёный лук',
      ],
      [
        '4 μέτριες πατάτες (~800 γρ.), κύβοι 2 εκ.',
        '1 μεγάλο κρεμμύδι σε φέτες',
        '¾ κ.γ. αλάτι, πιπέρι',
        '1 κ.γ. γλυκιά πάπρικα',
        '½ φλ. (120 ml) νερό, κι άλλο αν χρειαστεί',
        'Άνηθος ή φρέσκο κρεμμύδι',
      ],
    ),
    steps: lines(
      [
        'Place potatoes in a wide nonstick or well-seasoned pan with ½ cup water and salt. Cover tightly.',
        'Cook over medium heat 12–14 minutes until almost tender, shaking occasionally.',
        'Uncover, add onion and paprika. Cook, stirring, adding tiny splashes of water, until edges brown and onion softens, 8–10 minutes.',
        'Season with pepper. Finish with herbs. Serve ~250 g per person.',
      ],
      [
        'Выложите картофель в широкую сковороду с ½ стакана воды и солью. Плотно закройте.',
        'Готовьте на среднем огне 12–14 мин почти до мягкости, иногда встряхивая.',
        'Откройте, добавьте лук и паприку. Жарьте, помешивая и добавляя капли воды, 8–10 мин до румяности.',
        'Поперчите, добавьте зелень. Порция ~250 г.',
      ],
      [
        'Βάλτε πατάτες σε φαρδύ τηγάνι με ½ φλ. νερό και αλάτι. Σκεπάστε καλά.',
        'Ψήστε σε μέτρια φωτιά 12–14 λεπτά σχεδόν μαλακές.',
        'Ξεσκεπάστε, κρεμμύδι και πάπρικα. Ανακατέψτε 8–10 λεπτά με σταγόνες νερό μέχρι να ροδίσουν.',
        'Πιπέρι και βότανα. Σερβίρετε ~250 γρ.',
      ],
    ),
    tips: lines(
      [
        'A heavy lid traps steam — that is what cooks the potatoes without oil.',
        'Leftovers reheat well in a covered pan with a spoon of water.',
      ],
      [
        'Тяжёлая крышка удерживает пар — так картофель готовится без масла.',
        'Остатки разогревайте под крышкой с ложкой воды.',
      ],
      [
        'Βαρύ καπάκι κρατά τον ατμό — έτσι ψήνονται χωρίς λάδι.',
        'Τα περισσεύματα ζεσταίνονται σκεπαστά με κουταλιά νερό.',
      ],
    ),
  }),
R({
    id: 'fruit-compote',
    level: 'strict',
    category: 'sweet',
    difficulty: 'easy',
    prepMinutes: 5,
    cookMinutes: 20,
    servings: 6,
    servingSize: L('1 cup liquid + fruit (~250 ml)', '1 стакан с фруктами (~250 мл)', '1 φλ. με φρούτα (~250 ml)'),
    title: L('Dried fruit compote (uzvar)', 'Компот из сухофруктов (узва́р)', 'Κομπόστα αποξηραμένων'),
    summary: L(
      'Lightly sweetened dried-fruit drink served warm or chilled — traditional for Lenten and memorial tables.',
      'Слабо подслащённый напиток из сухофруктов — тёплым или холодным, для поста и поминальных столов.',
      'Ελαφρά γλυκό ποτό από ξερά φρούτα — ζεστό ή κρύο, για νηστεία και μνημόσυνα.',
    ),
    ingredients: lines(
      [
        '2 cups (280 g) mixed dried fruit (apple, pear, prune, apricot)',
        '8 cups (1.9 L) water',
        '1 cinnamon stick',
        '2–3 tbsp sugar, or to taste',
        'Optional: 2 whole cloves',
      ],
      [
        '2 стакана (280 г) смеси сухофруктов (яблоко, груша, чернослив, курага)',
        '8 стаканов (1,9 л) воды',
        '1 палочка корицы',
        '2–3 ст.л. сахара по вкусу',
        'По желанию: 2 бутона гвоздики',
      ],
      [
        '2 φλ. (280 γρ.) ανάμεικτα ξερά φρούτα',
        '8 φλ. (1,9 L) νερό',
        '1 ξύλο κανέλας',
        '2–3 κ.σ. ζάχαρη στη γεύση',
        'Προαιρετικά: 2 γαρίφαλα',
      ],
    ),
    steps: lines(
      [
        'Rinse dried fruit. Combine with water, cinnamon, and cloves in a pot.',
        'Bring to a boil, then simmer gently 15–20 minutes until fruit plumps.',
        'Stir in sugar off heat until dissolved. Taste and adjust sweetness.',
        'Cool slightly. Serve ~250 ml per person with some fruit in each cup. Chill leftovers.',
      ],
      [
        'Промойте сухофрукты. Сложите с водой, корицей и гвоздикой в кастрюлю.',
        'Доведите до кипения, затем варите 15–20 мин на слабом огне.',
        'Снимите с огня, растворите сахар. Попробуйте.',
        'Остудите. Порция ~250 мл с фруктами. Остатки охладите.',
      ],
      [
        'Πλύνετε τα φρούτα. Βάλτε με νερό, κανέλα και γαρίφαλα σε κατσαρόλα.',
        'Βράστε και σιγοβράστε 15–20 λεπτά μέχρι να φουσκώσουν.',
        'Κατεβάστε· διαλύστε τη ζάχαρη. Δοκιμάστε.',
        'Κρυώστε λίγο. Σερβίρετε ~250 ml με φρούτα. Ψύξτε τα περισσεύματα.',
      ],
    ),
    tips: lines(
      [
        'Sweeter fruit (dates, raisins) means you can use less sugar.',
        'Strain for a clear drink, or leave fruit in for a rustic cup.',
      ],
      [
        'Более сладкие сухофрукты позволяют меньше сахара.',
        'Процедите для прозрачного напитка или оставьте фрукты в чашке.',
      ],
      [
        'Πιο γλυκά φρούτα = λιγότερη ζάχαρη.',
        'Σουρώστε για καθαρό ρόφημα ή αφήστε τα φρούτα στο φλιτζάνι.',
      ],
    ),
  }),
R({
    id: 'buckwheat',
    level: 'strict',
    category: 'side',
    difficulty: 'easy',
    prepMinutes: 5,
    cookMinutes: 20,
    servings: 4,
    servingSize: L('¾ cup cooked (~140 g)', '¾ стакана (~140 г)', '¾ φλ. (~140 γρ.)'),
    title: L('Buckwheat kasha', 'Гречневая каша', 'Φαγόπυρο (κασά)'),
    summary: L(
      'Toasted buckwheat simmered in water — a Russian Lenten side that pairs with almost anything.',
      'Поджаренная гречка на воде — русский постный гарнир почти ко всему.',
      'Καβουρδισμένο φαγόπυρο σε νερό — ρωσικό νηστίσιμο συνοδευτικό.',
    ),
    ingredients: lines(
      [
        '1 cup (180 g) roasted buckwheat groats',
        '2 cups (480 ml) water',
        '¾ tsp salt',
        'Optional on oil days: 1 small onion fried in 1 tbsp oil',
      ],
      [
        '1 стакан (180 г) гречневой крупы (ядрица)',
        '2 стакана (480 мл) воды',
        '¾ ч.л. соли',
        'В дни с маслом: 1 луковица на 1 ст.л. масла',
      ],
      [
        '1 φλ. (180 γρ.) φαγόπυρο',
        '2 φλ. (480 ml) νερό',
        '¾ κ.γ. αλάτι',
        'Σε ημέρες λαδιού: 1 κρεμμύδι σε 1 κ.σ. λάδι',
      ],
    ),
    steps: lines(
      [
        'Toast buckwheat in a dry pot 2–3 minutes until fragrant (skip if already dark roasted).',
        'Add water and salt. Bring to a boil, cover, reduce to low.',
        'Simmer 15 minutes without lifting the lid. Rest 5 minutes off heat.',
        'Fluff with a fork. Serve ~140 g per person. Fold in fried onion on oil days.',
      ],
      [
        'Подсушите крупу на сухой сковороде/в кастрюле 2–3 мин (если ещё светлая).',
        'Добавьте воду и соль. Вскипятите, накройте, убавьте огонь.',
        'Варите 15 мин, не открывая. Дайте постоять 5 мин.',
        'Рассыпьте вилкой. Порция ~140 г; с луком — в дни с маслом.',
      ],
      [
        'Καβουρδίστε 2–3 λεπτά σε στεγνή κατσαρόλα (αν χρειάζεται).',
        'Νερό και αλάτι· βράστε, σκεπάστε, χαμηλώστε.',
        '15 λεπτά χωρίς να ανοίξετε. 5 λεπτά ξεκούραση.',
        'Χαλαρώστε με πιρούνι. ~140 γρ. ανά μερίδα· κρεμμύδι σε ημέρες λαδιού.',
      ],
    ),
    tips: lines(
      [
        'Ratio is usually 1:2 buckwheat to water by volume.',
        'Do not stir while simmering or it turns mushy.',
      ],
      [
        'Обычная пропорция 1:2 крупа:вода по объёму.',
        'Не мешайте при варке — иначе размажется.',
      ],
      [
        'Αναλογία συνήθως 1:2 φαγόπυρο προς νερό.',
        'Μην ανακατεύετε στο σιγοβράσιμο.',
      ],
    ),
  }),
R({
    id: 'herbal-tea',
    level: 'strict',
    category: 'drink',
    difficulty: 'easy',
    prepMinutes: 2,
    cookMinutes: 8,
    servings: 2,
    servingSize: L('1 mug (~250 ml)', '1 кружка (~250 мл)', '1 κούπα (~250 ml)'),
    title: L('Mint and lemon herbal tea', 'Травяной чай с мятой и лимоном', 'Τσάι δυόσμου και λεμονιού'),
    summary: L(
      'Caffeine-free pot of mint with lemon — soothing on any strict day.',
      'Бескофеиновый чай с мятой и лимоном — мягкий напиток в любой строгий день.',
      'Τσάι χωρίς καφεΐνη με δυόσμο και λεμόνι — απαλό ρόφημα σε αυστηρή νηστεία.',
    ),
    ingredients: lines(
      [
        '2 large handfuls fresh mint (or 2 tbsp dried)',
        '2½ cups (600 ml) water',
        '2 thin lemon slices',
        'Optional: 1 tsp honey per mug if your practice allows',
      ],
      [
        '2 горсти свежей мяты (или 2 ст.л. сушёной)',
        '2½ стакана (600 мл) воды',
        '2 тонких кружка лимона',
        'По желанию: 1 ч.л. мёда на кружку, если принято',
      ],
      [
        '2 χούφτες φρέσκο δυόσμο (ή 2 κ.σ. ξερό)',
        '2½ φλ. (600 ml) νερό',
        '2 λεπτές φέτες λεμονιού',
        'Προαιρετικά: 1 κ.γ. μέλι ανά κούπα αν επιτρέπεται',
      ],
    ),
    steps: lines(
      [
        'Bring water to a boil. Remove from heat.',
        'Add mint and lemon. Cover and steep 5–8 minutes.',
        'Strain into 2 mugs (~250 ml each). Sweeten only if appropriate for your fast.',
      ],
      [
        'Вскипятите воду. Снимите с огня.',
        'Добавьте мяту и лимон. Накройте на 5–8 мин.',
        'Процедите в 2 кружки (~250 мл). Подсластите только если уместно.',
      ],
      [
        'Βράστε νερό. Κατεβάστε από τη φωτιά.',
        'Προσθέστε δυόσμο και λεμόνι. Σκεπάστε 5–8 λεπτά.',
        'Σουρώστε σε 2 κούπες (~250 ml). Γλυκάνετε μόνο αν ταιριάζει στη νηστεία.',
      ],
    ),
    tips: lines(
      [
        'Dried mint is stronger — start with less and taste.',
        'Chamomile or linden blossom work the same way.',
      ],
      [
        'Сушёная мята крепче — начните с меньшей порции.',
        'Так же заваривают ромашку или липу.',
      ],
      [
        'Ο ξερός δυόσμος είναι πιο δυνατός — ξεκινήστε με λιγότερο.',
        'Το ίδιο γίνεται με χαμομήλι ή φλαμούρι.',
      ],
    ),
  }),
R({
    id: 'smoothie-bowl',
    level: 'strict',
    category: 'breakfast',
    difficulty: 'easy',
    prepMinutes: 10,
    cookMinutes: 0,
    servings: 1,
    servingSize: L('1 bowl (~400 g)', '1 миска (~400 г)', '1 μπολ (~400 γρ.)'),
    title: L('Berry smoothie bowl', 'Ягодный смузи-боул', 'Bowl με μούρα'),
    summary: L(
      'Thick blended frozen berries with banana — dairy-free breakfast you eat with a spoon.',
      'Густой смузи из замороженных ягод и банана — безмолочный завтрак ложкой.',
      'Πηχτό smoothie από κατεψυγμένα μούρα και μπανάνα — πρωινό χωρίς γάλα.',
    ),
    ingredients: lines(
      [
        '2 cups (280 g) frozen mixed berries',
        '½ ripe banana',
        '3–5 tbsp cold water or fruit juice, as needed',
        '1 tbsp seeds (pumpkin or sunflower)',
        'Optional: 2 tbsp dairy-free granola (check label)',
      ],
      [
        '2 стакана (280 г) замороженных ягод',
        '½ спелого банана',
        '3–5 ст.л. холодной воды или сока',
        '1 ст.л. семян (тыквы или подсолнечника)',
        'По желанию: 2 ст.л. гранолы без молока',
      ],
      [
        '2 φλ. (280 γρ.) κατεψυγμένα μούρα',
        '½ ώριμη μπανάνα',
        '3–5 κ.σ. κρύο νερό ή χυμό',
        '1 κ.σ. σπόρους',
        'Προαιρετικά: 2 κ.σ. granola χωρίς γάλα',
      ],
    ),
    steps: lines(
      [
        'Blend berries and banana with just enough liquid to move the blades — keep it thick.',
        'Scrape into a bowl (~400 g).',
        'Top with seeds and optional granola. Eat immediately.',
      ],
      [
        'Измельчите ягоды и банан с минимумом жидкости — масса должна быть густой.',
        'Выложите в миску (~400 г).',
        'Посыпьте семенами и гранолой. Ешьте сразу.',
      ],
      [
        'Χτυπήστε μούρα και μπανάνα με ελάχιστο υγρό — να μείνει πηχτό.',
        'Σε μπολ (~400 γρ.).',
        'Σπόροι και προαιρετικά granola. Φάτε αμέσως.',
      ],
    ),
    tips: lines(
      [
        'Frozen fruit must be truly frozen for a scoopable texture.',
        'A high-speed blender helps; otherwise chop fruit smaller first.',
      ],
      [
        'Для густой текстуры ягоды должны быть хорошо заморожены.',
        'Мощный блендер помогает; иначе нарежьте фрукты мельче.',
      ],
      [
        'Τα φρούτα πρέπει να είναι καλά κατεψυγμένα για υφή παγωτού.',
        'Ισχυρό μπλέντερ βοηθά· αλλιώς κόψτε τα φρούτα μικρότερα.',
      ],
    ),
  }),
  R({
    id: 'vegetable-laksa',
    level: 'fish',
    category: 'soup',
    difficulty: 'medium',
    prepMinutes: 20,
    cookMinutes: 25,
    servings: 4,
    servingSize: L('1 deep bowl (~450 ml)', '1 глубокая миска (~450 мл)', '1 βαθύ μπολ (~450 ml)'),
    title: L('Vegetable / prawn laksa', 'Овощная / креветочная лакса', 'Λάκσα λαχανικών / γαρίδας'),
    summary: L(
      'Fragrant coconut-curry noodle soup with vegetables and tofu — add prawns when fish is allowed.',
      'Ароматный кокосово-карри суп с лапшой, овощами и тофу — с креветками, когда разрешена рыба.',
      'Αρωματική σούπα κάρι καρύδας με noodles, λαχανικά και τόφου — με γαρίδες όταν επιτρέπεται ψάρι.',
    ),
    ingredients: lines(
      [
        '200 g dried rice noodles (or ramen-style wheat noodles)',
        '3 tbsp laksa paste or Thai red curry paste',
        '1 can (400 ml) full-fat coconut milk',
        '3 cups (720 ml) vegetable broth',
        '200 g firm tofu, cubed (omit or reduce if using plenty of prawns)',
        '250 g raw prawns, peeled and deveined (optional — for fish days)',
        '1 red bell pepper, thinly sliced',
        '1 cup (100 g) bean sprouts',
        '1 cup (80 g) shredded cabbage or bok choy',
        '1 tbsp soy sauce or tamari',
        '1 tsp brown sugar (optional)',
        'Juice of ½ lime, plus wedges to serve',
        'Fresh cilantro / coriander, chili slices, sliced scallions (optional)',
      ],
      [
        '200 г рисовой лапши (или пшеничной ramen)',
        '3 ст.л. пасты лакса или красной карри',
        '1 банка (400 мл) кокосового молока',
        '3 стакана (720 мл) овощного бульона',
        '200 г твёрдого тофу кубиками (меньше, если много креветок)',
        '250 г сырых креветок, очищенных (по желанию — в рыбные дни)',
        '1 красный перец тонко',
        '1 стакан (100 г) ростков бобов',
        '1 стакан (80 г) капусты или пак-чой',
        '1 ст.л. соевого соуса или тамари',
        '1 ч.л. коричневого сахара (по желанию)',
        'Сок ½ лайма + дольки для подачи',
        'Кинза, чили, зелёный лук (по желанию)',
      ],
      [
        '200 γρ. noodles ρυζιού (ή ramen)',
        '3 κ.σ. πάστα λάκσα ή κόκκινο κάρι',
        '1 κονσέρβα (400 ml) γάλα καρύδας',
        '3 φλ. (720 ml) ζωμό λαχανικών',
        '200 γρ. τόφου σε κύβους (λιγότερο αν βάλετε πολλές γαρίδες)',
        '250 γρ. ωμές γαρίδες καθαρισμένες (προαιρετικά — ημέρες ψαριού)',
        '1 κόκκινη πιπεριά σε λεπτές φέτες',
        '1 φλ. (100 γρ.) φύτρες',
        '1 φλ. (80 γρ.) λάχανο ή bok choy',
        '1 κ.σ. σος σόγιας ή tamari',
        '1 κ.γ. καστανή ζάχαρη (προαιρετικά)',
        'Χυμός ½ λάιμ + φέτες για σερβίρισμα',
        'Κόλιανδρος, καυτερή, φρέσκο κρεμμυδάκι (προαιρετικά)',
      ],
    ),
    steps: lines(
      [
        'Cook noodles according to package directions until just tender. Drain, rinse briefly with cold water, and set aside.',
        'In a wide pot over medium heat, loosen the laksa/curry paste with a splash of coconut milk. Cook 1–2 minutes until fragrant.',
        'Pour in the remaining coconut milk and the broth. Whisk smooth, bring to a gentle simmer.',
        'Add tofu and bell pepper. Simmer 8–10 minutes.',
        'If using prawns, add them now and cook 2–4 minutes until just pink and opaque — do not overcook.',
        'Stir in soy sauce, sugar if using, and cabbage; cook 2–3 minutes more.',
        'Taste — it should be rich, salty-sweet, and fragrant. Finish with lime juice.',
        'Divide noodles among 4 deep bowls. Ladle ~450 ml broth and toppings over each. Finish with sprouts, herbs, chili, and lime wedges.',
      ],
      [
        'Отварите лапшу по инструкции почти до готовности. Откиньте, ополосните холодной водой, отложите.',
        'В широкой кастрюле на среднем огне разведите пасту лакса/карри небольшим количеством кокосового молока. Готовьте 1–2 мин до аромата.',
        'Влейте оставшееся кокосовое молоко и бульон. Размешайте, доведите до слабого кипения.',
        'Добавьте тофу и перец. Варите 8–10 мин.',
        'Если используете креветки — добавьте сейчас и варите 2–4 мин до розового цвета, не переварите.',
        'Всыпьте соевый соус, сахар и капусту; ещё 2–3 мин.',
        'Попробуйте — должно быть насыщенно, солоновато-сладко и ароматно. Добавьте сок лайма.',
        'Разложите лапшу в 4 глубокие миски. Налейте ~450 мл бульона с начинкой. Сверху ростки, зелень, чили и лайм.',
      ],
      [
        'Βράστε τα noodles σχεδόν al dente. Στραγγίστε, ξεπλύνετε με κρύο νερό, αφήστε στην άκρη.',
        'Σε φαρδιά κατσαρόλα σε μέτρια φωτιά, αραιώστε την πάστα με λίγο γάλα καρύδας. 1–2 λεπτά μέχρι αρωματική.',
        'Ρίξτε το υπόλοιπο γάλα καρύδας και τον ζωμό. Ανακατέψτε, σιγοβράστε απαλά.',
        'Προσθέστε τόφου και πιπεριά. 8–10 λεπτά.',
        'Αν βάλετε γαρίδες, προσθέστε τώρα και μαγειρέψτε 2–4 λεπτά μέχρι ροζ — όχι παραπάνω.',
        'Σος σόγιας, ζάχαρη και λάχανο· ακόμη 2–3 λεπτά.',
        'Δοκιμάστε — πλούσιο, αλμυρό-γλυκό, αρωματικό. Τελειώστε με λάιμ.',
        'Μοιράστε noodles σε 4 βαθιά μπολ. Ρίξτε ~450 ml ζωμό και υλικά. Φύτρες, βότανα, καυτερή, λάιμ.',
      ],
    ),
    tips: lines(
      [
        'Skip the prawns for a fully plant-based bowl; keep tofu as the protein.',
        'Many bottled laksa pastes already contain shrimp — fine with prawns; use vegetarian paste for a plant-only version.',
        'For more heat, add fresh bird’s-eye chili or chili flakes at the table.',
      ],
      [
        'Без креветок — полностью растительный вариант; белок даёт тофу.',
        'Многие пасты «лакса» уже с креветкой — нормально с креветками; для растительного варианта берите вегетарианскую пасту.',
        'Для остроты добавьте свежий перец чили или хлопья за столом.',
      ],
      [
        'Χωρίς γαρίδες — πλήρως φυτικό μπολ· πρωτεΐνη από τόφου.',
        'Πολλές πάστες λάκσα έχουν ήδη γαρίδα — εντάξει με γαρίδες· για φυτική εκδοχή διαλέξτε χορτοφαγική πάστα.',
        'Για πιο καυτερό, φρέσκια καυτερή ή νιφάδες τσίλι στο τραπέζι.',
      ],
    ),
    notes: L(
      'No cooking oil — the paste is loosened in coconut milk. Prawns only when fish is allowed; otherwise keep it vegetable and tofu.',
      'Без масла — паста разводится в кокосовом молоке. Креветки — только когда разрешена рыба; иначе овощи и тофу.',
      'Χωρίς λάδι μαγειρέματος — η πάστα αραιώνεται σε γάλα καρύδας. Γαρίδες μόνο όταν επιτρέπεται ψάρι· αλλιώς λαχανικά και τόφου.',
    ),
  }),
  R({
    id: 'beet-bean-salad',
    level: 'strict',
    category: 'salad',
    difficulty: 'easy',
    prepMinutes: 15,
    cookMinutes: 0,
    servings: 4,
    servingSize: L('1 bowl (~200 g)', '1 миска (~200 г)', '1 μπολ (~200 γρ.)'),
    title: L('Beet and white bean salad', 'Салат из свёклы с фасолью', 'Σαλάτα παντζάρι με φασόλια'),
    summary: L(
      'Earthy beets, white beans, garlic, and vinegar — a classic Slavic Lenten plate. Use pre-cooked beets; no oil.',
      'Свёкла, белая фасоль, чеснок и уксус — классика славянского поста. Готовая свёкла; без масла.',
      'Παντζάρια, άσπρα φασόλια, σκόρδο και ξίδι — κλασικό νηστίσιμο πιάτο. Έτοιμα παντζάρια· χωρίς λάδι.',
    ),
    ingredients: lines(
      [
        '4 medium cooked beets, peeled and diced (~500 g)',
        '1 can (400 g) white beans, drained and rinsed',
        '2 garlic cloves, minced or grated',
        '3 tbsp red wine vinegar or apple cider vinegar',
        '½ tsp fine salt, plus more to taste',
        'Freshly ground black pepper',
        '½ small red onion, very thinly sliced',
        '3 tbsp chopped fresh dill (or parsley)',
      ],
      [
        '4 средние варёные свёклы, кубиками (~500 г)',
        '1 банка (400 г) белой фасоли, промытой',
        '2 зубчика чеснока, измельчённых',
        '3 ст.л. винного или яблочного уксуса',
        '½ ч.л. соли',
        'Свежемолотый чёрный перец',
        '½ красной луковицы тонкими полукольцами',
        '3 ст.л. укропа (или петрушки)',
      ],
      [
        '4 μέτρια βραστά παντζάρια σε κύβους (~500 γρ.)',
        '1 κονσέρβα (400 γρ.) άσπρα φασόλια, στραγγισμένα',
        '2 σκελίδες σκόρδο τριμμένο',
        '3 κ.σ. ξίδι κόκκινου κρασιού ή μήλου',
        '½ κ.γ. αλάτι',
        'Φρεσκοτριμμένο πιπέρι',
        '½ κόκκινο κρεμμύδι σε λεπτές φέτες',
        '3 κ.σ. άνηθο (ή μαϊντανό)',
      ],
    ),
    steps: lines(
      [
        'In a large bowl, whisk vinegar, garlic, salt, and pepper.',
        'Add beets, beans, and onion. Toss gently until coated.',
        'Fold in dill. Taste and adjust salt or vinegar.',
        'Rest 10 minutes if you can — flavours meld. Serve cold (~200 g per person).',
      ],
      [
        'В миске смешайте уксус, чеснок, соль и перец.',
        'Добавьте свёклу, фасоль и лук. Аккуратно перемешайте.',
        'Всыпьте укроп. По вкусу — соль или уксус.',
        'Подержите 10 мин. Подавайте холодным (~200 г на порцию).',
      ],
      [
        'Σε μπολ ανακατέψτε ξίδι, σκόρδο, αλάτι και πιπέρι.',
        'Προσθέστε παντζάρια, φασόλια και κρεμμύδι. Ανακατέψτε απαλά.',
        'Ρίξτε άνηθο. Δοκιμάστε αλάτι/ξίδι.',
        'Αφήστε 10 λεπτά. Σερβίρετε κρύο (~200 γρ. ανά μερίδα).',
      ],
    ),
    tips: lines(
      [
        'Vacuum-packed cooked beets make this a 10-minute dish; avoid heavily pickled jars.',
        'Keeps 2–3 days in the fridge — even better the next day.',
      ],
      [
        'Вакуумная варёная свёкла — блюдо за 10 мин; не берите сильно маринованную.',
        'Хранится 2–3 дня в холодильнике — назавтра ещё вкуснее.',
      ],
      [
        'Έτοιμα παντζάρια σε κενό — έτοιμο σε 10 λεπτά· αποφύγετε πολύ ξιδάτα.',
        'Κρατάει 2–3 μέρες στο ψυγείο — καλύτερο την επόμενη μέρα.',
      ],
    ),
  }),
  R({
    id: 'spinach-rice',
    level: 'strict',
    category: 'main',
    difficulty: 'easy',
    prepMinutes: 10,
    cookMinutes: 30,
    servings: 4,
    servingSize: L('1 plate (~280 g)', '1 тарелка (~280 г)', '1 πιάτο (~280 γρ.)'),
    title: L('Spinach rice (spanakorizo-style)', 'Рис со шпинатом', 'Σπανακόρυζο χωρίς λάδι'),
    summary: L(
      'Greek-style spinach and rice simmered with lemon and dill — water-sautéed onion, no oil.',
      'Рис со шпинатом, лимоном и укропом по-гречески — лук на воде, без масла.',
      'Σπανάκι με ρύζι, λεμόνι και άνηθο — κρεμμύδι σε νερό, χωρίς λάδι.',
    ),
    ingredients: lines(
      [
        '1 large onion, finely chopped',
        '2 garlic cloves, minced',
        '400 g fresh spinach (or 300 g frozen, thawed and squeezed)',
        '1 cup (200 g) medium-grain rice, rinsed',
        '3 cups (720 ml) water or vegetable broth',
        'Juice of 1 lemon, plus wedges to serve',
        '3 tbsp chopped fresh dill (or 1 tsp dried)',
        '1 tsp fine salt',
        'Freshly ground black pepper',
      ],
      [
        '1 крупная луковица мелко',
        '2 зубчика чеснока',
        '400 г свежего шпината (или 300 г замороженного, отжатого)',
        '1 стакан (200 г) риса, промытого',
        '3 стакана (720 мл) воды или овощного бульона',
        'Сок 1 лимона + дольки',
        '3 ст.л. укропа (или 1 ч.л. сушёного)',
        '1 ч.л. соли',
        'Чёрный перец',
      ],
      [
        '1 μεγάλο κρεμμύδι ψιλοκομμένο',
        '2 σκελίδες σκόρδο',
        '400 γρ. φρέσκο σπανάκι (ή 300 γρ. κατεψυγμένο, στραγγισμένο)',
        '1 φλ. (200 γρ.) ρύζι, ξεπλυμένο',
        '3 φλ. (720 ml) νερό ή ζωμό λαχανικών',
        'Χυμός 1 λεμονιού + φέτες',
        '3 κ.σ. άνηθο (ή 1 κ.γ. ξερό)',
        '1 κ.γ. αλάτι',
        'Πιπέρι',
      ],
    ),
    steps: lines(
      [
        'In a wide pot, soften onion with a splash of water over medium heat 4–5 minutes, stirring. Add garlic for 30 seconds.',
        'Add spinach; cook until wilted (or warmed through if frozen), 2–3 minutes.',
        'Stir in rice, salt, pepper, and water/broth. Bring to a simmer.',
        'Cover and cook on low 18–22 minutes until rice is tender and liquid absorbed. Add a splash of water if dry.',
        'Off heat, fold in lemon juice and dill. Rest covered 5 minutes. Serve ~280 g with lemon wedges.',
      ],
      [
        'В широкой кастрюле размягчите лук с ложкой воды 4–5 мин. Добавьте чеснок на 30 сек.',
        'Всыпьте шпинат; 2–3 мин до мягкости.',
        'Добавьте рис, соль, перец и воду/бульон. Доведите до кипения.',
        'Накройте и варите на малом огне 18–22 мин. При необходимости долейте воды.',
        'Снимите с огня, добавьте лимон и укроп. 5 мин под крышкой. Порция ~280 г.',
      ],
      [
        'Σε φαρδιά κατσαρόλα μαλακώστε το κρεμμύδι με λίγο νερό 4–5 λεπτά. Σκόρδο 30 δεύτερα.',
        'Προσθέστε σπανάκι· 2–3 λεπτά μέχρι μαραθεί.',
        'Ρύζι, αλάτι, πιπέρι και νερό/ζωμό. Σιγοβράστε.',
        'Σκεπάστε σε χαμηλή φωτιά 18–22 λεπτά. Αν στεγνώσει, λίγο νερό.',
        'Κατεβάστε, λεμόνι και άνηθο. 5 λεπτά σκεπασμένο. Μερίδα ~280 γρ.',
      ],
    ),
    tips: lines(
      [
        'Frozen spinach works well — squeeze out excess water before adding.',
        'For a thicker pot, use 2½ cups liquid; for soupier, use 3½.',
      ],
      [
        'Замороженный шпинат — хорошо отожмите воду.',
        'Для густого — 2½ стакана жидкости; для пожиже — 3½.',
      ],
      [
        'Κατεψυγμένο σπανάκι — στύψτε καλά το νερό.',
        'Για πιο πηχτό: 2½ φλ. υγρό· για πιο αραιό: 3½.',
      ],
    ),
  }),
  R({
    id: 'chickpea-soup',
    level: 'strict',
    category: 'soup',
    difficulty: 'easy',
    prepMinutes: 10,
    cookMinutes: 35,
    servings: 4,
    servingSize: L('1 bowl (~400 ml)', '1 миска (~400 мл)', '1 μπολ (~400 ml)'),
    title: L('Lemon chickpea soup', 'Гороховый суп из нута с лимоном', 'Ρεβιθόσουπα με λεμόνι'),
    summary: L(
      'Simple revithosoupa-style chickpeas with onion, bay, and plenty of lemon — no oil.',
      'Простой суп из нута с луком, лавром и лимоном — без масла.',
      'Απλή ρεβιθόσουπα με κρεμμύδι, δαφνόφυλλο και λεμόνι — χωρίς λάδι.',
    ),
    ingredients: lines(
      [
        '1 large onion, chopped',
        '2 garlic cloves, minced',
        '2 cans (400 g each) chickpeas, drained and rinsed — or 3 cups cooked',
        '5 cups (1.2 L) water or vegetable broth',
        '1 bay leaf',
        '1 tsp ground cumin (optional)',
        '1 tsp fine salt',
        'Juice of 1½–2 lemons',
        'Fresh parsley, chopped, to serve',
      ],
      [
        '1 крупная луковица',
        '2 зубчика чеснока',
        '2 банки (по 400 г) нута или 3 стакана варёного',
        '5 стаканов (1,2 л) воды или бульона',
        '1 лавровый лист',
        '1 ч.л. тмина (по желанию)',
        '1 ч.л. соли',
        'Сок 1½–2 лимонов',
        'Петрушка для подачи',
      ],
      [
        '1 μεγάλο κρεμμύδι',
        '2 σκελίδες σκόρδο',
        '2 κονσέρβες (400 γρ.) ρεβίθια ή 3 φλ. βραστά',
        '5 φλ. (1,2 L) νερό ή ζωμό',
        '1 δαφνόφυλλο',
        '1 κ.γ. κύμινο (προαιρετικά)',
        '1 κ.γ. αλάτι',
        'Χυμός 1½–2 λεμονιών',
        'Μαϊντανός για σερβίρισμα',
      ],
    ),
    steps: lines(
      [
        'Soften onion in a splash of water 4–5 minutes. Add garlic 30 seconds.',
        'Add chickpeas, water/broth, bay, cumin if using, and salt. Bring to a boil.',
        'Simmer uncovered 25–30 minutes. Mash a cup of chickpeas against the pot wall for body, or blend briefly.',
        'Remove bay. Stir in lemon juice off heat. Taste — it should be bright and savoury.',
        'Ladle ~400 ml per bowl. Top with parsley.',
      ],
      [
        'Размягчите лук с водой 4–5 мин. Чеснок 30 сек.',
        'Нут, вода/бульон, лавр, тмин и соль. Вскипятите.',
        'Варите без крышки 25–30 мин. Разомните часть нута для густоты.',
        'Уберите лавр. Влейте лимонный сок. Попробуйте.',
        'Порция ~400 мл. Сверху петрушка.',
      ],
      [
        'Μαλακώστε κρεμμύδι με νερό 4–5 λεπτά. Σκόρδο 30 δεύτερα.',
        'Ρεβίθια, νερό/ζωμό, δάφνη, κύμινο και αλάτι. Βράστε.',
        'Σιγοβράστε 25–30 λεπτά. Πολτοποιήστε λίγα ρεβίθια για σώμα.',
        'Βγάλετε τη δάφνη. Λεμόνι εκτός φωτιάς.',
        'Μερίδα ~400 ml. Μαϊντανός από πάνω.',
      ],
    ),
    tips: lines(
      [
        'Dried chickpeas: soak overnight, boil until tender (~1 hour), then continue from step 2.',
        'Extra lemon at the table wakes it up — Lenten chickpea soup loves acid.',
      ],
      [
        'Сухой нут: замочите на ночь, отварите (~1 ч), затем со шага 2.',
        'Дополнительный лимон за столом — постная ρεβιθόσουπα любит кислоту.',
      ],
      [
        'Ξερά ρεβίθια: μούλιασμα όλο το βράδυ, βράσιμο (~1 ώρα), μετά από το βήμα 2.',
        'Έξτρα λεμόνι στο τραπέζι — η ρεβιθόσουπα αγαπά την οξύτητα.',
      ],
    ),
  }),
  R({
    id: 'mushroom-barley',
    level: 'strict',
    category: 'soup',
    difficulty: 'medium',
    prepMinutes: 15,
    cookMinutes: 45,
    servings: 4,
    servingSize: L('1 bowl (~400 ml)', '1 миска (~400 мл)', '1 μπολ (~400 ml)'),
    title: L('Mushroom barley soup', 'Грибной суп с перловкой', 'Σούπα μανιταριών με κριθάρι'),
    summary: L(
      'Hearty Eastern European barley and mushrooms — onion softened in water, no oil.',
      'Сытный грибной суп с перловкой — лук на воде, без масла.',
      'Χορταστική σούπα με κριθάρι και μανιτάρια — κρεμμύδι σε νερό, χωρίς λάδι.',
    ),
    ingredients: lines(
      [
        '¾ cup (150 g) pearl barley, rinsed',
        '1 large onion, diced',
        '2 carrots, diced',
        '2 celery stalks, diced (optional)',
        '400 g mushrooms, sliced (button, cremini, or mixed)',
        '6 cups (1.4 L) water or vegetable broth',
        '2 bay leaves',
        '1 tsp fine salt',
        'Freshly ground black pepper',
        '2 tbsp chopped parsley or dill',
        'Lemon wedges, to serve',
      ],
      [
        '¾ стакана (150 г) перловки, промытой',
        '1 крупная луковица',
        '2 моркови кубиками',
        '2 стебля сельдерея (по желанию)',
        '400 г грибов ломтиками',
        '6 стаканов (1,4 л) воды или бульона',
        '2 лавровых листа',
        '1 ч.л. соли',
        'Чёрный перец',
        '2 ст.л. петрушки или укропа',
        'Лимон для подачи',
      ],
      [
        '¾ φλ. (150 γρ.) κριθάρι, ξεπλυμένο',
        '1 μεγάλο κρεμμύδι',
        '2 καρότα σε κύβους',
        '2 κλωνάρια σέλερι (προαιρετικά)',
        '400 γρ. μανιτάρια σε φέτες',
        '6 φλ. (1,4 L) νερό ή ζωμό',
        '2 δαφνόφυλλα',
        '1 κ.γ. αλάτι',
        'Πιπέρι',
        '2 κ.σ. μαϊντανό ή άνηθο',
        'Λεμόνι για σερβίρισμα',
      ],
    ),
    steps: lines(
      [
        'Soften onion, carrot, and celery in a splash of water 5–6 minutes, stirring.',
        'Add mushrooms; cook until they release liquid and shrink, 6–8 minutes.',
        'Add barley, water/broth, bay, salt, and pepper. Bring to a boil.',
        'Simmer partly covered 35–40 minutes until barley is tender. Add water if too thick.',
        'Remove bay. Stir in herbs. Serve ~400 ml with lemon.',
      ],
      [
        'Размягчите лук, морковь и сельдерей с водой 5–6 мин.',
        'Добавьте грибы; 6–8 мин, пока не пустят сок.',
        'Перловка, вода/бульон, лавр, соль, перец. Вскипятите.',
        'Варите под неплотной крышкой 35–40 мин. Долейте воду при необходимости.',
        'Уберите лавр. Зелень. Порция ~400 мл с лимоном.',
      ],
      [
        'Μαλακώστε κρεμμύδι, καρότο, σέλερι με νερό 5–6 λεπτά.',
        'Μανιτάρια· 6–8 λεπτά μέχρι να βγάλουν υγρά.',
        'Κριθάρι, νερό/ζωμό, δάφνη, αλάτι, πιπέρι. Βράστε.',
        'Σιγοβράστε μισοσκεπασμένα 35–40 λεπτά. Νερό αν χρειάζεται.',
        'Βγάλετε τη δάφνη. Βότανα. Μερίδα ~400 ml με λεμόνι.',
      ],
    ),
    tips: lines(
      [
        'Pearl barley softens faster than hulled; if using hulled, add 15–20 minutes.',
        'Dried mushrooms (a handful, soaked) deepen the broth — add soaking liquid too.',
      ],
      [
        'Перловка быстрее шелушёной; шелушёной добавьте 15–20 мин.',
        'Сушёные грибы (горсть, замоченные) усиливают бульон — вместе с настоем.',
      ],
      [
        'Το μαργαριταρένιο κριθάρι μαλακώνει πιο γρήγορα· το ολόκληρο θέλει +15–20 λεπτά.',
        'Αποξηραμένα μανιτάρια βαθαίνουν τον ζωμό — μαζί με το νερό μουλιάσματος.',
      ],
    ),
  }),
  R({
    id: 'stuffed-peppers',
    level: 'strict',
    category: 'main',
    difficulty: 'medium',
    prepMinutes: 25,
    cookMinutes: 50,
    servings: 4,
    servingSize: L('1–2 peppers', '1–2 перца', '1–2 πιπεριές'),
    title: L('Stuffed peppers with rice', 'Перцы фаршированные рисом', 'Γεμιστές πιπεριές με ρύζι'),
    summary: L(
      'Oven-baked peppers filled with rice, tomato, and herbs — a Lenten yemista without oil.',
      'Перцы с рисом, томатом и зеленью в духовке — постные «гемиста» без масла.',
      'Πιπεριές γεμιστές με ρύζι, ντομάτα και βότανα — νηστίσιμα γεμιστά χωρίς λάδι.',
    ),
    ingredients: lines(
      [
        '4 large bell peppers, tops cut, seeds removed',
        '1 cup (200 g) medium-grain rice, rinsed',
        '1 large onion, finely chopped',
        '2 garlic cloves, minced',
        '2 ripe tomatoes, grated or finely chopped (or 200 ml passata)',
        '2 tbsp tomato paste',
        '3 tbsp chopped parsley',
        '1 tsp dried oregano or mint',
        '1 tsp fine salt',
        'Freshly ground black pepper',
        '1½ cups (360 ml) water or vegetable broth, plus more for the pan',
      ],
      [
        '4 крупных перца, без семян',
        '1 стакан (200 г) риса',
        '1 крупная луковица',
        '2 зубчика чеснока',
        '2 спелых помидора натёртых (или 200 мл пассаты)',
        '2 ст.л. томатной пасты',
        '3 ст.л. петрушки',
        '1 ч.л. орегано или мяты',
        '1 ч.л. соли',
        'Чёрный перец',
        '1½ стакана (360 мл) воды/бульона + для формы',
      ],
      [
        '4 μεγάλες πιπεριές, χωρίς σπόρους',
        '1 φλ. (200 γρ.) ρύζι',
        '1 μεγάλο κρεμμύδι',
        '2 σκελίδες σκόρδο',
        '2 ώριμες ντομάτες τριμμένες (ή 200 ml passata)',
        '2 κ.σ. πελτέ',
        '3 κ.σ. μαϊντανό',
        '1 κ.γ. ρίγανη ή δυόσμο',
        '1 κ.γ. αλάτι',
        'Πιπέρι',
        '1½ φλ. (360 ml) νερό/ζωμό + για το ταψί',
      ],
    ),
    steps: lines(
      [
        'Heat oven to 190°C / 375°F. Soften onion in a splash of water 5 minutes; add garlic 30 seconds.',
        'Stir in rice, tomato, tomato paste, herbs, salt, pepper, and 1½ cups liquid. Simmer 5 minutes — rice stays undercooked.',
        'Stand peppers in a baking dish. Fill with rice mixture. Cap with pepper tops if you kept them.',
        'Pour ~1 cm water or broth into the dish around the peppers. Cover tightly with foil.',
        'Bake 40–45 minutes until peppers are soft and rice is tender. Uncover last 10 minutes if you want lightly browned tops. Rest 5 minutes before serving.',
      ],
      [
        'Духовка 190°C. Лук с водой 5 мин; чеснок 30 сек.',
        'Рис, томат, паста, зелень, соль, перец и 1½ стакана жидкости. 5 мин — рис полусырой.',
        'Поставьте перцы в форму, начините. Накройте «крышечками».',
        'Налейте ~1 см воды/бульона на дно. Плотно закройте фольгой.',
        'Пеките 40–45 мин. Последние 10 мин без фольги по желанию. 5 мин отдохнуть.',
      ],
      [
        'Φούρνος 190°C. Κρεμμύδι με νερό 5 λεπτά· σκόρδο 30 δεύτερα.',
        'Ρύζι, ντομάτα, πελτές, βότανα, αλάτι, πιπέρι και 1½ φλ. υγρό. 5 λεπτά — ρύζι μισοψημένο.',
        'Στήστε τις πιπεριές σε ταψί, γεμίστε. Βάλτε τα «καπάκια».',
        'Ρίξτε ~1 εκ. νερό/ζωμό στον πάτο. Καλύψτε με αλουμινόχαρτο.',
        'Ψήστε 40–45 λεπτά. Τα τελευταία 10 χωρίς αλουμινόχαρτο αν θέλετε. Ξεκούραση 5 λεπτά.',
      ],
    ),
    tips: lines(
      [
        'Any colour pepper works; red and yellow are sweeter.',
        'Leftover filling bakes well in hollowed tomatoes or zucchini.',
      ],
      [
        'Любой цвет перца; красный и жёлтый слаще.',
        'Остаток начинки — в помидоры или кабачки.',
      ],
      [
        'Οποιοδήποτε χρώμα πιπεριάς· κόκκινη και κίτρινη πιο γλυκές.',
        'Το υπόλοιπο γέμισμα πάει σε ντομάτες ή κολοκυθάκια.',
      ],
    ),
  }),
  R({
    id: 'split-pea-porridge',
    level: 'strict',
    category: 'main',
    difficulty: 'easy',
    prepMinutes: 10,
    cookMinutes: 50,
    servings: 4,
    servingSize: L('1 bowl (~300 g)', '1 миска (~300 г)', '1 μπολ (~300 γρ.)'),
    title: L('Split pea porridge', 'Гороховая каша', 'Φακές κίτρινες (πουρές)'),
    summary: L(
      'Creamy yellow split peas with onion and bay — thick Lenten porridge, no oil.',
      'Нежный гороховый пудинг с луком и лавром — густая постная каша без масла.',
      'Κρεμώδεις κίτρινες φακές με κρεμμύδι και δάφνη — πηχτός νηστίσιμος πουρές χωρίς λάδι.',
    ),
    ingredients: lines(
      [
        '2 cups (400 g) yellow split peas, rinsed',
        '1 large onion, chopped',
        '1 carrot, diced (optional)',
        '6 cups (1.4 L) water',
        '2 bay leaves',
        '1 tsp fine salt',
        'Freshly ground black pepper',
        'Lemon wedges and chopped parsley, to serve',
      ],
      [
        '2 стакана (400 г) жёлтого колотого гороха',
        '1 крупная луковица',
        '1 морковь (по желанию)',
        '6 стаканов (1,4 л) воды',
        '2 лавровых листа',
        '1 ч.л. соли',
        'Чёрный перец',
        'Лимон и петрушка для подачи',
      ],
      [
        '2 φλ. (400 γρ.) κίτρινες φακές, ξεπλυμένες',
        '1 μεγάλο κρεμμύδι',
        '1 καρότο (προαιρετικά)',
        '6 φλ. (1,4 L) νερό',
        '2 δαφνόφυλλα',
        '1 κ.γ. αλάτι',
        'Πιπέρι',
        'Λεμόνι και μαϊντανός',
      ],
    ),
    steps: lines(
      [
        'Soften onion (and carrot) in a splash of water 4–5 minutes.',
        'Add split peas, water, bay, and salt. Bring to a boil; skim foam if needed.',
        'Simmer on low, partly covered, 40–50 minutes, stirring often so it does not stick. Add water if too thick.',
        'When peas collapse into a porridge, remove bay. Mash or blend briefly for smoother texture.',
        'Season with pepper. Serve ~300 g with lemon and parsley.',
      ],
      [
        'Лук (и морковь) с водой 4–5 мин.',
        'Горох, вода, лавр, соль. Вскипятите; снимите пену.',
        'На малом огне 40–50 мин, часто мешая. Долейте воду при необходимости.',
        'Когда горох разварится, уберите лавр. При желании слегка пробейте блендером.',
        'Перец. Порция ~300 г с лимоном и петрушкой.',
      ],
      [
        'Κρεμμύδι (και καρότο) με νερό 4–5 λεπτά.',
        'Φακές, νερό, δάφνη, αλάτι. Βράστε· αφρίστε αν χρειάζεται.',
        'Χαμηλή φωτιά 40–50 λεπτά, συχνά ανακάτεμα. Νερό αν στεγνώσει.',
        'Όταν λιώσουν, βγάλετε τη δάφνη. Πολτοποιήστε λίγο αν θέλετε.',
        'Πιπέρι. Μερίδα ~300 γρ. με λεμόνι και μαϊντανό.',
      ],
    ),
    tips: lines(
      [
        'Stir near the end — split peas catch easily on the bottom.',
        'Leftovers thicken in the fridge; loosen with hot water when reheating.',
      ],
      [
        'К концу помешивайте — горох пригорает.',
        'В холодильнике густеет; при разогреве разбавьте горячей водой.',
      ],
      [
        'Στο τέλος ανακατεύετε συχνά — κολλάνε εύκολα.',
        'Στο ψυγείο πήζει· ζεσταίνοντας αραιώστε με ζεστό νερό.',
      ],
    ),
  }),
  R({
    id: 'lenten-borscht',
    level: 'strict',
    category: 'soup',
    difficulty: 'medium',
    prepMinutes: 20,
    cookMinutes: 40,
    servings: 6,
    servingSize: L('1 bowl (~350 ml)', '1 миска (~350 мл)', '1 μπολ (~350 ml)'),
    title: L('Lenten beet borscht', 'Постный борщ', 'Νηστίσιμο μπορς'),
    summary: L(
      'Ruby beet soup with cabbage, potato, and tomato — monastic-style, no oil or sour cream.',
      'Свекольный борщ с капустой, картофелем и томатом — постный, без масла и сметаны.',
      'Κόκκινη σούπα παντζαριού με λάχανο, πατάτα και ντομάτα — χωρίς λάδι και κρέμα.',
    ),
    ingredients: lines(
      [
        '1 large onion, diced',
        '2 carrots, grated or diced',
        '2 medium beets, peeled and grated (~300 g)',
        '2 medium potatoes, diced',
        '¼ small head cabbage, shredded (~200 g)',
        '2 tbsp tomato paste',
        '1 can (400 g) diced tomatoes, or 2 fresh tomatoes chopped',
        '7 cups (1.7 L) water or vegetable broth',
        '2 bay leaves',
        '2 tbsp vinegar or lemon juice',
        '1 tsp fine salt, plus more to taste',
        'Fresh dill and black pepper, to serve',
      ],
      [
        '1 крупная луковица',
        '2 моркови',
        '2 средние свёклы натёртые (~300 г)',
        '2 средние картофелины',
        '¼ небольшого кочана капусты (~200 г)',
        '2 ст.л. томатной пасты',
        '1 банка (400 г) томатов или 2 свежих',
        '7 стаканов (1,7 л) воды или бульона',
        '2 лавровых листа',
        '2 ст.л. уксуса или лимонного сока',
        '1 ч.л. соли',
        'Укроп и перец для подачи',
      ],
      [
        '1 μεγάλο κρεμμύδι',
        '2 καρότα',
        '2 μέτρια παντζάρια τριμμένα (~300 γρ.)',
        '2 μέτριες πατάτες',
        '¼ μικρό λάχανο (~200 γρ.)',
        '2 κ.σ. πελτέ',
        '1 κονσέρβα (400 γρ.) ντομάτα ή 2 φρέσκες',
        '7 φλ. (1,7 L) νερό ή ζωμό',
        '2 δαφνόφυλλα',
        '2 κ.σ. ξίδι ή χυμό λεμονιού',
        '1 κ.γ. αλάτι',
        'Άνηθος και πιπέρι',
      ],
    ),
    steps: lines(
      [
        'Soften onion and carrot in a splash of water 5 minutes. Add beet; cook 5 minutes more, adding water as needed so nothing sticks.',
        'Stir in tomato paste 1 minute. Add water/broth, potatoes, tomatoes, bay, and salt. Bring to a boil.',
        'Simmer 15 minutes. Add cabbage; cook 10–15 minutes more until vegetables are tender.',
        'Stir in vinegar or lemon — this keeps the colour bright. Remove bay. Taste for salt.',
        'Serve ~350 ml topped with dill and pepper.',
      ],
      [
        'Лук и морковь с водой 5 мин. Свёкла ещё 5 мин, подливая воду.',
        'Томатная паста 1 мин. Вода/бульон, картофель, томаты, лавр, соль. Вскипятите.',
        '15 мин. Капуста; ещё 10–15 мин до мягкости.',
        'Уксус или лимон — цвет ярче. Уберите лавр.',
        'Порция ~350 мл с укропом и перцем.',
      ],
      [
        'Κρεμμύδι και καρότο με νερό 5 λεπτά. Παντζάρι άλλα 5, με λίγο νερό.',
        'Πελτές 1 λεπτό. Νερό/ζωμό, πατάτες, ντομάτα, δάφνη, αλάτι. Βράστε.',
        '15 λεπτά. Λάχανο· ακόμη 10–15 μέχρι μαλακά.',
        'Ξίδι ή λεμόνι — κρατά το χρώμα. Βγάλετε τη δάφνη.',
        'Μερίδα ~350 ml με άνηθο και πιπέρι.',
      ],
    ),
    tips: lines(
      [
        'Acid at the end keeps beets ruby-red instead of dull brown.',
        'Even better the next day; reheats gently on the stove.',
      ],
      [
        'Кислота в конце сохраняет яркий цвет свёклы.',
        'На следующий день ещё вкуснее; разогревайте на плите.',
      ],
      [
        'Η οξύτητα στο τέλος κρατά το κόκκινο χρώμα.',
        'Καλύτερο την επόμενη μέρα· ζεστάνετε απαλά στην κατσαρόλα.',
      ],
    ),
  }),
  R({
    id: 'tomato-orzo',
    level: 'strict',
    category: 'main',
    difficulty: 'easy',
    prepMinutes: 8,
    cookMinutes: 20,
    servings: 4,
    servingSize: L('1 bowl (~280 g)', '1 миска (~280 г)', '1 μπολ (~280 γρ.)'),
    title: L('Tomato orzo pot', 'Орзо в томате', 'Κριθαράκι με ντομάτα'),
    summary: L(
      'One-pot orzo (kritharaki) simmered in tomato and onion — quick Lenten comfort, no oil.',
      'Орзо (крифараки) в томате с луком — быстрый постный ужин без масла.',
      'Κριθαράκι σε ντομάτα με κρεμμύδι — γρήγορο νηστίσιμο, χωρίς λάδι.',
    ),
    ingredients: lines(
      [
        '1 onion, finely chopped',
        '2 garlic cloves, minced',
        '1½ cups (300 g) orzo / kritharaki',
        '3 tbsp tomato paste',
        '1 can (400 g) crushed tomatoes',
        '4 cups (960 ml) water or vegetable broth',
        '1 tsp dried oregano',
        '1 tsp fine salt',
        'Freshly ground black pepper',
        'Fresh basil or parsley, to serve',
      ],
      [
        '1 луковица',
        '2 зубчика чеснока',
        '1½ стакана (300 г) орзо / крифараки',
        '3 ст.л. томатной пасты',
        '1 банка (400 г) измельчённых томатов',
        '4 стакана (960 мл) воды или бульона',
        '1 ч.л. орегано',
        '1 ч.л. соли',
        'Чёрный перец',
        'Базилик или петрушка',
      ],
      [
        '1 κρεμμύδι',
        '2 σκελίδες σκόρδο',
        '1½ φλ. (300 γρ.) κριθαράκι',
        '3 κ.σ. πελτέ',
        '1 κονσέρβα (400 γρ.) λιωμένη ντομάτα',
        '4 φλ. (960 ml) νερό ή ζωμό',
        '1 κ.γ. ρίγανη',
        '1 κ.γ. αλάτι',
        'Πιπέρι',
        'Βασιλικός ή μαϊντανός',
      ],
    ),
    steps: lines(
      [
        'Soften onion in a splash of water 4 minutes; add garlic 30 seconds.',
        'Stir in tomato paste 1 minute. Add orzo, crushed tomatoes, water/broth, oregano, salt, and pepper.',
        'Bring to a simmer, stirring so orzo does not clump. Cook 12–15 minutes until pasta is tender and sauce thickens.',
        'Add a splash of water if it gets too dry before the orzo is done.',
        'Rest 2 minutes. Serve ~280 g with herbs.',
      ],
      [
        'Лук с водой 4 мин; чеснок 30 сек.',
        'Томатная паста 1 мин. Орзо, томаты, вода/бульон, орегано, соль, перец.',
        'Томите 12–15 мин, помешивая, до готовности и густоты.',
        'Если сухо — долейте воды.',
        '2 мин отдохнуть. Порция ~280 г с зеленью.',
      ],
      [
        'Κρεμμύδι με νερό 4 λεπτά· σκόρδο 30 δεύτερα.',
        'Πελτές 1 λεπτό. Κριθαράκι, ντομάτα, νερό/ζωμό, ρίγανη, αλάτι, πιπέρι.',
        'Σιγοβράστε 12–15 λεπτά, ανακατεύοντας, μέχρι μαλακό και πηχτό.',
        'Αν στεγνώσει, λίγο νερό.',
        'Ξεκούραση 2 λεπτά. Μερίδα ~280 γρ. με βότανα.',
      ],
    ),
    tips: lines(
      [
        'Any small pasta works — ditalini or broken spaghetti in a pinch.',
        'Stir often in the last minutes; orzo loves to stick.',
      ],
      [
        'Подойдёт любая мелкая паста — диталини или ломаные спагетти.',
        'В конце часто мешайте — орзо прилипает.',
      ],
      [
        'Οποιοδήποτε μικρό ζυμαρικό — ditalini ή σπασμένα σπαγγέτι.',
        'Στο τέλος ανακατεύετε συχνά· κολλάει εύκολα.',
      ],
    ),
  }),
  R({
    id: 'banana-oat-cookies',
    level: 'strict',
    category: 'sweet',
    difficulty: 'easy',
    prepMinutes: 10,
    cookMinutes: 15,
    servings: 12,
    servingSize: L('1 cookie (~35 g)', '1 печенье (~35 г)', '1 μπισκότο (~35 γρ.)'),
    title: L('Banana oat cookies', 'Овсяное печенье с бананом', 'Μπισκότα βρώμης με μπανάνα'),
    summary: L(
      'Soft Lenten cookies from ripe banana, oats, and raisins — no oil, eggs, or dairy.',
      'Мягкое постное печенье из банана, овсянки и изюма — без масла, яиц и молока.',
      'Απαλά νηστίσιμα μπισκότα από μπανάνα, βρώμη και σταφίδες — χωρίς λάδι, αυγά ή γάλα.',
    ),
    ingredients: lines(
      [
        '2 very ripe bananas (~240 g peeled), mashed',
        '1½ cups (135 g) rolled oats',
        '⅓ cup (50 g) raisins or chopped dried fruit',
        '1 tsp ground cinnamon',
        '½ tsp vanilla extract (optional)',
        'Pinch of fine salt',
        'Optional: 2 tbsp chopped walnuts or sunflower seeds',
      ],
      [
        '2 очень спелых банана (~240 г), размятых',
        '1½ стакана (135 г) овсяных хлопьев',
        '⅓ стакана (50 г) изюма или сухофруктов',
        '1 ч.л. корицы',
        '½ ч.л. ванили (по желанию)',
        'Щепотка соли',
        'По желанию: 2 ст.л. грецких орехов или семян',
      ],
      [
        '2 πολύ ώριμες μπανάνες (~240 γρ.), λιωμένες',
        '1½ φλ. (135 γρ.) νιφάδες βρώμης',
        '⅓ φλ. (50 γρ.) σταφίδες ή ξερά φρούτα',
        '1 κ.γ. κανέλα',
        '½ κ.γ. βανίλια (προαιρετικά)',
        'Πιτσίλισμα αλάτι',
        'Προαιρετικά: 2 κ.σ. καρύδια ή σπόρους',
      ],
    ),
    steps: lines(
      [
        'Heat oven to 180°C / 350°F. Line a baking sheet with parchment (no oil needed).',
        'In a bowl, mash bananas until mostly smooth. Stir in oats, raisins, cinnamon, vanilla if using, salt, and optional nuts.',
        'Let the mixture sit 5 minutes so the oats hydrate — it should be thick and scoopable.',
        'Scoop ~12 mounds (about 2 tbsp each) onto the sheet. Flatten slightly with a spoon into cookie shapes.',
        'Bake 12–15 minutes until set and lightly golden at the edges. Cool on the sheet 5 minutes, then move to a rack. Makes 12 cookies (~35 g each).',
      ],
      [
        'Духовка 180°C. Противень застелите бумагой (масло не нужно).',
        'Разомните бананы. Добавьте овсянку, изюм, корицу, ваниль, соль и орехи.',
        'Подержите 5 мин — хлопья набухнут; масса должна быть густой.',
        'Выложите ~12 комочков (по ~2 ст.л.), слегка приплющите.',
        'Пеките 12–15 мин до золотистых краёв. 5 мин на противне, затем на решётку. 12 штук (~35 г).',
      ],
      [
        'Φούρνος 180°C. Ταψί με αντικολλητικό χαρτί (χωρίς λάδι).',
        'Λιώστε τις μπανάνες. Ανακατέψτε βρώμη, σταφίδες, κανέλα, βανίλια, αλάτι και ξηρούς καρπούς.',
        'Αφήστε 5 λεπτά να φουσκώσει η βρώμη — πηχτό μείγμα.',
        'Βάλτε ~12 μπάλες (~2 κ.σ.), πιέστε ελαφρά.',
        'Ψήστε 12–15 λεπτά μέχρι χρυσαφένια στις άκρες. 5 λεπτά στο ταψί, μετά σε σχάρα. 12 μπισκότα (~35 γρ.).',
      ],
    ),
    tips: lines(
      [
        'Spottier bananas = sweeter cookies and better binding.',
        'They stay soft; store airtight up to 3 days, or freeze.',
        'For crispier edges, bake 2–3 minutes longer and cool fully on a rack.',
      ],
      [
        'Чем спелее банан — тем слаще и лучше держится форма.',
        'Остаются мягкими; в закрытой банке до 3 дней или в морозилке.',
        'Для хрустящего края — +2–3 мин и полностью остудите на решётке.',
      ],
      [
        'Όσο πιο ώριμη η μπανάνα, τόσο πιο γλυκά και δεμένα.',
        'Μένουν μαλακά· σε κλειστό δοχείο έως 3 μέρες ή κατάψυξη.',
        'Για πιο τραγανές άκρες, +2–3 λεπτά και κρυώστε στη σχάρα.',
      ],
    ),
  }),
  R({
    id: 'palikaria',
    level: 'strict',
    category: 'salad',
    difficulty: 'medium',
    prepMinutes: 20,
    cookMinutes: 60,
    servings: 6,
    servingSize: L('1 bowl (~220 g)', '1 миска (~220 г)', '1 μπολ (~220 γρ.)'),
    title: L(
      'Palikaria (polysporia)',
      'Паликарья (полиспория)',
      'Παλικάρια (πολυσπόρια)',
    ),
    summary: L(
      'Boiled mixed beans and wheat berries with herbs and a bright lemon-vinegar dressing — the Greek Fotokolyva grain plate, oil-free.',
      'Смесь бобовых и пшеницы с зеленью и лимонно-уксусной заправкой — греческая полиспория / фотоколыва без масла.',
      'Μείγμα οσπρίων και σιταριού με μυρωδικά και λεμονάτη σάλτσα — πολυσπόρια / φωτοκόλλυβα χωρίς λάδι.',
    ),
    ingredients: lines(
      [
        '3 cups (about 500 g) mixed cooked beans — chickpeas, navy, black beans, black-eyed peas',
        '¼ cup (45 g) wheat berries, cooked until tender',
        '⅓ cup red onion, finely chopped',
        '¼ cup fresh dill, chopped',
        '¼ cup fresh parsley, chopped',
        'Dressing: 3 tbsp red wine vinegar + 2 tbsp lemon juice',
        '1 tsp lemon zest',
        '1 tsp dried oregano',
        '1 tsp mustard (optional)',
        'Fine salt and black pepper',
      ],
      [
        '3 стакана (~500 г) варёных бобовых — нут, белая, чёрная фасоль, чёрный глаз',
        '¼ стакана (45 г) пшеничных зёрен, сваренных до мягкости',
        '⅓ стакана красного лука',
        '¼ стакана укропа',
        '¼ стакана петрушки',
        'Заправка: 3 ст.л. винного уксуса + 2 ст.л. лимонного сока',
        '1 ч.л. цедры лимона',
        '1 ч.л. орегано',
        '1 ч.л. горчицы (по желанию)',
        'Соль и перец',
      ],
      [
        '3 φλ. (~500 γρ.) βρασμένα όσπρια — ρεβίθια, άσπρα, μαύρα, μαυρομάτικα',
        '¼ φλ. (45 γρ.) σιτάρι, βρασμένο',
        '⅓ φλ. κόκκινο κρεμμύδι',
        '¼ φλ. άνηθο',
        '¼ φλ. μαϊντανό',
        'Σάλτσα: 3 κ.σ. ξίδι κρασιού + 2 κ.σ. χυμό λεμονιού',
        '1 κ.γ. ξύσμα λεμονιού',
        '1 κ.γ. ρίγανη',
        '1 κ.γ. μουστάρδα (προαιρετικά)',
        'Αλάτι και πιπέρι',
      ],
    ),
    steps: lines(
      [
        'If using dried beans and wheat: soak overnight separately; boil until tender (wheat berries often need 45–60 minutes). Drain and cool slightly.',
        'Combine beans, wheat berries, onion, dill, and parsley in a large bowl.',
        'Whisk vinegar, lemon juice, zest, oregano, mustard if using, salt, and pepper. Pour over the salad and toss well.',
        'Taste and adjust lemon or salt. Rest 15 minutes so flavours settle. Serve ~220 g per person, warm or room temperature.',
      ],
      [
        'Сухие бобы и пшеницу замочите отдельно; варите до мягкости. Откиньте, слегка остудите.',
        'Смешайте бобы, пшеницу, лук, укроп и петрушку.',
        'Взбейте уксус, лимон, цедру, орегано, горчицу, соль, перец. Залейте и перемешайте.',
        'Попробуйте; дайте постоять 15 мин. Порция ~220 г, тёплым или комнатной температуры.',
      ],
      [
        'Αν χρησιμοποιείτε ξερά: μουλιάστε χωριστά· βράστε μέχρι μαλακά. Στραγγίξτε.',
        'Ανακατέψτε όσπρια, σιτάρι, κρεμμύδι, άνηθο, μαϊντανό.',
        'Χτυπήστε ξίδι, λεμόνι, ξύσμα, ρίγανη, μουστάρδα, αλάτι, πιπέρι. Περιχύστε.',
        'Δοκιμάστε· αφήστε 15 λεπτά. Μερίδα ~220 γρ., χλιαρό ή σε θερμοκρασία δωματίου.',
      ],
    ),
    tips: lines(
      [
        'Canned beans work — rinse well and skip the long boil.',
        'On wine-and-oil days, replace half the vinegar with 3–4 tbsp olive oil.',
        'Traditionally linked to the Presentation of Christ (Fotokolyva) and winter feast days.',
      ],
      [
        'Консервированные бобы — промойте и не варите долго.',
        'В дни с маслом — 3–4 ст.л. оливкового масла вместо части уксуса.',
        'Связано с Сретением (Фотоколыва) и зимними праздниками.',
      ],
      [
        'Κονσέρβα όσπρια — ξεπλύνετε καλά.',
        'Σε μέρες με λάδι, 3–4 κ.σ. ελαιόλαδο αντί για μέρος του ξιδιού.',
        'Συνδέεται με τα Εισόδια / Φωτοκόλλυβα και χειμωνιάτικες γιορτές.',
      ],
    ),
  }),
  R({
    id: 'gigantes-plaki',
    level: 'wine_oil',
    category: 'main',
    difficulty: 'medium',
    prepMinutes: 25,
    cookMinutes: 90,
    servings: 6,
    servingSize: L('1 portion (~250 g)', '1 порция (~250 г)', '1 μερίδα (~250 γρ.)'),
    title: L('Gigantes plaki', 'Гигантес плаки', 'Γίγαντες πλακί'),
    summary: L(
      'Giant white beans baked in tomato with carrot, celery, and leek — classic Greek wine-and-oil Lenten main.',
      'Крупная белая фасоль в томате с овощами — классическое греческое постное блюдо с маслом.',
      'Γίγαντες στον φούρνο με ντομάτα και λαχανικά — κλασικό νηστίσιμο με λάδι.',
    ),
    ingredients: lines(
      [
        '500 g dried gigantes (or large butter/lima beans), soaked overnight',
        '1 cup carrot, chopped',
        '1 leek (white part), chopped',
        '1 cup celery, chopped',
        '1 onion, sliced',
        '⅔ cup (160 ml) olive oil',
        '1⅔ cups (400 ml) tomato passata or sauce',
        '2 tbsp tomato paste',
        '1⅓ cups (320 ml) hot water',
        '1 tsp fine salt, ¼ tsp black pepper',
        'Optional: parsley or dill to finish',
      ],
      [
        '500 г сухой крупной фасоли (гигантес), замоченной на ночь',
        '1 стакан моркови',
        '1 лук-порей (белая часть)',
        '1 стакан сельдерея',
        '1 луковица кольцами',
        '⅔ стакана (160 мл) оливкового масла',
        '1⅔ стакана (400 мл) томатной пассы',
        '2 ст.л. томатной пасты',
        '1⅓ стакана (320 мл) горячей воды',
        '1 ч.л. соли, ¼ ч.л. перца',
        'По желанию: петрушка или укроп',
      ],
      [
        '500 γρ. ξερά γίγαντες, μουλιασμένα overnight',
        '1 φλ. καρότο',
        '1 πράσο (άσπρο μέρος)',
        '1 φλ. σέλινο',
        '1 κρεμμύδι σε φέτες',
        '⅔ φλ. (160 ml) ελαιόλαδο',
        '1⅔ φλ. (400 ml) πελτέ / passata',
        '2 κ.σ. πελτέ',
        '1⅓ φλ. (320 ml) καυτό νερό',
        '1 κ.γ. αλάτι, ¼ κ.γ. πιπέρι',
        'Προαιρετικά: μαϊντανός ή άνηθος',
      ],
    ),
    steps: lines(
      [
        'Boil soaked beans in fresh water until just tender but not falling apart (45–70 minutes depending on age). Drain.',
        'Heat oven to 180°C / 350°F. In a wide ovenproof pan, warm half the oil; soften onion, leek, carrot, and celery 8–10 minutes.',
        'Stir in tomato paste, then passata, hot water, remaining oil, salt, and pepper. Simmer 5 minutes.',
        'Fold in the drained beans. Bake uncovered 35–45 minutes until the sauce thickens and the top browns lightly.',
        'Rest 10 minutes. Serve ~250 g with bread or rice; scatter herbs if using.',
      ],
      [
        'Варите замоченную фасоль до мягкости (45–70 мин). Откиньте.',
        'Духовка 180°C. В половине масла обжарьте лук, порей, морковь, сельдерей 8–10 мин.',
        'Добавьте томатную пасту, пассу, воду, оставшееся масло, соль, перец. 5 мин.',
        'Вмешайте фасоль. Запекайте 35–45 мин без крышки до густоты.',
        '10 мин отдохнуть. Порция ~250 г с хлебом или рисом.',
      ],
      [
        'Βράστε τα μουλιασμένα φασόλια μέχρι μαλακά (45–70 λεπτά). Στραγγίξτε.',
        'Φούρνος 180°C. Με το μισό λάδι μαλακώστε κρεμμύδι, πράσο, καρότο, σέλινο 8–10 λεπτά.',
        'Πελτές, passata, νερό, υπόλοιπο λάδι, αλάτι, πιπέρι. 5 λεπτά.',
        'Βάλτε τα φασόλια. Ψήστε 35–45 λεπτά ακάλυπτα μέχρι να δέσει.',
        'Ξεκούραση 10 λεπτά. Μερίδα ~250 γρ. με ψωμί ή ρύζι.',
      ],
    ),
    tips: lines(
      [
        'No gigantes? Large butter beans or cannellini work; reduce boil time if canned.',
        'Sauce should coat the beans, not drown them — bake longer if still watery.',
      ],
      [
        'Нет гигантес — крупная белая фасоль; консервы — меньше варить.',
        'Соус должен обволакивать, не заливать — дольше в духовке, если жидко.',
      ],
      [
        'Χωρίς γίγαντες — μεγάλα φασόλια βουτύρου ή κανελίνι.',
        'Η σάλτσα να ντύνει, όχι να πνίγει — περισσότερο ψήσιμο αν είναι νερουλή.',
      ],
    ),
  }),
  R({
    id: 'briam',
    level: 'wine_oil',
    category: 'main',
    difficulty: 'easy',
    prepMinutes: 25,
    cookMinutes: 75,
    servings: 6,
    servingSize: L('1 portion (~280 g)', '1 порция (~280 г)', '1 μερίδα (~280 γρ.)'),
    title: L('Briam', 'Бриам', 'Μπριάμ'),
    summary: L(
      'Oven-roasted potatoes, zucchini, and carrot in tomato with mint and parsley — Greek summer tray bake for oil days.',
      'Запечённые картофель, кабачки и морковь в томате с мятой — греческая летняя запеканка с маслом.',
      'Πατάτες, κολοκυθάκια και καρότο στο φούρνο με ντομάτα και δυόσμο — καλοκαιρινό ταψί με λάδι.',
    ),
    ingredients: lines(
      [
        '6 medium potatoes, peeled and cut in wedges',
        '2 carrots, thick slices',
        '2 large zucchini, thick half-moons',
        '1 yellow onion + 1 cup chopped green onions',
        '1 cup chopped mint + 1 cup chopped parsley',
        '1 celery stalk with leaves, chopped',
        '2 garlic cloves, minced',
        '1⅓ cups (320 ml) tomato passata',
        '⅔ cup (160 ml) olive oil',
        '1 cup (240 ml) water',
        '1¼ tsp salt, ¼ tsp pepper, 3 bay leaves',
      ],
      [
        '6 средних картофелин дольками',
        '2 моркови крупными кусками',
        '2 крупных кабачка полукольцами',
        '1 луковица + 1 стакан зелёного лука',
        '1 стакан мяты + 1 стакан петрушки',
        '1 стебель сельдерея с листьями',
        '2 зубчика чеснока',
        '1⅓ стакана (320 мл) томатной пассы',
        '⅔ стакана (160 мл) оливкового масла',
        '1 стакан (240 мл) воды',
        '1¼ ч.л. соли, ¼ ч.л. перца, 3 лавровых листа',
      ],
      [
        '6 μέτριες πατάτες σε φέτες',
        '2 καρότα χοντρά',
        '2 μεγάλα κολοκυθάκια σε μισοφέτες',
        '1 κρεμμύδι + 1 φλ. φρέσκο κρεμμύδι',
        '1 φλ. δυόσμο + 1 φλ. μαϊντανό',
        '1 σέλινο με φύλλα',
        '2 σκελίδες σκόρδο',
        '1⅓ φλ. (320 ml) passata',
        '⅔ φλ. (160 ml) ελαιόλαδο',
        '1 φλ. (240 ml) νερό',
        '1¼ κ.γ. αλάτι, ¼ κ.γ. πιπέρι, 3 φύλλα δάφνης',
      ],
    ),
    steps: lines(
      [
        'Heat oven to 190°C / 375°F. In a large roasting pan, toss all vegetables, herbs, garlic, passata, oil, water, salt, pepper, and bay.',
        'Spread in a fairly even layer. Cover with foil and bake 40 minutes.',
        'Uncover, stir gently, and bake another 30–35 minutes until potatoes are soft and edges caramelise.',
        'Rest 10 minutes. Serve ~280 g; spoon the tomato juices over each plate.',
      ],
      [
        'Духовка 190°C. Смешайте овощи, зелень, чеснок, пассу, масло, воду, соль, перец, лавр.',
        'Ровным слоем. Под фольгой 40 мин.',
        'Снимите фольгу, перемешайте; ещё 30–35 мин до мягкости картофеля.',
        '10 мин отдохнуть. Порция ~280 г с соком.',
      ],
      [
        'Φούρνος 190°C. Ανακατέψτε όλα τα λαχανικά, βότανα, σκόρδο, passata, λάδι, νερό, αλάτι, πιπέρι, δάφνη.',
        'Απλώστε. Καλύψτε με αλουμινόχαρτο 40 λεπτά.',
        'Ξεσκεπάστε, ανακατέψτε· άλλα 30–35 λεπτά μέχρι μαλακές πατάτες.',
        'Ξεκούραση 10 λεπτά. Μερίδα ~280 γρ. με τους χυμούς.',
      ],
    ),
    tips: lines(
      [
        'Cut pieces a similar size so everything finishes together.',
        'Leftovers reheat well and taste even better the next day.',
      ],
      [
        'Режьте одинаково по размеру.',
        'На второй день ещё вкуснее.',
      ],
      [
        'Κόψτε περίπου ίδιο μέγεθος.',
        'Τα περισσεύματα είναι καλύτερα την άλλη μέρα.',
      ],
    ),
  }),
  R({
    id: 'fasolatha',
    level: 'wine_oil',
    category: 'soup',
    difficulty: 'easy',
    prepMinutes: 15,
    cookMinutes: 90,
    servings: 6,
    servingSize: L('1 bowl (~350 ml)', '1 миска (~350 мл)', '1 μπολ (~350 ml)'),
    title: L('Fasolatha', 'Фасолада', 'Φασολάδα'),
    summary: L(
      'Greek white bean soup with carrot, celery, leek, and a bright lemon finish — olive oil for wine-and-oil days.',
      'Греческий суп из белой фасоли с овощами и лимоном — с оливковым маслом.',
      'Ελληνική σούπα άσπρων φασολιών με λαχανικά και λεμόνι — με ελαιόλαδο.',
    ),
    ingredients: lines(
      [
        '1⅔ cups (300 g) dried white kidney or cannellini beans, soaked overnight',
        '1 onion, chopped',
        '2 carrots, chopped',
        '2 celery stalks, chopped',
        '1 leek (white part), chopped',
        '½ cup (120 ml) olive oil',
        '9 cups (2.1 L) water',
        'Juice of 2 lemons',
        '3 tbsp flour (optional, to thicken)',
        '1 tsp fine salt, pepper to taste',
      ],
      [
        '1⅔ стакана (300 г) сухой белой фасоли, замоченной',
        '1 луковица',
        '2 моркови',
        '2 стебля сельдерея',
        '1 лук-порей (белая часть)',
        '½ стакана (120 мл) оливкового масла',
        '9 стаканов (2,1 л) воды',
        'Сок 2 лимонов',
        '3 ст.л. муки (по желанию)',
        '1 ч.л. соли, перец',
      ],
      [
        '1⅔ φλ. (300 γρ.) ξερά άσπρα φασόλια, μουλιασμένα',
        '1 κρεμμύδι',
        '2 καρότα',
        '2 σέλινα',
        '1 πράσο (άσπρο)',
        '½ φλ. (120 ml) ελαιόλαδο',
        '9 φλ. (2,1 L) νερό',
        'Χυμός 2 λεμονιών',
        '3 κ.σ. αλεύρι (προαιρετικά)',
        '1 κ.γ. αλάτι, πιπέρι',
      ],
    ),
    steps: lines(
      [
        'Drain soaked beans. In a large pot, warm half the oil; soften onion, leek, carrot, and celery 8 minutes.',
        'Add beans and water. Bring to a boil, skim foam, then simmer gently 60–75 minutes until beans are creamy-soft.',
        'Season with salt and pepper. Optional: whisk flour with a ladle of hot broth, stir back in, and simmer 5 minutes to thicken.',
        'Off heat, stir in lemon juice and remaining oil. Taste and add more lemon if needed. Serve ~350 ml.',
      ],
      [
        'Откиньте фасоль. В половине масла обжарьте лук, порей, морковь, сельдерей 8 мин.',
        'Добавьте фасоль и воду. Вскипятите, снимите пену; варите 60–75 мин до мягкости.',
        'Посолите. По желанию: муку разведите бульоном, влейте, ещё 5 мин.',
        'Снимите с огня: лимон и оставшееся масло. Порция ~350 мл.',
      ],
      [
        'Στραγγίξτε τα φασόλια. Με το μισό λάδι μαλακώστε κρεμμύδι, πράσο, καρότο, σέλινο 8 λεπτά.',
        'Φασόλια και νερό. Βράστε, αφαιρέστε αφρό· σιγοβράστε 60–75 λεπτά.',
        'Αλάτι. Προαιρετικά: αλεύρι με ζωμό, άλλα 5 λεπτά.',
        'Κλείστε τη φωτιά· λεμόνι και υπόλοιπο λάδι. Μερίδα ~350 ml.',
      ],
    ),
    tips: lines(
      [
        'Canned white beans: use 3 cans rinsed; simmer vegetables 20 minutes, then add beans 15 minutes.',
        'For a tomato fasolatha, add ½ cup passata with the water.',
      ],
      [
        'Консервы: 3 банки; овощи 20 мин, затем фасоль 15 мин.',
        'С томатом — ½ стакана пассы вместе с водой.',
      ],
      [
        'Κονσέρβα: 3 κουτιά· λαχανικά 20 λεπτά, μετά φασόλια 15.',
        'Με ντομάτα — ½ φλ. passata μαζί με το νερό.',
      ],
    ),
  }),
  R({
    id: 'semolina-halva',
    level: 'wine_oil',
    category: 'sweet',
    difficulty: 'medium',
    prepMinutes: 10,
    cookMinutes: 35,
    servings: 10,
    servingSize: L('1 slice (~80 g)', '1 кусок (~80 г)', '1 κομμάτι (~80 γρ.)'),
    title: L('Semolina halva', 'Манный халва', 'Χαλβάς σιμιγδαλιού'),
    summary: L(
      'Classic Greek Lenten halva — toasted semolina in spiced syrup with olive oil, raisins, and citrus peel.',
      'Классическая греческая постная халва — манка в пряном сиропе с маслом, изюмом и цедрой.',
      'Κλασικός νηστίσιμος χαλβάς — σιμιγδάλι σε αρωματισμένο σιρόπι με λάδι και σταφίδες.',
    ),
    ingredients: lines(
      [
        '6 cups (1.4 L) water',
        '2 cups (400 g) sugar',
        'Peel of 1 lemon + peel of 1 orange',
        '3 cinnamon sticks + 4 cardamom pods (optional)',
        '1 cup (240 ml) olive oil',
        '2 cups (320 g) coarse or medium semolina',
        '½ cup (75 g) raisins',
        '1 tbsp orange-blossom water (optional)',
      ],
      [
        '6 стаканов (1,4 л) воды',
        '2 стакана (400 г) сахара',
        'Цедра 1 лимона + 1 апельсина',
        '3 палочки корицы + 4 коробочки кардамона (по желанию)',
        '1 стакан (240 мл) оливкового масла',
        '2 стакана (320 г) манки (грубой или средней)',
        '½ стакана (75 г) изюма',
        '1 ст.л. апельсиновой воды (по желанию)',
      ],
      [
        '6 φλ. (1,4 L) νερό',
        '2 φλ. (400 γρ.) ζάχαρη',
        'Φλούδα 1 λεμονιού + 1 πορτοκαλιού',
        '3 ξύλα κανέλας + 4 κάρδαμο (προαιρετικά)',
        '1 φλ. (240 ml) ελαιόλαδο',
        '2 φλ. (320 γρ.) χοντρό ή μέτριο σιμιγδάλι',
        '½ φλ. (75 γρ.) σταφίδες',
        '1 κ.σ. ανθόνερο πορτοκαλιού (προαιρετικά)',
      ],
    ),
    steps: lines(
      [
        'Syrup: simmer water, sugar, citrus peels, cinnamon, and cardamom 10 minutes. Keep hot; remove peels and spices before pouring.',
        'In a wide pot, warm the oil. Add semolina and toast over medium heat, stirring constantly, until golden and nutty (8–12 minutes).',
        'Carefully pour in the hot syrup (it will bubble vigorously). Stir until smooth. Add raisins and orange-blossom water if using.',
        'Cook, stirring, until the mixture pulls from the sides and thickens (5–8 minutes).',
        'Press into an oiled mould or pan. Cool completely, then slice. About 10 portions (~80 g).',
      ],
      [
        'Сироп: вода, сахар, цедра, корица, кардамон 10 мин. Держите горячим; специи уберите.',
        'В масле обжарьте манку, постоянно мешая, до золотистого цвета (8–12 мин).',
        'Осторожно влейте горячий сироп (будет кипеть). Размешайте. Добавьте изюм и апельсиновую воду.',
        'Мешайте 5–8 мин до густоты.',
        'Утрамбуйте в форму. Остудите, нарежьте. ~10 порций (~80 г).',
      ],
      [
        'Σιρόπι: νερό, ζάχαρη, φλούδες, κανέλα, κάρδαμο 10 λεπτά. Κρατήστε ζεστό.',
        'Στο λάδι καβουρδίστε το σιμιγδάλι μέχρι χρυσαφένιο (8–12 λεπτά), ανακατεύοντας.',
        'Ρίξτε προσεκτικά το καυτό σιρόπι. Ανακατέψτε. Σταφίδες και ανθόνερο.',
        '5–8 λεπτά μέχρι να δέσει.',
        'Βάλτε σε φόρμα. Κρυώστε, κόψτε. ~10 μερίδες (~80 γρ.).',
      ],
    ),
    tips: lines(
      [
        'Stand back when adding syrup — steam rises fast.',
        'Coarser semolina gives a more traditional grainy texture.',
      ],
      [
        'Отстранитесь при вливании сиропа — пар резко поднимается.',
        'Крупная манка — более традиционная текстура.',
      ],
      [
        'Προσοχή στο σιρόπι — βγάζει πολύ ατμό.',
        'Χοντρό σιμιγδάλι = πιο παραδοσιακή υφή.',
      ],
    ),
  }),
  R({
    id: 'artichoke-stew',
    level: 'wine_oil',
    category: 'main',
    difficulty: 'medium',
    prepMinutes: 20,
    cookMinutes: 45,
    servings: 5,
    servingSize: L('1 bowl (~300 g)', '1 миска (~300 г)', '1 μπολ (~300 γρ.)'),
    title: L('Artichoke stew (à la polita)', 'Артишоки по-политски', 'Αγκινάρες αλά πολίτα'),
    summary: L(
      'Artichokes with potato, carrot, and peas in a lemony dill sauce — Constantinopolitan-style Lenten stew with oil.',
      'Артишоки с картофелем, морковью и горошком в лимонно-укропном соусе — политский пост с маслом.',
      'Αγκινάρες με πατάτα, καρότο και αρακά σε λεμονάτη σάλτσα με άνηθο — αλά πολίτα με λάδι.',
    ),
    ingredients: lines(
      [
        '¾ cup (180 ml) olive oil',
        '1 onion, chopped',
        '750 g frozen artichoke bottoms (no need to thaw)',
        '4 carrots, cut in chunks',
        '4 medium potatoes, large chunks',
        '500 g frozen peas, thawed',
        '¼ cup tomato sauce + ½ cup hot water',
        '1½ tsp salt, ½ tsp pepper',
        '¼ cup fresh dill, chopped',
        'Juice of 1½ lemons',
        '1 tbsp flour (optional, for a thicker avgolemono-style finish without egg)',
      ],
      [
        '¾ стакана (180 мл) оливкового масла',
        '1 луковица',
        '750 г замороженных донышек артишоков',
        '4 моркови кусками',
        '4 средних картофелины',
        '500 г горошка, размороженного',
        '¼ стакана томатного соуса + ½ стакана горячей воды',
        '1½ ч.л. соли, ½ ч.л. перца',
        '¼ стакана укропа',
        'Сок 1½ лимонов',
        '1 ст.л. муки (по желанию, для густоты)',
      ],
      [
        '¾ φλ. (180 ml) ελαιόλαδο',
        '1 κρεμμύδι',
        '750 γρ. κατεψυγμένοι πάτοι αγκινάρας',
        '4 καρότα χοντρά',
        '4 μέτριες πατάτες',
        '500 γρ. αρακάς, ξεπαγωμένος',
        '¼ φλ. ντομάτα + ½ φλ. καυτό νερό',
        '1½ κ.γ. αλάτι, ½ κ.γ. πιπέρι',
        '¼ φλ. άνηθο',
        'Χυμός 1½ λεμονιών',
        '1 κ.σ. αλεύρι (προαιρετικά)',
      ],
    ),
    steps: lines(
      [
        'Warm oil in a wide pot; soften onion 5 minutes. Add artichokes and carrots; cook 5 minutes, stirring.',
        'Add tomato sauce, hot water, potatoes, salt, and pepper. Cover and simmer 25–30 minutes until potatoes are tender.',
        'Stir in peas and dill; cook 5 minutes more.',
        'Optional: whisk flour with lemon juice and a ladle of hot broth, then stir into the pot and simmer 2 minutes to thicken.',
        'Otherwise stir lemon juice in off heat. Taste and adjust. Serve ~300 g.',
      ],
      [
        'В масле обжарьте лук 5 мин. Добавьте артишоки и морковь; ещё 5 мин.',
        'Томатный соус, вода, картофель, соль, перец. Под крышкой 25–30 мин.',
        'Горошек и укроп; ещё 5 мин.',
        'По желанию: муку с лимоном и бульоном влейте, 2 мин для густоты.',
        'Или просто лимон в конце. Порция ~300 г.',
      ],
      [
        'Στο λάδι μαλακώστε κρεμμύδι 5 λεπτά. Αγκινάρες και καρότα άλλα 5.',
        'Ντομάτα, νερό, πατάτες, αλάτι, πιπέρι. Σκεπαστά 25–30 λεπτά.',
        'Αρακάς και άνηθος· άλλα 5 λεπτά.',
        'Προαιρετικά: αλεύρι με λεμόνι και ζωμό· 2 λεπτά να δέσει.',
        'Αλλιώς λεμόνι στο τέλος. Μερίδα ~300 γρ.',
      ],
    ),
    tips: lines(
      [
        'Fresh artichokes work if trimmed carefully; keep in lemon water while prepping.',
        'Plenty of dill and lemon is the signature of à la polita.',
      ],
      [
        'Свежие артишоки — очистите и держите в лимонной воде.',
        'Много укропа и лимона — характер политского стиля.',
      ],
      [
        'Φρέσκες αγκινάρες — καθαρίστε και κρατήστε σε νερό με λεμόνι.',
        'Πολύ άνηθος και λεμόνι = αλά πολίτα.',
      ],
    ),
  }),
  R({
    id: 'black-eyed-spinach',
    level: 'wine_oil',
    category: 'main',
    difficulty: 'easy',
    prepMinutes: 15,
    cookMinutes: 55,
    servings: 4,
    servingSize: L('1 bowl (~300 g)', '1 миска (~300 г)', '1 μπολ (~300 γρ.)'),
    title: L(
      'Black-eyed peas with spinach',
      'Фасоль чёрный глаз со шпинатом',
      'Μαυρομάτικα με σπανάκι',
    ),
    summary: L(
      'Black-eyed peas simmered with spinach, parsley, and tomato — a simple Greek Lenten pot for oil days.',
      'Фасоль чёрный глаз со шпинатом, петрушкой и томатом — простое греческое постное блюдо с маслом.',
      'Μαυρομάτικα με σπανάκι, μαϊντανό και ντομάτα — απλό νηστίσιμο με λάδι.',
    ),
    ingredients: lines(
      [
        '1 cup (200 g) dried black-eyed peas, soaked 4 hours or overnight',
        '850 g fresh spinach (or 2 large bags), washed',
        '1 cup flat-leaf parsley, chopped',
        '1 onion, finely chopped',
        '½ cup (120 ml) olive oil',
        '2 cups (480 ml) tomato juice or passata',
        '1¼ tsp salt, 1 tsp black pepper',
      ],
      [
        '1 стакан (200 г) сухой фасоли чёрный глаз, замоченной',
        '850 г свежего шпината',
        '1 стакан петрушки',
        '1 луковица',
        '½ стакана (120 мл) оливкового масла',
        '2 стакана (480 мл) томатного сока или пассы',
        '1¼ ч.л. соли, 1 ч.л. перца',
      ],
      [
        '1 φλ. (200 γρ.) ξερά μαυρομάτικα, μουλιασμένα',
        '850 γρ. φρέσκο σπανάκι',
        '1 φλ. μαϊντανό',
        '1 κρεμμύδι',
        '½ φλ. (120 ml) ελαιόλαδο',
        '2 φλ. (480 ml) χυμό ντομάτας ή passata',
        '1¼ κ.γ. αλάτι, 1 κ.γ. πιπέρι',
      ],
    ),
    steps: lines(
      [
        'Boil soaked peas in fresh water until tender, 30–40 minutes. Drain, reserving ½ cup cooking liquid.',
        'In a wide pot, warm oil; soften onion 5 minutes. Add tomato juice, salt, and pepper; simmer 5 minutes.',
        'Add spinach in handfuls until wilted, then parsley and the drained peas. Add a splash of reserved liquid if dry.',
        'Simmer uncovered 10–15 minutes until the sauce coats the peas. Serve ~300 g warm or room temperature.',
      ],
      [
        'Варите фасоль 30–40 мин до мягкости. Откиньте, оставьте ½ стакана отвара.',
        'В масле обжарьте лук 5 мин. Томат, соль, перец — 5 мин.',
        'Шпинат горстями до увядания, петрушка и фасоль. При необходимости — отвар.',
        '10–15 мин без крышки. Порция ~300 г.',
      ],
      [
        'Βράστε τα μαυρομάτικα 30–40 λεπτά. Στραγγίξτε· κρατήστε ½ φλ. ζουμί.',
        'Στο λάδι μαλακώστε κρεμμύδι 5 λεπτά. Ντομάτα, αλάτι, πιπέρι — 5 λεπτά.',
        'Σπανάκι χούφτες-χούφτες, μαϊντανός και φασόλια. Λίγο ζουμί αν χρειάζεται.',
        '10–15 λεπτά ακάλυπτα. Μερίδα ~300 γρ.',
      ],
    ),
    tips: lines(
      [
        'Frozen spinach works — thaw and squeeze out excess water first.',
        'Canned black-eyed peas: rinse and skip the long boil; simmer 15 minutes total with the greens.',
      ],
      [
        'Замороженный шпинат — разморозьте и отожмите.',
        'Консервы чёрный глаз — промойте; тушите со шпинатом ~15 мин.',
      ],
      [
        'Κατεψυγμένο σπανάκι — ξεπαγώστε και στύψτε.',
        'Κονσέρβα μαυρομάτικα — ξεπλύνετε· σιγοβράστε ~15 λεπτά με τα χόρτα.',
      ],
    ),
  }),
];

export const FASTING_RECIPES: readonly FastingRecipe[] = [
  ...CORE_FASTING_RECIPES,
  ...MIA_KOUPPA_EXTRA_RECIPES,
  ...MARILENA_EXTRA_RECIPES,
];
