/** Map orthocal / KJV book abbreviations to getBible book numbers (1–66). */
const USFM_TO_NR: Record<string, number> = {
  GEN: 1,
  EXO: 2,
  LEV: 3,
  NUM: 4,
  DEU: 5,
  JOS: 6,
  JDG: 7,
  RUT: 8,
  '1SA': 9,
  '2SA': 10,
  '1KI': 11,
  '2KI': 12,
  '1CH': 13,
  '2CH': 14,
  EZR: 15,
  NEH: 16,
  EST: 17,
  JOB: 18,
  PSA: 19,
  PRO: 20,
  ECC: 21,
  SNG: 22,
  ISA: 23,
  JER: 24,
  LAM: 25,
  EZK: 26,
  DAN: 27,
  HOS: 28,
  JOL: 29,
  AMO: 30,
  OBA: 31,
  JON: 32,
  MIC: 33,
  NAM: 34,
  HAB: 35,
  ZEP: 36,
  HAG: 37,
  ZEC: 38,
  MAL: 39,
  MAT: 40,
  MRK: 41,
  LUK: 42,
  JHN: 43,
  ACT: 44,
  ROM: 45,
  '1CO': 46,
  '2CO': 47,
  GAL: 48,
  EPH: 49,
  PHP: 50,
  COL: 51,
  '1TH': 52,
  '2TH': 53,
  '1TI': 54,
  '2TI': 55,
  TIT: 56,
  PHM: 57,
  HEB: 58,
  JAS: 59,
  '1PE': 60,
  '2PE': 61,
  '1JN': 62,
  '2JN': 63,
  '3JN': 64,
  JUD: 65,
  REV: 66,
};

const ALIAS_TO_USFM: Record<string, string> = {
  gen: 'GEN',
  genesis: 'GEN',
  exod: 'EXO',
  exodus: 'EXO',
  lev: 'LEV',
  leviticus: 'LEV',
  num: 'NUM',
  numbers: 'NUM',
  deut: 'DEU',
  deuteronomy: 'DEU',
  josh: 'JOS',
  joshua: 'JOS',
  judges: 'JDG',
  judg: 'JDG',
  ruth: 'RUT',
  '1 kgs': '1SA',
  '1 kings': '1SA',
  '2 kgs': '2SA',
  '2 kings': '2SA',
  '3 kgs': '1KI',
  '3 kings': '1KI',
  '4 kgs': '2KI',
  '4 kings': '2KI',
  '1 chr': '1CH',
  '1 chronicles': '1CH',
  '2 chr': '2CH',
  '2 chronicles': '2CH',
  ezra: 'EZR',
  neh: 'NEH',
  nehemiah: 'NEH',
  esth: 'EST',
  esther: 'EST',
  job: 'JOB',
  ps: 'PSA',
  psalm: 'PSA',
  psalms: 'PSA',
  prov: 'PRO',
  proverbs: 'PRO',
  eccl: 'ECC',
  ecclesiastes: 'ECC',
  song: 'SNG',
  isa: 'ISA',
  isaiah: 'ISA',
  jer: 'JER',
  jeremiah: 'JER',
  ezek: 'EZK',
  ezekiel: 'EZK',
  dan: 'DAN',
  daniel: 'DAN',
  matt: 'MAT',
  matthew: 'MAT',
  mt: 'MAT',
  mark: 'MRK',
  mk: 'MRK',
  luke: 'LUK',
  lk: 'LUK',
  john: 'JHN',
  jn: 'JHN',
  acts: 'ACT',
  rom: 'ROM',
  '1 cor': '1CO',
  '1 corinthians': '1CO',
  '2 cor': '2CO',
  '2 corinthians': '2CO',
  gal: 'GAL',
  galatians: 'GAL',
  eph: 'EPH',
  ephesians: 'EPH',
  phil: 'PHP',
  philippians: 'PHP',
  col: 'COL',
  colossians: 'COL',
  '1 thess': '1TH',
  '1 thessalonians': '1TH',
  '2 thess': '2TH',
  '2 thessalonians': '2TH',
  '1 tim': '1TI',
  '1 timothy': '1TI',
  '2 tim': '2TI',
  '2 timothy': '2TI',
  titus: 'TIT',
  tit: 'TIT',
  heb: 'HEB',
  hebrews: 'HEB',
  jas: 'JAS',
  james: 'JAS',
  '1 pet': '1PE',
  '1 peter': '1PE',
  '2 pet': '2PE',
  '2 peter': '2PE',
  '1 john': '1JN',
  '1 jn': '1JN',
  jude: 'JUD',
  rev: 'REV',
  revelation: 'REV',
};

function normalizeAlias(name: string): string {
  return name.replace(/\./g, '').replace(/\s+/g, ' ').trim().toLowerCase();
}

export function getBibleBookNumber(bookName: string): number | null {
  const usfm = bookName.replace(/\./g, '').replace(/\s+/g, '').trim().toUpperCase();
  const byUsfm = USFM_TO_NR[usfm];
  if (byUsfm !== undefined) return byUsfm;

  const cleaned = normalizeAlias(bookName);
  const mapped = ALIAS_TO_USFM[cleaned];
  if (!mapped) return null;
  return USFM_TO_NR[mapped] ?? null;
}
